{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrev-35snb\/masklocationproviding\/providesnapshotmask()"]}],"metadata":{"externalID":"s:9DevRevSDK0aB0C21MaskLocationProvidingP015provideSnapshotD0AA0hD0CyYaF","title":"provideSnapshotMask()","required":true,"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"provideSnapshotMask","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SnapshotMask","text":"SnapshotMask"}],"role":"symbol","modules":[{"name":"DevRevSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideSnapshotMask","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SnapshotMask","text":"SnapshotMask","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask"}]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"An object describing the regions to be masked or whether the snapshot should be skipped.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Provides the current snapshot mask configuration."}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding\/provideSnapshotMask()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","title":"DevRevSDK","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","abstract":[],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb":{"navigatorTitle":[{"kind":"identifier","text":"DevRev"}],"abstract":[{"type":"text","text":"An entry point to the DevRev SDK."}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRev"}],"title":"DevRev","url":"\/documentation\/devrevsdk\/devrev-35snb"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/MaskLocationProviding":{"kind":"symbol","abstract":[{"type":"text","text":"A protocol for providing explicit masking locations for UI snapshots."}],"url":"\/documentation\/devrevsdk\/devrev-35snb\/masklocationproviding","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MaskLocationProviding","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding","navigatorTitle":[{"kind":"identifier","text":"MaskLocationProviding"}],"role":"symbol","type":"topic","title":"DevRev.MaskLocationProviding"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask":{"kind":"symbol","abstract":[{"type":"text","text":"A class that describes the regions of a snapshot to be masked for privacy purposes."}],"url":"\/documentation\/devrevsdk\/snapshotmask","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SnapshotMask","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","navigatorTitle":[{"kind":"identifier","text":"SnapshotMask"}],"role":"symbol","type":"topic","title":"SnapshotMask"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/MaskLocationProviding/provideSnapshotMask()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"provideSnapshotMask","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SnapshotMask","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SnapshotMask"}],"kind":"symbol","title":"provideSnapshotMask()","url":"\/documentation\/devrevsdk\/devrev-35snb\/masklocationproviding\/providesnapshotmask()","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding\/provideSnapshotMask()","type":"topic","required":true,"abstract":[{"type":"text","text":"Provides the current snapshot mask configuration."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/title","value":"SnapshotMask"},{"value":[{"text":"SnapshotMask","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/navigatorTitle","value":[{"text":"SnapshotMask","kind":"identifier"}],"op":"replace"}]}]}