{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Configures the SDK with the app ID and feature configuration."}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/devrev-35snb\/configure(appid:featureconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"appID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"s:9DevRevSDK0aB0C9configure5appID20featureConfigurationySS_AA07FeatureH0CtFZ","roleHeading":"Type Method","title":"configure(appID:featureConfiguration:)","modules":[{"name":"DevRevSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/configure(appID:featureConfiguration:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"text":"appID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureConfiguration"},{"kind":"text","text":": "},{"text":"FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An identifier unique to your app.","type":"text"}]}],"name":"appID"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"This is a mandatory method before using any other features."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/configure(appID:featureConfiguration:)":{"title":"configure(appID:featureConfiguration:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/configure(appID:featureConfiguration:)","url":"\/documentation\/devrevsdk\/devrev-35snb\/configure(appid:featureconfiguration:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configures the SDK with the app ID and feature configuration."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"text":"appID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureConfiguration"},{"text":": ","kind":"text"},{"text":"FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb":{"title":"DevRev","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","navigatorTitle":[{"text":"DevRev","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrev-35snb","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An entry point to the DevRev SDK."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRev"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","value":"FeatureConfiguration","op":"replace"},{"value":[{"text":"FeatureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments"},{"value":[{"text":"FeatureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle"}]}]}