{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MaskLocationProviding","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Conform to this protocol to supply custom logic for determining which regions of a UI snapshot should be masked"},{"text":" ","type":"text"},{"text":"for privacy purposes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Implementers are expected to return a "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","isActive":true},{"type":"text","text":" in the completion handler describing the areas to be"},{"text":" ","type":"text"},{"text":"obscured or whether the snapshot should be skipped entirely.","type":"text"}]},{"style":"important","content":[{"inlineContent":[{"text":"Use this protocol to help protect user privacy by specifying sensitive regions that should not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"appear in the captured snapshots."}],"type":"paragraph"}],"name":"Important","type":"aside"}],"kind":"content"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb"]]},"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"MaskLocationProviding"}],"modules":[{"name":"DevRevSDK"}],"externalID":"s:9DevRevSDK0aB0C21MaskLocationProvidingP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MaskLocationProviding"}],"role":"symbol","title":"DevRev.MaskLocationProviding","extendedModule":"DevRevSDK","symbolKind":"protocol"},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding\/provideSnapshotMask(_:)"]}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrev-35snb\/masklocationproviding"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"A protocol for providing explicit masking locations for UI snapshots.","type":"text"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/MaskLocationProviding/provideSnapshotMask(_:)":{"abstract":[{"type":"text","text":"Provides the current snapshot mask configuration."}],"kind":"symbol","title":"provideSnapshotMask(_:)","required":true,"role":"symbol","url":"\/documentation\/devrevsdk\/devrev-35snb\/masklocationproviding\/providesnapshotmask(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding\/provideSnapshotMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"provideSnapshotMask"},{"kind":"text","text":"(("},{"text":"SnapshotMask","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SnapshotMask"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/MaskLocationProviding":{"navigatorTitle":[{"kind":"identifier","text":"MaskLocationProviding"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/MaskLocationProviding","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MaskLocationProviding","kind":"identifier"}],"role":"symbol","title":"DevRev.MaskLocationProviding","abstract":[{"text":"A protocol for providing explicit masking locations for UI snapshots.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrev-35snb\/masklocationproviding"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb":{"title":"DevRev","type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrev-35snb","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRev","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","abstract":[{"type":"text","text":"An entry point to the DevRev SDK."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DevRev"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","title":"DevRevSDK","url":"\/documentation\/devrevsdk","role":"collection","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SnapshotMask"}],"title":"SnapshotMask","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SnapshotMask","kind":"identifier"}],"type":"topic","url":"\/documentation\/devrevsdk\/snapshotmask","kind":"symbol","abstract":[{"text":"A class that describes the regions of a snapshot to be masked for privacy purposes.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SnapshotMask","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/fragments","op":"replace","value":[{"text":"SnapshotMask","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SnapshotMask"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/navigatorTitle"}]}]}