{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","text":"DevRevDelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A delegate object, conforming to the "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","isActive":true},{"type":"text","text":" protocol."}],"type":"paragraph"}],"name":"delegate"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb"]]},"kind":"symbol","abstract":[{"type":"text","text":"Sets the DevRev delegate."}],"metadata":{"roleHeading":"Type Method","role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","kind":"typeIdentifier","text":"DevRevDelegate"},{"text":")","kind":"text"}],"externalID":"s:9DevRevSDK0aB0C11setDelegateyyAA0abE0_pFZ","title":"setDelegate(_:)","modules":[{"name":"DevRevSDK"}],"extendedModule":"DevRevSDK"},"variants":[{"paths":["\/documentation\/devrevsdk\/devrev-35snb\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/setDelegate(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","role":"collection"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRev","kind":"identifier"}],"navigatorTitle":[{"text":"DevRev","kind":"identifier"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrev-35snb","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","kind":"symbol","title":"DevRev","type":"topic","abstract":[{"text":"An entry point to the DevRev SDK.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/setDelegate(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/setDelegate(_:)","abstract":[{"text":"Sets the DevRev delegate.","type":"text"}],"title":"setDelegate(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrev-35snb\/setdelegate(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","kind":"typeIdentifier","text":"DevRevDelegate"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate":{"url":"\/documentation\/devrevsdk\/devrevdelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A delegate protocol that notifies the host app of DevRev SDK’s session events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevDelegate"}],"navigatorTitle":[{"text":"DevRevDelegate","kind":"identifier"}],"title":"DevRevDelegate"}},"variantOverrides":[{"patch":[{"value":"DevRevDelegate","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/title","op":"replace"},{"value":[{"text":"DevRevDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DevRevDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}