{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateFeatureConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","title":"updateFeatureConfiguration(_:)","modules":[{"name":"DevRevSDK"}],"externalID":"s:9DevRevSDK0aB0C26updateFeatureConfigurationyyAA0eF0CFZ"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb"]]},"abstract":[{"text":"Updates the feature configuration after the SDK has been configured.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateFeatureConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"featureConfiguration","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"featureConfiguration","content":[{"inlineContent":[{"text":"A new feature configuration object.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrev-35snb\/updatefeatureconfiguration(_:)"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/updateFeatureConfiguration(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb/updateFeatureConfiguration(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb\/updateFeatureConfiguration(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateFeatureConfiguration"},{"text":"(","kind":"text"},{"text":"FeatureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrev-35snb\/updatefeatureconfiguration(_:)","type":"topic","kind":"symbol","title":"updateFeatureConfiguration(_:)","abstract":[{"text":"Updates the feature configuration after the SDK has been configured.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"type":"topic","title":"FeatureConfiguration","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration","role":"symbol","navigatorTitle":[{"text":"FeatureConfiguration","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb":{"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","abstract":[{"text":"An entry point to the DevRev SDK.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrev-35snb","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRev"}],"title":"DevRev","navigatorTitle":[{"kind":"identifier","text":"DevRev"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"role":"collection","type":"topic","title":"DevRevSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","value":"FeatureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"text":"FeatureConfiguration","kind":"identifier"}]}]}]}