{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"locations","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Location","preciseIdentifier":"s:9DevRevSDK12SnapshotMaskC8LocationC","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"shouldSkip","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"externalID":"s:9DevRevSDK12SnapshotMaskC9locations10shouldSkipACSayAC8LocationCG_Sbtcfc","roleHeading":"Initializer","title":"init(locations:shouldSkip:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/snapshotmask\/init(locations:shouldskip:)"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/init(locations:shouldSkip:)"},"abstract":[{"type":"text","text":"Creates a snapshot mask configuration for external mask type."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"locations","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Location","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK12SnapshotMaskC8LocationC","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"shouldSkip"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The regions to be masked.","type":"text"}]}],"name":"locations"},{"name":"shouldSkip","content":[{"type":"paragraph","inlineContent":[{"text":"A flag whether the snapshot should be skipped entirely.","type":"text"}]}]}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/init(locations:shouldSkip:)":{"url":"\/documentation\/devrevsdk\/snapshotmask\/init(locations:shouldskip:)","role":"symbol","title":"init(locations:shouldSkip:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"locations","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Location","preciseIdentifier":"s:9DevRevSDK12SnapshotMaskC8LocationC"},{"text":"], ","kind":"text"},{"text":"shouldSkip","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/init(locations:shouldSkip:)","abstract":[{"text":"Creates a snapshot mask configuration for external mask type.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask":{"url":"\/documentation\/devrevsdk\/snapshotmask","role":"symbol","type":"topic","title":"SnapshotMask","navigatorTitle":[{"kind":"identifier","text":"SnapshotMask"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","abstract":[{"text":"A class that describes the regions of a snapshot to be masked for privacy purposes.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SnapshotMask","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/Location":{"url":"\/documentation\/devrevsdk\/snapshotmask\/location","role":"symbol","title":"SnapshotMask.Location","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Location"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location","abstract":[{"text":"A class that describes the regions with its mask type.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/title","value":"SnapshotMask","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/fragments","value":[{"kind":"identifier","text":"SnapshotMask"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/navigatorTitle","op":"replace","value":[{"text":"SnapshotMask","kind":"identifier"}]}]}]}