{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location"},"metadata":{"roleHeading":"Class","modules":[{"name":"DevRevSDK"}],"externalID":"s:9DevRevSDK12SnapshotMaskC8LocationC","symbolKind":"class","navigatorTitle":[{"text":"Location","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}],"title":"SnapshotMask.Location","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask"]]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location\/init(location:)"],"generated":true,"title":"Initializers"}],"abstract":[{"type":"text","text":"A class that describes the regions with its mask type."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/snapshotmask\/location"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://ai.devrev.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SQ"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/Location":{"url":"\/documentation\/devrevsdk\/snapshotmask\/location","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location","navigatorTitle":[{"text":"Location","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that describes the regions with its mask type."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}],"title":"SnapshotMask.Location","role":"symbol","kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/Location/init(location:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location\/init(location:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a location configuration for a specific mask type."}],"url":"\/documentation\/devrevsdk\/snapshotmask\/location\/init(location:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(location:)"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","url":"\/documentation\/devrevsdk","type":"topic","title":"DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","role":"symbol","url":"\/documentation\/devrevsdk\/snapshotmask","title":"SnapshotMask","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SnapshotMask","kind":"identifier"}],"abstract":[{"text":"A class that describes the regions of a snapshot to be masked for privacy purposes.","type":"text"}],"navigatorTitle":[{"text":"SnapshotMask","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SnapshotMask","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/fragments","value":[{"text":"SnapshotMask","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SnapshotMask","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}