{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/activateThirdPartyAnalyticsMonitor()"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"sections":[],"abstract":[{"text":"Activates the third party analytics monitoring system","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(activateThirdPartyAnalyticsMonitor) "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"},{"text":"()","kind":"text"}]}]}],"metadata":{"title":"activateThirdPartyAnalyticsMonitor()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activateThirdPartyAnalyticsMonitor","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)activateThirdPartyAnalyticsMonitor","roleHeading":"Type Method","modules":[{"name":"DevRevSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/userexperior\/activatethirdpartyanalyticsmonitor()"]},{"paths":["\/documentation\/devrevsdk\/userexperior\/activatethirdpartyanalyticsmonitor()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/activateThirdPartyAnalyticsMonitor()":{"abstract":[{"text":"Activates the third party analytics monitoring system","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/activateThirdPartyAnalyticsMonitor()","url":"\/documentation\/devrevsdk\/userexperior\/activatethirdpartyanalyticsmonitor()","title":"activateThirdPartyAnalyticsMonitor()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"activateThirdPartyAnalyticsMonitor","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"activateThirdPartyAnalyticsMonitor","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"activateThirdPartyAnalyticsMonitor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","value":"UserExperior"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","value":[{"kind":"identifier","text":"UserExperior"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1activateThirdPartyAnalyticsMonitor()\/title","value":"activateThirdPartyAnalyticsMonitor","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1activateThirdPartyAnalyticsMonitor()\/fragments"}]}]}