{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Mask given views. They will show as masked in portal playbacks."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(markSensitiveViewsWithViewToSecure:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"markSensitiveViews","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewsToSecure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"viewsToSecure      ","content":[{"inlineContent":[{"type":"text","text":"An array of views that should be masked"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/markSensitiveViews(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"metadata":{"title":"markSensitiveViews(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"}],"roleHeading":"Type Method","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)markSensitiveViewsWithViewToSecure:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markSensitiveViews"},{"kind":"text","text":"("},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"DevRevSDK"}]},"variants":[{"paths":["\/documentation\/devrevsdk\/userexperior\/marksensitiveviews(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/userexperior\/marksensitiveviews(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/markSensitiveViews(_:)":{"abstract":[{"text":"Mask given views. They will show as masked in portal playbacks.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/markSensitiveViews(_:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"markSensitiveViews","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/marksensitiveviews(_:)","title":"markSensitiveViews(_:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"markSensitiveViewsWithViewToSecure:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"},{"kind":"text","text":"("},{"text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"viewsToSecure","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1markSensitiveViews(_:)\/title","value":"markSensitiveViewsWithViewToSecure:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1markSensitiveViews(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"}]},{"value":"UserExperior","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserExperior"}]}]}]}