{"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"DevRevSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseRecording"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)pauseRecording","roleHeading":"Type Method","navigatorTitle":[{"text":"pauseRecording","kind":"identifier"}],"title":"pauseRecording()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/userexperior\/pauserecording()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/userexperior\/pauserecording()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Pauses the ongoing user recording."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/pauseRecording()"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(pauseRecording) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseRecording"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/pauseRecording()":{"kind":"symbol","abstract":[{"type":"text","text":"Pauses the ongoing user recording."}],"url":"\/documentation\/devrevsdk\/userexperior\/pauserecording()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pauseRecording"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/pauseRecording()","title":"pauseRecording()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseRecording"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"pauseRecording"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pauseRecording"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"pauseRecording","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"UserExperior","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","op":"replace","value":[{"text":"UserExperior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1pauseRecording()\/title","value":"pauseRecording","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1pauseRecording()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"pauseRecording"}]}]}]}