{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setDelegate:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DevRevDelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/userexperior\/setdelegate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/userexperior\/setdelegate(_:)"]}],"metadata":{"title":"setDelegate(_:)","symbolKind":"method","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"modules":[{"name":"DevRevSDK"}],"role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)setDelegate:","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DevRevDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate"},{"kind":"text","text":")"}]},"kind":"symbol","abstract":[{"text":"Set User Experior Delegate","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setDelegate(_:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate":{"abstract":[{"type":"text","text":"A delegate protocol that notifies the host app of DevRev SDK’s session events."}],"title":"DevRevDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DevRevDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevDelegate"}],"url":"\/documentation\/devrevsdk\/devrevdelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/setDelegate(_:)":{"kind":"symbol","title":"setDelegate(_:)","abstract":[{"type":"text","text":"Set User Experior Delegate"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DevRevDelegate","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/devrevsdk\/userexperior\/setdelegate(_:)","type":"topic","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setDelegate(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setDelegate:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDelegate:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<DevRevDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DevRevSDK@objc(pl)DevRevDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","value":"UserExperior","op":"replace"},{"value":[{"text":"UserExperior","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","op":"replace"},{"value":"DevRevDelegate","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/fragments","value":[{"text":"DevRevDelegate","kind":"identifier"}],"op":"replace"},{"value":"setDelegate:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1setDelegate(_:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1setDelegate(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDelegate:"}]}]}]}