{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"abstract":[{"text":"Start user recording with framework and sdk version (In case of Hybrid platform ONLY)","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/userexperior\/startrecording(_:_:_:)"]},{"paths":["\/documentation\/devrevsdk\/userexperior\/startrecording(_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)startRecordingWithVersionKey:fw:sv:","modules":[{"name":"DevRevSDK"}],"role":"symbol","title":"startRecording(_:_:_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startRecording","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"startRecordingWithVersionKey:fw:sv:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(startRecordingWithVersionKey:fw:sv:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"versionKey","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"fw"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sv"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"versionKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string value of SDK version key"}]}]},{"name":"fw","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string value of SDK Framework - Applicable for hybrid platform"}]}]},{"name":"versionKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string value of the current SDK version"}]}]}]}],"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/startRecording(_:_:_:)":{"abstract":[{"text":"Start user recording with framework and sdk version (In case of Hybrid platform ONLY)","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:_:_:)","role":"symbol","title":"startRecording(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"startRecordingWithVersionKey:fw:sv:"}],"url":"\/documentation\/devrevsdk\/userexperior\/startrecording(_:_:_:)","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"startRecordingWithVersionKey:fw:sv:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startRecordingWithVersionKey:fw:sv:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startRecordingWithVersionKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"versionKey"},{"text":" ","kind":"text"},{"text":"fw:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fw","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sv:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"sv","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startRecording(_:_:_:)\/title","value":"startRecordingWithVersionKey:fw:sv:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startRecording(_:_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startRecordingWithVersionKey:fw:sv:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","value":"UserExperior","op":"replace"},{"op":"replace","value":[{"text":"UserExperior","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}