{"variants":[{"paths":["\/documentation\/devrevsdk\/userexperior\/stoptimer(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/userexperior\/stoptimer(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use endTimerWithName:properties: instead. In case of no property pass empty object as a properties.","type":"text"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(stopTimerWithName:) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopTimer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"timerName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)stopTimerWithName:","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopTimer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"text":"stopTimerWithName:","kind":"identifier"}],"title":"stopTimer(_:)","roleHeading":"Type Method","platforms":[],"symbolKind":"method"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/stopTimer(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:)","url":"\/documentation\/devrevsdk\/userexperior\/stoptimer(_:)","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"stopTimer(_:)","navigatorTitle":[{"text":"stopTimerWithName:","kind":"identifier"}],"abstract":[],"deprecated":true,"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"stopTimerWithName:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopTimerWithName:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"stopTimerWithName:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timerName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"stopTimerWithName:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopTimer(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopTimerWithName:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopTimer(_:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","value":"UserExperior","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","op":"replace","value":[{"text":"UserExperior","kind":"identifier"}]}]}]}