{"sections":[],"kind":"symbol","abstract":[{"text":"Stop masking all previously masked views. Effects only manually masked views","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(unmarkAllSensitives) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmarkAllSensitives","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkAllSensitives()"},"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)unmarkAllSensitives","modules":[{"name":"DevRevSDK"}],"role":"symbol","navigatorTitle":[{"text":"unmarkAllSensitives","kind":"identifier"}],"symbolKind":"method","roleHeading":"Type Method","title":"unmarkAllSensitives()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmarkAllSensitives"},{"kind":"text","text":"()"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/userexperior\/unmarkallsensitives()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/userexperior\/unmarkallsensitives()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/unmarkAllSensitives()":{"navigatorTitle":[{"text":"unmarkAllSensitives","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkAllSensitives()","kind":"symbol","title":"unmarkAllSensitives()","url":"\/documentation\/devrevsdk\/userexperior\/unmarkallsensitives()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmarkAllSensitives","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Stop masking all previously masked views. Effects only manually masked views"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"unmarkAllSensitives","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"unmarkAllSensitives","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unmarkAllSensitives"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"UserExperior","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","op":"replace"},{"value":[{"text":"UserExperior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkAllSensitives()\/title","value":"unmarkAllSensitives","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unmarkAllSensitives"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkAllSensitives()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}