{"abstract":[{"text":"Stop masking given views.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmarkSensitiveViews","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"unmarkSensitiveViewsWithViewToUnBlock:","kind":"identifier"}],"title":"unmarkSensitiveViews(_:)","roleHeading":"Type Method","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)unmarkSensitiveViewsWithViewToUnBlock:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/userexperior\/unmarksensitiveviews(_:)"]},{"paths":["\/documentation\/devrevsdk\/userexperior\/unmarksensitiveviews(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(unmarkSensitiveViewsWithViewToUnBlock:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unmarkSensitiveViews"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewsToUnblock"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewsToUnblock      ","content":[{"type":"paragraph","inlineContent":[{"text":"An array of views you want to stop masking.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"They will no longer show as masked in portal playbacks, unless they are auto masked.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkSensitiveViews(_:)"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/unmarkSensitiveViews(_:)":{"navigatorTitle":[{"kind":"identifier","text":"unmarkSensitiveViewsWithViewToUnBlock:"}],"url":"\/documentation\/devrevsdk\/userexperior\/unmarksensitiveviews(_:)","kind":"symbol","title":"unmarkSensitiveViews(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmarkSensitiveViews","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkSensitiveViews(_:)","abstract":[{"type":"text","text":"Stop masking given views."}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"unmarkSensitiveViewsWithViewToUnBlock:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unmarkSensitiveViewsWithViewToUnBlock:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unmarkSensitiveViewsWithViewToUnBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewsToUnblock"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"unmarkSensitiveViewsWithViewToUnBlock:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkSensitiveViews(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unmarkSensitiveViewsWithViewToUnBlock:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkSensitiveViews(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","op":"replace","value":"UserExperior"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","op":"replace","value":[{"text":"UserExperior","kind":"identifier"}]}]}]}