{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"updateRevUserData(revOrgId:revUserId:isAnonymous:)","externalID":"c:@M@DevRevSDK@objc(cs)UserExperior(cm)updateRevUserDataWithRevOrgId:revUserId:isAnonymous:","role":"symbol","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateRevUserData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"revOrgId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"revUserId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isAnonymous"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:"}],"roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/updateRevUserData(revOrgId:revUserId:isAnonymous:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(updateRevUserDataWithRevOrgId:revUserId:isAnonymous:) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRevUserData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"revOrgId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"revUserId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"isAnonymous","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/userexperior\/updaterevuserdata(revorgid:revuserid:isanonymous:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/userexperior\/updaterevuserdata(revorgid:revuserid:isanonymous:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/updateRevUserData(revOrgId:revUserId:isAnonymous:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/updateRevUserData(revOrgId:revUserId:isAnonymous:)","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateRevUserData","kind":"identifier"},{"kind":"text","text":"("},{"text":"revOrgId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"revUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAnonymous"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"url":"\/documentation\/devrevsdk\/userexperior\/updaterevuserdata(revorgid:revuserid:isanonymous:)","type":"topic","kind":"symbol","title":"updateRevUserData(revOrgId:revUserId:isAnonymous:)","navigatorTitle":[{"kind":"identifier","text":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"updateRevUserDataWithRevOrgId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"revOrgId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"revUserId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"revUserId"},{"kind":"text","text":" "},{"text":"isAnonymous:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isAnonymous"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"UserExperior","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title"},{"value":[{"text":"UserExperior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1updateRevUserData(revOrgId:revUserId:isAnonymous:)\/title","op":"replace","value":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1updateRevUserData(revOrgId:revUserId:isAnonymous:)\/fragments"}]}]}