{"metadata":{"modules":[{"name":"DevRevSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"domains","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"externalID":"s:9DevRevSDK8IdentityC13AccountTraitsC7domainsSaySSGSgvp","role":"symbol","roleHeading":"Instance Property","title":"domains","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class\/domains","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The domains of the account.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"domains"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/identity\/accounttraits-swift.class\/domains"]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"kind":"symbol","url":"\/documentation\/devrevsdk\/identity","title":"Identity","type":"topic","role":"symbol","abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"type":"text","text":" "},{"text":"The minimum information needed is the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Identity","kind":"identifier"}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid","title":"userID","type":"topic","role":"symbol","abstract":[{"text":"A user identifier.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"userID","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/AccountTraits-swift.class":{"abstract":[{"text":"A collection of traits describing the account.","type":"text"}],"navigatorTitle":[{"text":"AccountTraits","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.class","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","title":"Identity.AccountTraits","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountTraits"}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/AccountTraits-swift.class/domains":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class\/domains","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"domains"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.class\/domains","abstract":[{"text":"The domains of the account.","type":"text"}],"title":"domains","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"kind":"identifier","text":"Identity"}],"op":"replace"},{"value":[{"kind":"identifier","text":"Identity"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle"},{"value":"userID","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}],"op":"replace"}]}]}