{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/autostartrecording"]},{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/autostartrecording"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(py)autoStartRecording","roleHeading":"Instance Property","title":"autoStartRecording","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"autoStartRecording","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"autoStartRecording"}],"modules":[{"name":"DevRevSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/autoStartRecording"},"kind":"symbol","abstract":[{"text":"Automatically starts session recording after SDK configuration.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"autoStartRecording","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","kind":"symbol","url":"\/documentation\/devrevsdk","type":"topic","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","role":"symbol","type":"topic","title":"FeatureConfiguration","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"kind":"symbol","navigatorTitle":[{"text":"FeatureConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/featureconfiguration"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/autoStartRecording":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/autoStartRecording","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/featureconfiguration\/autostartrecording","title":"autoStartRecording","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoStartRecording","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Automatically starts session recording after SDK configuration.","type":"text"}],"navigatorTitle":[{"text":"autoStartRecording","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"autoStartRecording"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"autoStartRecording","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoStartRecording"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"FeatureConfiguration","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace"},{"value":"autoStartRecording","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1autoStartRecording\/title"},{"value":[{"kind":"identifier","text":"autoStartRecording"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1autoStartRecording\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}