{"sections":[],"metadata":{"roleHeading":"Type Property","externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(cpy)default","role":"symbol","symbolKind":"property","modules":[{"name":"DevRevSDK"}],"title":"default","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"kind":"text","text":": "},{"text":"FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/default"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration"}]}]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The default configuration with enabled frame capture and auto start recording."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/default":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/default","type":"topic","abstract":[{"text":"The default configuration with enabled frame capture and auto start recording.","type":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration\/default","title":"default"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"abstract":[{"text":"A feature configuration class used to customize SDK behavior.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","role":"symbol","kind":"symbol","title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"FeatureConfiguration","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"op":"replace","value":[{"kind":"identifier","text":"FeatureConfiguration"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle"}]}]}