{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableSupportChatStreaming","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DevRevSDK"}],"title":"enableSupportChatStreaming","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"enableSupportChatStreaming","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(py)enableSupportChatStreaming","role":"symbol","navigatorTitle":[{"text":"enableSupportChatStreaming","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"enableSupportChatStreaming","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/enablesupportchatstreaming"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/enablesupportchatstreaming"]}],"abstract":[{"type":"text","text":"Enables real-time AI agent response streaming in PLuG conversations."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/enableSupportChatStreaming":{"title":"enableSupportChatStreaming","kind":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration\/enablesupportchatstreaming","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableSupportChatStreaming"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Enables real-time AI agent response streaming in PLuG conversations."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableSupportChatStreaming","role":"symbol","navigatorTitle":[{"text":"enableSupportChatStreaming","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"enableSupportChatStreaming"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enableSupportChatStreaming"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"enableSupportChatStreaming","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableSupportChatStreaming\/title","value":"enableSupportChatStreaming"},{"value":[{"kind":"identifier","text":"enableSupportChatStreaming"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableSupportChatStreaming\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","value":"FeatureConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"text":"FeatureConfiguration","kind":"identifier"}]}]}]}