{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"metadata":{"title":"enableFrameCapture","symbolKind":"property","role":"symbol","modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"text":"enableFrameCapture","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(py)enableFrameCapture","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableFrameCapture","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableFrameCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableFrameCapture","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/enableframecapture"]},{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/enableframecapture"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Enables or disables frame capture for session replay."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"role":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/enableFrameCapture":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableFrameCapture"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"enableFrameCapture","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableFrameCapture","navigatorTitle":[{"text":"enableFrameCapture","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/enableframecapture","type":"topic","abstract":[{"text":"Enables or disables frame capture for session replay.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","abstract":[],"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"enableFrameCapture"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"enableFrameCapture"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"enableFrameCapture","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"FeatureConfiguration","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"value":[{"text":"FeatureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle"},{"value":"enableFrameCapture","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableFrameCapture\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableFrameCapture\/fragments","value":[{"text":"enableFrameCapture","kind":"identifier"}],"op":"replace"}]}]}