{"abstract":[{"type":"text","text":"Creates configuration that allows you use set only custom support widget themes."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DevRevSDK"}],"title":"init(witCustomSupportWidgetTheme:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"witCustomSupportWidgetTheme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"initWithWitCustomSupportWidgetTheme:","kind":"identifier"}],"symbolKind":"init","externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(im)initWithWitCustomSupportWidgetTheme:"},"sections":[],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(witCustomSupportWidgetTheme:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"witCustomSupportWidgetTheme"},{"text":" ","kind":"text"},{"text":"theme","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"theme: A custom theme."}]}]}]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(witcustomsupportwidgettheme:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(witcustomsupportwidgettheme:)"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","type":"topic","url":"\/documentation\/devrevsdk\/featureconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"title":"FeatureConfiguration","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(witCustomSupportWidgetTheme:)":{"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(witCustomSupportWidgetTheme:)","type":"topic","abstract":[{"type":"text","text":"Creates configuration that allows you use set only custom support widget themes."}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(witcustomsupportwidgettheme:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"witCustomSupportWidgetTheme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme"},{"kind":"text","text":")"}],"title":"init(witCustomSupportWidgetTheme:)","role":"symbol","navigatorTitle":[{"text":"initWithWitCustomSupportWidgetTheme:","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportWidgetTheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"title":"SupportWidgetTheme","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithWitCustomSupportWidgetTheme:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWitCustomSupportWidgetTheme:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithWitCustomSupportWidgetTheme:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SupportWidgetTheme","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"kind":"text","text":" *) "},{"text":"theme","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","value":"FeatureConfiguration"},{"value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(witCustomSupportWidgetTheme:)\/title","value":"initWithWitCustomSupportWidgetTheme:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithWitCustomSupportWidgetTheme:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(witCustomSupportWidgetTheme:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","value":"SupportWidgetTheme","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]}]}]}