{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(withShouldEnableFrameCapture:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(withshouldenableframecapture:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(withshouldenableframecapture:)"]}],"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(withShouldEnableFrameCapture:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"withShouldEnableFrameCapture","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithShouldEnableFrameCapture:"}],"externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(im)initWithShouldEnableFrameCapture:","modules":[{"name":"DevRevSDK"}]},"abstract":[{"text":"Creates a configuration that toggles frame capture while preserving the current runtime settings.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"withShouldEnableFrameCapture","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shouldEnableFrameCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"shouldEnableFrameCapture: A flag that enables or disables frame capture.","type":"text"}]}]}],"type":"unorderedList"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"The remaining properties reuse the values from the currently active feature configuration."}],"type":"paragraph"}],"name":"Note","type":"aside"}],"kind":"content"}],"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","abstract":[],"title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(withShouldEnableFrameCapture:)":{"abstract":[{"text":"Creates a configuration that toggles frame capture while preserving the current runtime settings.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShouldEnableFrameCapture"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(withShouldEnableFrameCapture:)","title":"init(withShouldEnableFrameCapture:)","navigatorTitle":[{"text":"initWithShouldEnableFrameCapture:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration\/init(withshouldenableframecapture:)","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"symbol","title":"FeatureConfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithShouldEnableFrameCapture:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithShouldEnableFrameCapture:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithShouldEnableFrameCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"shouldEnableFrameCapture"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"initWithShouldEnableFrameCapture:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(withShouldEnableFrameCapture:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithShouldEnableFrameCapture:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(withShouldEnableFrameCapture:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","op":"replace","value":"FeatureConfiguration"},{"op":"replace","value":[{"text":"FeatureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"text":"FeatureConfiguration","kind":"identifier"}]}]}]}