{"variants":[{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:enablesupportchatstreaming:supportwidgetarticlesearchfilters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:enablesupportchatstreaming:supportwidgetarticlesearchfilters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Creates an SDK configuration.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(im)initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","title":"init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","role":"symbol","modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoStartRecording","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"alwaysUseRemoteConfig"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"supportWidgetTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"text":", ","kind":"text"},{"text":"enableSupportChatStreaming","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"supportWidgetArticleSearchFilters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ArticleSearchFilters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters"},{"text":"?)","kind":"text"}],"symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enableFrameCapture"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"text":"autoStartRecording","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"alwaysUseRemoteConfig"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"supportWidgetTheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"},{"text":" = .systemDefault, ","kind":"text"},{"kind":"externalParam","text":"enableSupportChatStreaming"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"supportWidgetArticleSearchFilters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","text":"ArticleSearchFilters","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"enableFrameCapture","content":[{"type":"paragraph","inlineContent":[{"text":"A flag enables or disables frame capture.","type":"text"}]}]},{"name":"autoStartRecording","content":[{"inlineContent":[{"type":"text","text":"A flag automatically starts recording."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag specifies to use a remote config always."}]}],"name":"alwaysUseRemoteConfig"},{"name":"supportWidgetTheme","content":[{"inlineContent":[{"type":"text","text":"A support widget theme."}],"type":"paragraph"}]},{"name":"enableSupportChatStreaming","content":[{"type":"paragraph","inlineContent":[{"text":"Enables real-time AI agent response streaming in PLuG conversations.","type":"text"}]}]},{"name":"supportWidgetArticleSearchFilters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional filters for PLuG article search; applied when the support widget is ready."}]}]}]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","abstract":[{"type":"text","text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search)."}],"url":"\/documentation\/devrevsdk\/articlesearchfilters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilters"}],"title":"ArticleSearchFilters","kind":"symbol","navigatorTitle":[{"text":"ArticleSearchFilters","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SupportWidgetTheme"}],"abstract":[{"text":"A theme class used to customize the support widget appearance.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","type":"topic","role":"symbol","title":"SupportWidgetTheme","url":"\/documentation\/devrevsdk\/supportwidgettheme","navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)":{"abstract":[{"type":"text","text":"Creates an SDK configuration."}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:enablesupportchatstreaming:supportwidgetarticlesearchfilters:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoStartRecording","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alwaysUseRemoteConfig"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"supportWidgetTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"text":", ","kind":"text"},{"text":"enableSupportChatStreaming","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"supportWidgetArticleSearchFilters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters"},{"text":"?)","kind":"text"}],"title":"init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","navigatorTitle":[{"text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEnableFrameCapture:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"enableFrameCapture"},{"kind":"text","text":" "},{"text":"autoStartRecording:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoStartRecording"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysUseRemoteConfig:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"alwaysUseRemoteConfig","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"supportWidgetTheme:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"supportWidgetTheme"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableSupportChatStreaming:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"enableSupportChatStreaming","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportWidgetArticleSearchFilters:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters","text":"ArticleSearchFilters","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"supportWidgetArticleSearchFilters"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A flag enables or disables frame capture.","type":"text"}],"type":"paragraph"}],"name":"enableFrameCapture"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag automatically starts recording."}]}],"name":"autoStartRecording"},{"name":"alwaysUseRemoteConfig","content":[{"type":"paragraph","inlineContent":[{"text":"A flag specifies to use a remote config always.","type":"text"}]}]},{"name":"supportWidgetTheme","content":[{"inlineContent":[{"text":"A support widget theme.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enables real-time AI agent response streaming in PLuG conversations."}]}],"name":"enableSupportChatStreaming"},{"content":[{"inlineContent":[{"type":"text","text":"Optional filters for PLuG article search; applied when the support widget is ready."}],"type":"paragraph"}],"name":"supportWidgetArticleSearchFilters"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"FeatureConfiguration","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","op":"replace","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/title","value":"ArticleSearchFilters"},{"value":[{"kind":"identifier","text":"ArticleSearchFilters"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/navigatorTitle","value":[{"text":"ArticleSearchFilters","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SupportWidgetTheme","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"op":"replace","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle"},{"value":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}