{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoStartRecording"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"alwaysUseRemoteConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"supportWidgetTheme","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A flag enables or disables frame capture.","type":"text"}]}],"name":"enableFrameCapture"},{"name":"autoStartRecording","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag automatically starts recording."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A flag specifies to use a remote config always.","type":"text"}]}],"name":"alwaysUseRemoteConfig"},{"name":"supportWidgetTheme","content":[{"type":"paragraph","inlineContent":[{"text":"A support widget theme.","type":"text"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)"},"abstract":[{"text":"Creates an SDK configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:)"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"autoStartRecording","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alwaysUseRemoteConfig"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportWidgetTheme"},{"kind":"text","text":": "},{"text":"SupportWidgetTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)","navigatorTitle":[{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:"}],"modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(im)initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:","role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","type":"topic","url":"\/documentation\/devrevsdk\/featureconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"title":"FeatureConfiguration","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)":{"title":"init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)","navigatorTitle":[{"text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates an SDK configuration."}],"role":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:)","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoStartRecording"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"alwaysUseRemoteConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"supportWidgetTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportWidgetTheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"title":"SupportWidgetTheme","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"text":") ","kind":"text"},{"text":"initWithEnableFrameCapture:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"enableFrameCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoStartRecording:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"autoStartRecording","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"alwaysUseRemoteConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"alwaysUseRemoteConfig"},{"text":" ","kind":"text"},{"text":"supportWidgetTheme:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"},{"text":" *) ","kind":"text"},{"text":"supportWidgetTheme","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"enableFrameCapture","content":[{"inlineContent":[{"type":"text","text":"A flag enables or disables frame capture."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A flag automatically starts recording.","type":"text"}],"type":"paragraph"}],"name":"autoStartRecording"},{"name":"alwaysUseRemoteConfig","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag specifies to use a remote config always."}]}]},{"name":"supportWidgetTheme","content":[{"inlineContent":[{"text":"A support widget theme.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","op":"replace","value":"FeatureConfiguration"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:"}]},{"op":"replace","value":"SupportWidgetTheme","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","op":"replace","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","value":[{"kind":"identifier","text":"SupportWidgetTheme"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}