{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:supportwidgettheme:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:supportwidgettheme:)"]}],"metadata":{"title":"init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)","symbolKind":"init","externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(im)initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:","roleHeading":"Initializer","modules":[{"name":"DevRevSDK"}],"role":"symbol","navigatorTitle":[{"text":"initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enableFrameCapture"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"autoStartRecording","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportWidgetTheme"},{"kind":"text","text":": "},{"text":"SupportWidgetTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"autoStartRecording","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"supportWidgetTheme"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"enableFrameCapture","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag enables or disables frame capture."}]}]},{"content":[{"inlineContent":[{"text":"A flag automatically starts recording.","type":"text"}],"type":"paragraph"}],"name":"autoStartRecording"},{"name":"supportWidgetTheme","content":[{"inlineContent":[{"text":"A support widget theme.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Creates an SDK configuration."}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"enableFrameCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoStartRecording"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"supportWidgetTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)","abstract":[{"type":"text","text":"Creates an SDK configuration."}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:supportwidgettheme:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:"}],"role":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"role":"collection","type":"topic","title":"DevRevSDK","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"type":"topic","title":"FeatureConfiguration","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration","role":"symbol","navigatorTitle":[{"text":"FeatureConfiguration","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SupportWidgetTheme","kind":"identifier"}],"title":"SupportWidgetTheme","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"url":"\/documentation\/devrevsdk\/supportwidgettheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithEnableFrameCapture:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"enableFrameCapture","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoStartRecording:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"autoStartRecording","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportWidgetTheme:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","kind":"typeIdentifier","text":"SupportWidgetTheme"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"supportWidgetTheme"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"A flag enables or disables frame capture.","type":"text"}],"type":"paragraph"}],"name":"enableFrameCapture"},{"content":[{"inlineContent":[{"type":"text","text":"A flag automatically starts recording."}],"type":"paragraph"}],"name":"autoStartRecording"},{"content":[{"inlineContent":[{"type":"text","text":"A support widget theme."}],"type":"paragraph"}],"name":"supportWidgetTheme"}],"kind":"parameters"}},{"op":"replace","value":"initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnableFrameCapture:autoStartRecording:supportWidgetTheme:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:supportWidgetTheme:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","value":"FeatureConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"value":"SupportWidgetTheme","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"op":"replace","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}