{"abstract":[{"type":"text","text":"Inherited from "},{"code":"Decodable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(from:)"},"metadata":{"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","title":"init(from:)","modules":[{"name":"DevRevSDK"}],"role":"symbol","externalID":"s:9DevRevSDK20FeatureConfigurationC4fromACs7Decoder_p_tKcfc"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"symbol","title":"FeatureConfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","abstract":[],"title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(from:)":{"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(from:)","abstract":[],"role":"symbol","title":"init(from:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"FeatureConfiguration","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}