{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"abstract":[{"text":"Optional filters for PLuG article search (widget and CMDK). Applied when the support widget is ready. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for no filter."}],"metadata":{"title":"supportWidgetArticleSearchFilters","navigatorTitle":[{"kind":"identifier","text":"supportWidgetArticleSearchFilters"}],"externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(py)supportWidgetArticleSearchFilters","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportWidgetArticleSearchFilters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters","text":"ArticleSearchFilters"},{"text":"?","kind":"text"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/supportwidgetarticlesearchfilters"]},{"paths":["\/documentation\/devrevsdk\/featureconfiguration\/supportwidgetarticlesearchfilters"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"supportWidgetArticleSearchFilters","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters","text":"ArticleSearchFilters","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetArticleSearchFilters","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"title":"FeatureConfiguration","type":"topic","abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureConfiguration"}],"url":"\/documentation\/devrevsdk\/featureconfiguration","navigatorTitle":[{"text":"FeatureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters":{"url":"\/documentation\/devrevsdk\/articlesearchfilters","kind":"symbol","role":"symbol","abstract":[{"text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search).","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilters"}],"type":"topic","title":"ArticleSearchFilters","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilters"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/supportWidgetArticleSearchFilters":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetArticleSearchFilters","title":"supportWidgetArticleSearchFilters","abstract":[{"text":"Optional filters for PLuG article search (widget and CMDK). Applied when the support widget is ready. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for no filter.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportWidgetArticleSearchFilters","kind":"identifier"},{"kind":"text","text":": "},{"text":"ArticleSearchFilters","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"supportWidgetArticleSearchFilters","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/supportwidgetarticlesearchfilters","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"supportWidgetArticleSearchFilters","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"supportWidgetArticleSearchFilters","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters","text":"ArticleSearchFilters","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"supportWidgetArticleSearchFilters"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"FeatureConfiguration","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"value":[{"text":"FeatureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/title","value":"ArticleSearchFilters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/fragments","value":[{"text":"ArticleSearchFilters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/navigatorTitle","op":"replace","value":[{"text":"ArticleSearchFilters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetArticleSearchFilters\/title","value":"supportWidgetArticleSearchFilters"},{"value":[{"text":"supportWidgetArticleSearchFilters","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetArticleSearchFilters\/fragments","op":"replace"}]}]}