{"abstract":[{"text":"The theme for the widget (system “light” or “dark” or custom).","type":"text"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportWidgetTheme"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetTheme"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration(py)supportWidgetTheme","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportWidgetTheme","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"}],"title":"supportWidgetTheme","navigatorTitle":[{"text":"supportWidgetTheme","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DevRevSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/supportwidgettheme"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/featureconfiguration\/supportwidgettheme"]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","abstract":[],"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/supportWidgetTheme":{"navigatorTitle":[{"text":"supportWidgetTheme","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The theme for the widget (system “light” or “dark” or custom).","type":"text"}],"kind":"symbol","title":"supportWidgetTheme","url":"\/documentation\/devrevsdk\/featureconfiguration\/supportwidgettheme","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetTheme","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportWidgetTheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme","kind":"typeIdentifier"}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme","title":"SupportWidgetTheme","kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SupportWidgetTheme"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"role":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"supportWidgetTheme"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"supportWidgetTheme","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"kind":"text","text":" * "},{"text":"supportWidgetTheme","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"supportWidgetTheme","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetTheme\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"supportWidgetTheme"}]},{"value":"SupportWidgetTheme","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title"},{"value":[{"kind":"identifier","text":"SupportWidgetTheme"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SupportWidgetTheme"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","op":"replace"},{"value":"FeatureConfiguration","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"kind":"identifier","text":"FeatureConfiguration"}],"op":"replace"},{"value":[{"kind":"identifier","text":"FeatureConfiguration"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","op":"replace"}]}]}