{"metadata":{"modules":[{"name":"DevRevSDK"}],"title":"addSessionProperties(_:)","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)addSessionProperties:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSessionProperties","kind":"identifier"},{"text":"([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"addSessionProperties:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSessionProperties","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"properties"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary of custom session properties.","type":"text"}]}],"name":"properties"}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any new properties in the dictionary will be added to the session properties. If a property already exists, the"},{"type":"text","text":" "},{"text":"new value takes precedence and will override the existing value.","type":"text"}]},{"type":"aside","name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any date that would be a part of the properties dictionary "},{"inlineContent":[{"text":"should","type":"text"}],"type":"strong"},{"text":" be sent in the ","type":"text"},{"type":"codeVoice","code":"YYYY\/MM\/DD"},{"text":" ","type":"text"},{"text":"format.","type":"text"}]}]},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"text":"In cases when you want to clear out the stored session properties, you can call the","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","isActive":true},{"text":" method.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/addsessionproperties(_:)"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/addsessionproperties(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Adds properties to the session. The properties will be sent along any analytic events.","type":"text"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/addSessionProperties(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevInterop"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","type":"topic","title":"DevRevInterop","abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","abstract":[],"kind":"symbol","title":"DevRevSDK","type":"topic","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/clearSessionProperties()":{"type":"topic","title":"clearSessionProperties()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","abstract":[{"type":"text","text":"Clears the session properties."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearSessionProperties"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSessionProperties"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/clearsessionproperties()"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/addSessionProperties(_:)":{"url":"\/documentation\/devrevsdk\/devrevinterop\/addsessionproperties(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addSessionProperties"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"addSessionProperties:","kind":"identifier"}],"title":"addSessionProperties(_:)","type":"topic","abstract":[{"text":"Adds properties to the session. The properties will be sent along any analytic events.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/addSessionProperties(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"addSessionProperties:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addSessionProperties:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"addSessionProperties:"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"properties","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"properties","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary of custom session properties."}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace","value":"DevRev"},{"value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}]},{"value":"clearSessionProperties","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1clearSessionProperties()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1clearSessionProperties()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearSessionProperties","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1addSessionProperties(_:)\/title","op":"replace","value":"addSessionProperties:"},{"value":[{"kind":"text","text":"+ "},{"text":"addSessionProperties:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1addSessionProperties(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}