{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/captureError(_:tag:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(captureError:tag:) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureError","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"error","content":[{"inlineContent":[{"text":"The error object to capture (NSError in Objective-C).","type":"text"}],"type":"paragraph"}]},{"name":"tag","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A tag to categorize the error (e.g., “NetworkError”, “ValidationError”)."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"This method captures errors that are caught and handled in your app, logging them for analysis.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Only the first N errors per session will be logged (based on platform settings) to prevent excessive file writes."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/captureerror(_:tag:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/captureerror(_:tag:)"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Captures a handled error and logs it to a file."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"captureError:tag:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureError"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"DevRevSDK"}],"title":"captureError(_:tag:)","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)captureError:tag:","symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/captureError(_:tag:)":{"role":"symbol","abstract":[{"type":"text","text":"Captures a handled error and logs it to a file."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/captureError(_:tag:)","title":"captureError(_:tag:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"captureError:tag:","kind":"identifier"}],"type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop\/captureerror(_:tag:)","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrevinterop","title":"DevRevInterop","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","abstract":[],"title":"DevRevSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"captureError:tag:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"captureError:tag:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"captureError:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tag"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The error object to capture (NSError in Objective-C).","type":"text"}]}],"name":"error"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A tag to categorize the error (e.g., “NetworkError”, “ValidationError”).","type":"text"}]}],"name":"tag"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1captureError(_:tag:)\/title","value":"captureError:tag:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1captureError(_:tag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"captureError:tag:"}]},{"value":"DevRev","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]}]}]}