{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/clearsessionproperties()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/clearsessionproperties()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","modules":[{"name":"DevRevSDK"}],"role":"symbol","title":"clearSessionProperties()","navigatorTitle":[{"text":"clearSessionProperties","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)clearSessionProperties","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearSessionProperties","kind":"identifier"},{"kind":"text","text":"()"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSessionProperties"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Clears the session properties."}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/clearSessionProperties()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/clearsessionproperties()","navigatorTitle":[{"text":"clearSessionProperties","kind":"identifier"}],"title":"clearSessionProperties()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearSessionProperties","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","abstract":[{"type":"text","text":"Clears the session properties."}],"kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"kind":"symbol","title":"DevRevInterop","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","type":"topic","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"clearSessionProperties"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"clearSessionProperties","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"clearSessionProperties","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"clearSessionProperties","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1clearSessionProperties()\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1clearSessionProperties()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearSessionProperties","kind":"identifier"}],"op":"replace"},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}]}]}]}