{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(configureWithAppID:featureConfiguration:) "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"appID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"featureConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"appID","content":[{"type":"paragraph","inlineContent":[{"text":"An identifier unique to your app.","type":"text"}]}]},{"name":"featureConfiguration","content":[{"inlineContent":[{"type":"text","text":"A feature configuration to customize SDK behavior."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This overload allows customizing SDK behavior during setup.","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"configureWithAppID:featureConfiguration:","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)configureWithAppID:featureConfiguration:","title":"configure(appID:featureConfiguration:)","symbolKind":"method","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"featureConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration"},{"text":")","kind":"text"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:featureConfiguration:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configures the SDK with the app ID and a feature configuration."}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/configure(appid:featureconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/configure(appid:featureconfiguration:)"]}],"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"abstract":[{"text":"A feature configuration class used to customize SDK behavior.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","role":"symbol","kind":"symbol","title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/configure(appID:featureConfiguration:)":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:featureConfiguration:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration"},{"text":")","kind":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/configure(appid:featureconfiguration:)","title":"configure(appID:featureConfiguration:)","kind":"symbol","abstract":[{"type":"text","text":"Configures the SDK with the app ID and a feature configuration."}],"type":"topic","navigatorTitle":[{"text":"configureWithAppID:featureConfiguration:","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"title":"DevRevInterop","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"configureWithAppID:featureConfiguration:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWithAppID:featureConfiguration:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureWithAppID:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"appID","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureConfiguration:"},{"text":"(","kind":"text"},{"text":"FeatureConfiguration","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration"},{"kind":"text","text":" *) "},{"text":"featureConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An identifier unique to your app.","type":"text"}]}],"name":"appID"},{"name":"featureConfiguration","content":[{"inlineContent":[{"text":"A feature configuration to customize SDK behavior.","type":"text"}],"type":"paragraph"}]}]}},{"value":"FeatureConfiguration","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FeatureConfiguration"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"FeatureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:featureConfiguration:)\/title","value":"configureWithAppID:featureConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:featureConfiguration:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"configureWithAppID:featureConfiguration:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}