{"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)consentOptIn","navigatorTitle":[{"kind":"identifier","text":"consentOptIn"}],"title":"consentOptIn()","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"consentOptIn"},{"text":"()","kind":"text"}],"role":"symbol","modules":[{"name":"DevRevSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/consentOptIn()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(consentOptIn) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"consentOptIn","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Records that the end-user "},{"type":"strong","inlineContent":[{"text":"gave","type":"text"}]},{"type":"text","text":" permission (opted-in) for user recording."}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/consentoptin()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/consentoptin()"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/consentOptIn()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/consentoptin()","abstract":[{"text":"Records that the end-user ","type":"text"},{"type":"strong","inlineContent":[{"text":"gave","type":"text"}]},{"type":"text","text":" permission (opted-in) for user recording."}],"navigatorTitle":[{"text":"consentOptIn","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/consentOptIn()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentOptIn"},{"text":"()","kind":"text"}],"kind":"symbol","title":"consentOptIn()","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","title":"DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"consentOptIn","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"consentOptIn","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"consentOptIn","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"consentOptIn","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1consentOptIn()\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"consentOptIn"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1consentOptIn()\/fragments"},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}],"op":"replace"}]}]}