{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"endTimerWithName:properties:"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)endTimerWithName:properties:","title":"endTimer(_:properties:)","role":"symbol","roleHeading":"Type Method","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"endTimer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/endTimer(_:properties:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(endTimerWithName:properties:) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endTimer"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A timer name. The timer name can have up to 250 characters."}]}],"name":"name"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A property dictionary.","type":"text"}]}],"name":"properties"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"This method will calculate the complete time from the start of the event. The method acts as a balanced call to","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startTimer(_:properties:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"sections":[],"abstract":[{"text":"Ends a previously started timer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/endtimer(_:properties:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/endtimer(_:properties:)"]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/endTimer(_:properties:)":{"abstract":[{"type":"text","text":"Ends a previously started timer."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"endTimer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"title":"endTimer(_:properties:)","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/endtimer(_:properties:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"endTimerWithName:properties:"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/endTimer(_:properties:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","title":"DevRevInterop"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/startTimer(_:properties:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startTimerWithName:properties:"}],"kind":"symbol","title":"startTimer(_:properties:)","url":"\/documentation\/devrevsdk\/devrevinterop\/starttimer(_:properties:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startTimer(_:properties:)","type":"topic","abstract":[{"type":"text","text":"Starts a timer at any point in the app in order to measure time metrics for events such as load or response time."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"endTimerWithName:properties:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"endTimerWithName:properties:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"endTimerWithName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"text":" ","kind":"text"},{"text":"properties:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"properties","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"name","content":[{"inlineContent":[{"text":"A timer name. The timer name can have up to 250 characters.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A property dictionary.","type":"text"}],"type":"paragraph"}],"name":"properties"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1endTimer(_:properties:)\/title","value":"endTimerWithName:properties:"},{"value":[{"text":"+ ","kind":"text"},{"text":"endTimerWithName:properties:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1endTimer(_:properties:)\/fragments"},{"value":"DevRev","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}]},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace"},{"op":"replace","value":"startTimerWithName:properties:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startTimer(_:properties:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startTimer(_:properties:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startTimerWithName:properties:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}