{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposeSensitiveViews"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"exposeSensitiveViews:","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)exposeSensitiveViews:","symbolKind":"method","title":"exposeSensitiveViews(_:)","modules":[{"name":"DevRevSDK"}],"roleHeading":"Type Method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(exposeSensitiveViews:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exposeSensitiveViews","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sensitiveViews"},{"kind":"text","text":": "},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of views you want to expose."}]}],"name":"sensitiveViews"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/exposesensitiveviews(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/exposesensitiveviews(_:)"]}],"abstract":[{"text":"Disable the auto masking feature for the passed auto masked views.","type":"text"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/exposeSensitiveViews(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","title":"DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/exposeSensitiveViews(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/exposeSensitiveViews(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exposeSensitiveViews","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Disable the auto masking feature for the passed auto masked views."}],"navigatorTitle":[{"kind":"identifier","text":"exposeSensitiveViews:"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/exposesensitiveviews(_:)","title":"exposeSensitiveViews(_:)","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"exposeSensitiveViews:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"exposeSensitiveViews:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"exposeSensitiveViews:"},{"kind":"text","text":"("},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"sensitiveViews","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"value":"exposeSensitiveViews:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1exposeSensitiveViews(_:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1exposeSensitiveViews(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"exposeSensitiveViews:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}