{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(identifyVerifiedUser:sesionToken:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifyVerifiedUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"userID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string used to identify the user (can be an email)."}]}]},{"name":"sessionToken","content":[{"inlineContent":[{"text":"A session token generated by your backend.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"The verification process is done between your and DevRev’s backend.","type":"text"},{"text":" ","type":"text"},{"text":"The identification method should be called when you receive a callback or you have your user’s data ready.","type":"text"}]},{"type":"aside","content":[{"inlineContent":[{"text":"Make sure that you have called the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)"},{"text":" method before.","type":"text"}],"type":"paragraph"}],"name":"Important","style":"important"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/identifyverifieduser(_:sessiontoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/identifyverifieduser(_:sessiontoken:)"]}],"abstract":[{"text":"Identifies a verified user after the SDK has been configured.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)identifyVerifiedUser:sesionToken:","navigatorTitle":[{"text":"identifyVerifiedUser:sesionToken:","kind":"identifier"}],"modules":[{"name":"DevRevSDK"}],"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifyVerifiedUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"identifyVerifiedUser(_:sessionToken:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyVerifiedUser(_:sessionToken:)"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"type":"topic","role":"collection","title":"DevRevSDK","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/configure(appID:)":{"abstract":[{"text":"Configures the SDK with the app ID.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"configure(appID:)","navigatorTitle":[{"kind":"identifier","text":"configureWithAppID:"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/configure(appid:)","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/identifyVerifiedUser(_:sessionToken:)":{"title":"identifyVerifiedUser(_:sessionToken:)","type":"topic","navigatorTitle":[{"text":"identifyVerifiedUser:sesionToken:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyVerifiedUser(_:sessionToken:)","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/identifyverifieduser(_:sessiontoken:)","abstract":[{"text":"Identifies a verified user after the SDK has been configured.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifyVerifiedUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"identifyVerifiedUser:sesionToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"identifyVerifiedUser:sesionToken:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"identifyVerifiedUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userID"},{"kind":"text","text":" "},{"kind":"identifier","text":"sesionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"userID","content":[{"inlineContent":[{"text":"A string used to identify the user (can be an email).","type":"text"}],"type":"paragraph"}]},{"name":"sessionToken","content":[{"type":"paragraph","inlineContent":[{"text":"A session token generated by your backend.","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/title","op":"replace","value":"configureWithAppID:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWithAppID:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyVerifiedUser(_:sessionToken:)\/title","op":"replace","value":"identifyVerifiedUser:sesionToken:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyVerifiedUser(_:sessionToken:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"identifyVerifiedUser:sesionToken:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace","value":"DevRev"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace","value":[{"kind":"identifier","text":"DevRev"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]}]}]}