{"abstract":[{"text":"Identifies an unverified user after the SDK has been configured.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(identifyUnverifiedUserWithIdentity:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"identifyUnverifiedUser","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"identity","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","text":"Identity","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"An identity object.","type":"text"}],"type":"paragraph"}],"name":"identity"}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"The identification method should be called when you receive a callback or you have your user’s data ready.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/identifyunverifieduser(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/identifyunverifieduser(_:)"]}],"kind":"symbol","metadata":{"roleHeading":"Type Method","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifyUnverifiedUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Identity","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)identifyUnverifiedUserWithIdentity:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifyUnverifiedUserWithIdentity:"}],"title":"identifyUnverifiedUser(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyUnverifiedUser(_:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"type":"topic","title":"userID","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"userID"}],"url":"\/documentation\/devrevsdk\/identity\/userid","kind":"symbol","abstract":[{"text":"A user identifier.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"type":"topic","title":"Identity","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity","kind":"symbol","abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"text":" ","type":"text"},{"text":"The information can be either on the level of organizations or your user.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The minimum information needed is the "},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevInterop"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","type":"topic","title":"DevRevInterop","abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","abstract":[],"kind":"symbol","title":"DevRevSDK","type":"topic","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/identifyUnverifiedUser(_:)":{"abstract":[{"type":"text","text":"Identifies an unverified user after the SDK has been configured."}],"navigatorTitle":[{"text":"identifyUnverifiedUserWithIdentity:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/identifyunverifieduser(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifyUnverifiedUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Identity","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity"},{"text":")","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyUnverifiedUser(_:)","title":"identifyUnverifiedUser(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"identifyUnverifiedUserWithIdentity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"identifyUnverifiedUserWithIdentity:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"identifyUnverifiedUserWithIdentity:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","text":"Identity","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"},{"text":" *) ","kind":"text"},{"text":"identity","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"identity","content":[{"inlineContent":[{"text":"An identity object.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"userID","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}],"op":"replace"},{"value":"Identity","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","op":"replace","value":[{"text":"Identity","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"Identity"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace","value":"DevRev"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}]},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace"},{"value":"identifyUnverifiedUserWithIdentity:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyUnverifiedUser(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyUnverifiedUser(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"identifyUnverifiedUserWithIdentity:"}]}]}]}