{"abstract":[{"text":"Logs out the current identified user and resets the session.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The process will also unregister the user’s device from receiving push notifications, and stop any ongoing"},{"type":"text","text":" "},{"text":"session recording.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(logoutWithDeviceID:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"deviceID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"text":"unique","type":"text"}]},{"text":" to your system, or the app vendor","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"identifier i.e. IDFV ("},{"type":"codeVoice","code":"UIDevice.identifierForVendor"},{"text":").","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"After calling this method, you will need to re-identify the user.","type":"text"}]}],"type":"aside","style":"important"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/logout(deviceid:)"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/logout(deviceid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)logoutWithDeviceID:","navigatorTitle":[{"kind":"identifier","text":"logoutWithDeviceID:"}],"modules":[{"name":"DevRevSDK"}],"title":"logout(deviceID:)"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/logout(deviceID:)"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/logout(deviceID:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/logout(deviceID:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"kind":"text","text":"("},{"text":"deviceID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logoutWithDeviceID:"}],"abstract":[{"type":"text","text":"Logs out the current identified user and resets the session."},{"text":" ","type":"text"},{"type":"text","text":"The process will also unregister the user’s device from receiving push notifications, and stop any ongoing"},{"type":"text","text":" "},{"text":"session recording.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/logout(deviceid:)","kind":"symbol","type":"topic","title":"logout(deviceID:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","title":"DevRevInterop"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"logoutWithDeviceID:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"logoutWithDeviceID:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"logoutWithDeviceID:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"deviceID","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"deviceID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"text":"unique","type":"text"}]},{"type":"text","text":" to your system, or the app vendor"},{"type":"text","text":" "},{"text":"identifier i.e. IDFV (","type":"text"},{"type":"codeVoice","code":"UIDevice.identifierForVendor"},{"text":").","type":"text"}]}]}]}},{"value":"logoutWithDeviceID:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1logout(deviceID:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1logout(deviceID:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"logoutWithDeviceID:","kind":"identifier"}]},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}]}]}