{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/marksensitiveviews(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/marksensitiveviews(_:)"]}],"abstract":[{"type":"text","text":"Mark the passed views as sensitive."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markSensitiveViews"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"sensitiveViews","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":"])","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sensitiveViews","content":[{"inlineContent":[{"type":"text","text":"An array of views that should be masked."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The views will be shown as masked in the portal playbacks.","type":"text"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/markSensitiveViews(_:)","interfaceLanguage":"swift"},"metadata":{"title":"markSensitiveViews(_:)","modules":[{"name":"DevRevSDK"}],"role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)markSensitiveViews:","symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"markSensitiveViews","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"markSensitiveViews:"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/markSensitiveViews(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markSensitiveViews"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"markSensitiveViews(_:)","navigatorTitle":[{"text":"markSensitiveViews:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/markSensitiveViews(_:)","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/marksensitiveviews(_:)","abstract":[{"text":"Mark the passed views as sensitive.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"kind":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","title":"DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","role":"symbol","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"type":"topic","title":"DevRevSDK","abstract":[],"kind":"symbol","url":"\/documentation\/devrevsdk","role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"markSensitiveViews:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"markSensitiveViews:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"markSensitiveViews:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<UIView *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"sensitiveViews","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of views that should be masked."}]}],"name":"sensitiveViews"}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1markSensitiveViews(_:)\/title","op":"replace","value":"markSensitiveViews:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"markSensitiveViews:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1markSensitiveViews(_:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace","value":"DevRev"},{"op":"replace","value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}