{"abstract":[{"type":"text","text":"Pauses user interaction tracking."}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/pauseuserinteractiontracking()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/pauseuserinteractiontracking()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pauseUserInteractionTracking","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Type Method","modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"kind":"identifier","text":"pauseUserInteractionTracking"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pauseUserInteractionTracking","kind":"identifier"},{"kind":"text","text":"()"}],"title":"pauseUserInteractionTracking()","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)pauseUserInteractionTracking"},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseUserInteractionTracking()","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"title":"DevRevInterop","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/pauseUserInteractionTracking()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/pauseuserinteractiontracking()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pauseUserInteractionTracking","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseUserInteractionTracking()","abstract":[{"type":"text","text":"Pauses user interaction tracking."}],"role":"symbol","title":"pauseUserInteractionTracking()","navigatorTitle":[{"kind":"identifier","text":"pauseUserInteractionTracking"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"pauseUserInteractionTracking"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"pauseUserInteractionTracking"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"pauseUserInteractionTracking","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1pauseUserInteractionTracking()\/title","value":"pauseUserInteractionTracking","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"pauseUserInteractionTracking","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1pauseUserInteractionTracking()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}