{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseRecording"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"text":"pauseRecording","kind":"identifier"}],"symbolKind":"method","title":"pauseRecording()","modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)pauseRecording","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/pauserecording()"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/pauserecording()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Pauses the ongoing user recording session."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pauseRecording","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseRecording()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/pauseRecording()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/pauserecording()","title":"pauseRecording()","abstract":[{"type":"text","text":"Pauses the ongoing user recording session."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseRecording()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseRecording","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pauseRecording","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"url":"\/documentation\/devrevsdk\/devrevinterop","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol","title":"DevRevInterop","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"role":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","url":"\/documentation\/devrevsdk","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"pauseRecording","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"pauseRecording","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"pauseRecording"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1pauseRecording()\/title","value":"pauseRecording"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"pauseRecording"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1pauseRecording()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev"},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"kind":"identifier","text":"DevRev"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}