{"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/preferssystemtheme"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/preferssystemtheme"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"metadata":{"platforms":[{"unavailable":false,"message":"Configure prefersSystemTheme via FeatureConfiguration passed to DevRev.configure or DevRev.updateFeatureConfiguration(_:).","deprecated":true,"beta":false}],"navigatorTitle":[{"text":"prefersSystemTheme","kind":"identifier"}],"symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cpy)prefersSystemTheme","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefersSystemTheme","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"prefersSystemTheme"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefersSystemTheme","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/prefersSystemTheme","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"A flag to use the default theme for the support feature.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"Configure prefersSystemTheme via FeatureConfiguration passed to DevRev.configure or DevRev.updateFeatureConfiguration(_:).","type":"text"}],"type":"paragraph"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/prefersSystemTheme":{"title":"prefersSystemTheme","deprecated":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/prefersSystemTheme","navigatorTitle":[{"text":"prefersSystemTheme","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/preferssystemtheme","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A flag to use the default theme for the support feature.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersSystemTheme","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"url":"\/documentation\/devrevsdk\/devrevinterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","role":"symbol","title":"DevRevInterop","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"deprecated":true,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","value":"prefersSystemTheme","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefersSystemTheme","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"prefersSystemTheme","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":[{"inlineContent":[{"type":"text","text":"Configure prefersSystemTheme via FeatureConfiguration passed to DevRev.configure or DevRev.updateFeatureConfiguration(_:)."}],"type":"paragraph"}],"path":"\/deprecationSummary","op":"replace"},{"value":"prefersSystemTheme","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1prefersSystemTheme\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1prefersSystemTheme\/fragments","value":[{"kind":"identifier","text":"prefersSystemTheme"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}]}]}]}