{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/processallondemandsessions()"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/processallondemandsessions()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"abstract":[{"type":"text","text":"Stops the ongoing user recording and sends all on-demand sessions along with the current recording."}],"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"processAllOnDemandSessions"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAllOnDemandSessions"},{"kind":"text","text":"()"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)processAllOnDemandSessions","modules":[{"name":"DevRevSDK"}],"roleHeading":"Type Method","role":"symbol","title":"processAllOnDemandSessions()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAllOnDemandSessions"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processAllOnDemandSessions()"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"title":"DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK","url":"\/documentation\/devrevsdk","role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/processAllOnDemandSessions()":{"abstract":[{"text":"Stops the ongoing user recording and sends all on-demand sessions along with the current recording.","type":"text"}],"title":"processAllOnDemandSessions()","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop\/processallondemandsessions()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAllOnDemandSessions"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"processAllOnDemandSessions"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processAllOnDemandSessions()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"processAllOnDemandSessions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"processAllOnDemandSessions"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"processAllOnDemandSessions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace"},{"value":"processAllOnDemandSessions","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processAllOnDemandSessions()\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processAllOnDemandSessions()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"processAllOnDemandSessions"}],"op":"replace"}]}]}