{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(processPushNotificationWithPayload:) ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processPushNotification"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"payload","content":[{"inlineContent":[{"type":"text","text":"The push notification JSON payload."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Processes the push notification and performs the necessary actions."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"metadata":{"modules":[{"name":"DevRevSDK"}],"role":"symbol","title":"processPushNotification(_:)","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)processPushNotificationWithPayload:","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processPushNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","navigatorTitle":[{"text":"processPushNotificationWithPayload:","kind":"identifier"}]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/processPushNotification(_:)":{"url":"\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)","navigatorTitle":[{"kind":"identifier","text":"processPushNotificationWithPayload:"}],"title":"processPushNotification(_:)","role":"symbol","abstract":[{"text":"Processes the push notification and performs the necessary actions.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"processPushNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop","kind":"symbol","role":"symbol","title":"DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"processPushNotificationWithPayload:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"processPushNotificationWithPayload:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"processPushNotificationWithPayload:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"payload"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"payload","content":[{"type":"paragraph","inlineContent":[{"text":"The push notification JSON payload.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processPushNotification(_:)\/title","value":"processPushNotificationWithPayload:","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processPushNotification(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"processPushNotificationWithPayload:","kind":"identifier"}],"op":"replace"},{"value":"DevRev","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}],"op":"replace"}]}]}