{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processPushNotification"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Sendable","preciseIdentifier":"s:s8SendableP"},{"kind":"text","text":"])"}],"title":"processPushNotification(_:)","symbolKind":"method","externalID":"s:9DevRevSDK0aB7InteropC23processPushNotificationyySDySSs8Sendable_pGFZ","modules":[{"name":"DevRevSDK"}],"role":"symbol","roleHeading":"Type Method"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)-5r4j4"]}],"abstract":[{"text":"Processes the push notification and performs the necessary actions.","type":"text"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-5r4j4","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processPushNotification"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Sendable","kind":"typeIdentifier","preciseIdentifier":"s:s8SendableP"},{"kind":"text","text":"])"}]}],"kind":"declarations"},{"parameters":[{"name":"userInfo","content":[{"inlineContent":[{"type":"text","text":"The user info dictionary from the push notification."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This overload is using the "},{"type":"codeVoice","code":"Sendable"},{"type":"text","text":" type from the push notification."}]}],"name":"Important"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/processPushNotification(_:)-5r4j4":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"processPushNotification","kind":"identifier"},{"text":"([","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Sendable","preciseIdentifier":"s:s8SendableP"},{"text":"])","kind":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)-5r4j4","kind":"symbol","title":"processPushNotification(_:)","role":"symbol","abstract":[{"type":"text","text":"Processes the push notification and performs the necessary actions."}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-5r4j4"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","type":"topic","abstract":[],"role":"collection"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"kind":"symbol","title":"DevRevInterop","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace","value":[{"kind":"identifier","text":"DevRev"}]},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}