{"kind":"symbol","abstract":[{"type":"text","text":"Registers the device token provided by Apple for receiving push notifications from DevRev."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(registerDeviceToken:forDeviceID:) ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The device token as provided by Apple, no need for processing the byte array.","type":"text"}],"type":"paragraph"}],"name":"deviceToken"},{"name":"deviceID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"type":"text","text":"unique"}]},{"type":"text","text":" to your system, or the app vendor"},{"text":" ","type":"text"},{"type":"text","text":"identifier i.e. IDFV ("},{"code":"UIDevice.identifierForVendor","type":"codeVoice"},{"type":"text","text":")."}]}]}]}],"metadata":{"navigatorTitle":[{"text":"registerDeviceToken:forDeviceID:","kind":"identifier"}],"title":"registerDeviceToken(_:deviceID:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"text":"deviceID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)registerDeviceToken:forDeviceID:","role":"symbol","modules":[{"name":"DevRevSDK"}],"symbolKind":"method","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)"]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/registerDeviceToken(_:deviceID:)":{"abstract":[{"type":"text","text":"Registers the device token provided by Apple for receiving push notifications from DevRev."}],"title":"registerDeviceToken(_:deviceID:)","url":"\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deviceID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerDeviceToken:forDeviceID:"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"url":"\/documentation\/devrevsdk\/devrevinterop","abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"registerDeviceToken:forDeviceID:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"registerDeviceToken:forDeviceID:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"registerDeviceToken:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deviceToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"forDeviceID:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceID","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"deviceToken","content":[{"inlineContent":[{"type":"text","text":"The device token as provided by Apple, no need for processing the byte array."}],"type":"paragraph"}]},{"name":"deviceID","content":[{"inlineContent":[{"text":"A unique device ID. This should be either an identifier ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"unique"}]},{"type":"text","text":" to your system, or the app vendor"},{"text":" ","type":"text"},{"text":"identifier i.e. IDFV (","type":"text"},{"type":"codeVoice","code":"UIDevice.identifierForVendor"},{"text":").","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)\/title","value":"registerDeviceToken:forDeviceID:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"registerDeviceToken:forDeviceID:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)\/fragments"},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DevRev"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}