{"kind":"symbol","metadata":{"modules":[{"name":"DevRevSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)registerRawDeviceToken:forDeviceID:","navigatorTitle":[{"kind":"identifier","text":"registerRawDeviceToken:forDeviceID:"}],"roleHeading":"Type Method","title":"registerDeviceToken(_:deviceID:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerDeviceToken"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deviceID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-3acfg"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-3acfg"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(registerRawDeviceToken:forDeviceID:) "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"deviceToken"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"deviceID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device token as provided by Apple, no need for processing the byte array."}]}],"name":"deviceToken"},{"name":"deviceID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"text":"unique","type":"text"}]},{"text":" to your system, or the app vendor","type":"text"},{"type":"text","text":" "},{"text":"identifier i.e. IDFV (","type":"text"},{"code":"UIDevice.identifierForVendor","type":"codeVoice"},{"text":").","type":"text"}]}]}]}],"abstract":[{"text":"Registers the device token as provided by Apple for receiving push notifications from DevRev.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-3acfg","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"role":"collection","type":"topic","title":"DevRevSDK","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/registerDeviceToken(_:deviceID:)-3acfg":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-3acfg","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerDeviceToken"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"deviceID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"registerRawDeviceToken:forDeviceID:","kind":"identifier"}],"title":"registerDeviceToken(_:deviceID:)","abstract":[{"text":"Registers the device token as provided by Apple for receiving push notifications from DevRev.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-3acfg"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"title":"DevRevInterop","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","role":"symbol","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"registerRawDeviceToken:forDeviceID:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerRawDeviceToken:forDeviceID:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerRawDeviceToken:"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"forDeviceID:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceID"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device token as provided by Apple, no need for processing the byte array."}]}],"name":"deviceToken"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"inlineContent":[{"type":"text","text":"unique"}],"type":"strong"},{"text":" to your system, or the app vendor","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"identifier i.e. IDFV ("},{"code":"UIDevice.identifierForVendor","type":"codeVoice"},{"text":").","type":"text"}]}],"name":"deviceID"}],"kind":"parameters"},"op":"replace"},{"value":"registerRawDeviceToken:forDeviceID:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-3acfg\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerRawDeviceToken:forDeviceID:"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-3acfg\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace","value":"DevRev"},{"value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}]}]}