{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deviceID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"registerDeviceToken:forDeviceID:"}],"modules":[{"name":"DevRevSDK"}],"title":"registerDeviceToken(_:deviceID:)","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)registerDeviceToken:forDeviceID:","symbolKind":"method"},"abstract":[{"text":"Registers the processed device token string for receiving push notifications from DevRev.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(registerDeviceToken:forDeviceID:) "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"deviceID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"deviceToken","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The processed device token string."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"type":"text","text":"unique"}]},{"text":" to your system, or the app vendor","type":"text"},{"type":"text","text":" "},{"type":"text","text":"identifier i.e. IDFV ("},{"type":"codeVoice","code":"UIDevice.identifierForVendor"},{"type":"text","text":")."}]}],"name":"deviceID"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-9lp2p","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-9lp2p"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-9lp2p"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"type":"topic","abstract":[],"role":"collection","title":"DevRevSDK","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevInterop"}],"url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"type":"topic","title":"DevRevInterop","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/registerDeviceToken(_:deviceID:)-9lp2p":{"abstract":[{"type":"text","text":"Registers the processed device token string for receiving push notifications from DevRev."}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-9lp2p","navigatorTitle":[{"text":"registerDeviceToken:forDeviceID:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-9lp2p","title":"registerDeviceToken(_:deviceID:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerDeviceToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"registerDeviceToken:forDeviceID:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerDeviceToken:forDeviceID:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerDeviceToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"deviceToken","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forDeviceID:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"deviceID","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"deviceToken","content":[{"inlineContent":[{"type":"text","text":"The processed device token string."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A unique device ID. This should be either an identifier ","type":"text"},{"type":"strong","inlineContent":[{"text":"unique","type":"text"}]},{"type":"text","text":" to your system, or the app vendor"},{"text":" ","type":"text"},{"text":"identifier i.e. IDFV (","type":"text"},{"code":"UIDevice.identifierForVendor","type":"codeVoice"},{"text":").","type":"text"}]}],"name":"deviceID"}],"kind":"parameters"}},{"value":"DevRev","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"kind":"identifier","text":"DevRev"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-9lp2p\/title","value":"registerDeviceToken:forDeviceID:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-9lp2p\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerDeviceToken:forDeviceID:"}],"op":"replace"}]}]}