{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Resumes a paused recording session."}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeRecording"},{"text":"()","kind":"text"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)resumeRecording","navigatorTitle":[{"kind":"identifier","text":"resumeRecording"}],"modules":[{"name":"DevRevSDK"}],"role":"symbol","title":"resumeRecording()","roleHeading":"Type Method","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeRecording()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resumeRecording","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/resumerecording()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/resumerecording()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/resumeRecording()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/resumerecording()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resumeRecording"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resumeRecording"}],"title":"resumeRecording()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeRecording()","abstract":[{"text":"Resumes a paused recording session.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"resumeRecording","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"resumeRecording"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"resumeRecording"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DevRev"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeRecording()\/title","value":"resumeRecording"},{"value":[{"text":"+ ","kind":"text"},{"text":"resumeRecording","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeRecording()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}