{"abstract":[{"type":"text","text":"Sets a flag that resumes the session monitoring."}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeAllMonitoring"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"The main purpose of this method is to get the consent (opt-in) of the end-user that their session will be monitored","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and data might be collected."}],"type":"paragraph"},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The monitoring flag is "},{"type":"strong","inlineContent":[{"type":"text","text":"opted-in"}]},{"type":"text","text":" by default, meaning it is enabled from start. In case you want to"}]}],"type":"aside","style":"important"},{"content":[{"inlineContent":[{"type":"text","text":"This method will only store a monitoring permission flag, it will "},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"text":" provide any UI or dialog.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The responsibility of implementing a UI is yours as a developer integrating the SDK."}],"type":"paragraph"}],"type":"aside","name":"Important","style":"important"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()"}]}],"type":"aside","name":"See Also","style":"note"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"title":"resumeAllMonitoring()","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"resumeAllMonitoring","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"DevRevSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)resumeAllMonitoring","navigatorTitle":[{"text":"resumeAllMonitoring","kind":"identifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/resumeallmonitoring()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/resumeallmonitoring()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/stopAllMonitoring()":{"navigatorTitle":[{"text":"stopAllMonitoring","kind":"identifier"}],"kind":"symbol","title":"stopAllMonitoring()","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/stopallmonitoring()","abstract":[{"type":"text","text":"Sets a flag that stops all session monitoring."}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAllMonitoring"},{"kind":"text","text":"()"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"title":"DevRevInterop","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/resumeAllMonitoring()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeAllMonitoring"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Sets a flag that resumes the session monitoring."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()","navigatorTitle":[{"kind":"identifier","text":"resumeAllMonitoring"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/resumeallmonitoring()","title":"resumeAllMonitoring()","role":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"resumeAllMonitoring","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"resumeAllMonitoring","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"resumeAllMonitoring"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"stopAllMonitoring","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopAllMonitoring()\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopAllMonitoring()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stopAllMonitoring"}]},{"value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeAllMonitoring()\/title","value":"resumeAllMonitoring","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeAllMonitoring()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"resumeAllMonitoring","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}