{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resumeUserInteractionTracking","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","role":"symbol","modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"text":"resumeUserInteractionTracking","kind":"identifier"}],"title":"resumeUserInteractionTracking()","roleHeading":"Type Method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)resumeUserInteractionTracking"},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeUserInteractionTracking()","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resumeUserInteractionTracking","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Resumes user interaction tracking."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/resumeuserinteractiontracking()"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/resumeuserinteractiontracking()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","role":"collection","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/resumeUserInteractionTracking()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/resumeuserinteractiontracking()","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resumeUserInteractionTracking"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"resumeUserInteractionTracking","kind":"identifier"}],"title":"resumeUserInteractionTracking()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeUserInteractionTracking()","abstract":[{"text":"Resumes user interaction tracking.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"resumeUserInteractionTracking","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"resumeUserInteractionTracking","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"resumeUserInteractionTracking","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev"},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"},{"value":"resumeUserInteractionTracking","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeUserInteractionTracking()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeUserInteractionTracking()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"resumeUserInteractionTracking"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}