{"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/setdelegate(_:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","text":"DevRevDelegate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)setDelegate:","roleHeading":"Type Method","title":"setDelegate(_:)","role":"symbol"},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/setDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the DevRev delegate."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(setDelegate:) ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","text":"DevRevDelegate"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"delegate","content":[{"inlineContent":[{"text":"A delegate object, conforming to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate"},{"type":"text","text":" protocol."}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"url":"\/documentation\/devrevsdk\/devrevinterop","role":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/setDelegate(_:)":{"navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Sets the DevRev delegate."}],"title":"setDelegate(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/setDelegate(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","text":"DevRevDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/setdelegate(_:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate":{"url":"\/documentation\/devrevsdk\/devrevdelegate","kind":"symbol","type":"topic","role":"symbol","title":"DevRevDelegate","navigatorTitle":[{"text":"DevRevDelegate","kind":"identifier"}],"abstract":[{"text":"A delegate protocol that notifies the host app of DevRev SDK’s session events.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevDelegate"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","type":"topic","abstract":[],"title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"setDelegate:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDelegate:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDelegate:"},{"kind":"text","text":"("},{"text":"id<DevRevDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DevRevSDK@objc(pl)DevRevDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":{"parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"A delegate object, conforming to the ","type":"text"},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","type":"reference","isActive":true},{"type":"text","text":" protocol."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}]},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"},{"value":"setDelegate:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1setDelegate(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDelegate:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1setDelegate(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/title","value":"DevRevDelegate"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/fragments","op":"replace","value":[{"text":"DevRevDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DevRevDelegate"}]}]}]}