{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/showsupport(isanimated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/showsupport(isanimated:)"]}],"kind":"symbol","abstract":[{"text":"Presents the support feature modally over the top most view controller.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(isAnimated:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(showSupport:) "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showSupport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isAnimated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = true)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag denoting whether the process is animated."}]}],"name":"isAnimated"}]}],"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)showSupport:","roleHeading":"Type Method","title":"showSupport(isAnimated:)","navigatorTitle":[{"text":"showSupport:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showSupport","kind":"identifier"},{"kind":"text","text":"("},{"text":"isAnimated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/showSupport(isAnimated:)":{"navigatorTitle":[{"text":"showSupport:","kind":"identifier"}],"abstract":[{"text":"Presents the support feature modally over the top most view controller.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(isAnimated:)","url":"\/documentation\/devrevsdk\/devrevinterop\/showsupport(isanimated:)","type":"topic","title":"showSupport(isAnimated:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showSupport","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isAnimated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"role":"symbol","type":"topic","title":"DevRevInterop","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"showSupport:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showSupport:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showSupport:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isAnimated"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"isAnimated","content":[{"inlineContent":[{"type":"text","text":"A flag denoting whether the process is animated."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(isAnimated:)\/title","op":"replace","value":"showSupport:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(isAnimated:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showSupport:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}]}]}