{"abstract":[{"text":"Pushes the support feature to your navigation stack.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(showSupportFromNavigationController:isAnimated:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSupport"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isAnimated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"navigationController","content":[{"inlineContent":[{"type":"text","text":"The navigation view controller where the support feature will be pushed."}],"type":"paragraph"}]},{"name":"isAnimated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag denoting whether the process is animated."}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-3d2ry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-3d2ry"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-3d2ry"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showSupport","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAnimated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)showSupportFromNavigationController:isAnimated:","navigatorTitle":[{"kind":"identifier","text":"showSupportFromNavigationController:isAnimated:"}],"modules":[{"name":"DevRevSDK"}],"title":"showSupport(from:isAnimated:)"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","title":"DevRevInterop"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/showSupport(from:isAnimated:)-3d2ry":{"navigatorTitle":[{"text":"showSupportFromNavigationController:isAnimated:","kind":"identifier"}],"abstract":[{"text":"Pushes the support feature to your navigation stack.","type":"text"}],"role":"symbol","title":"showSupport(from:isAnimated:)","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-3d2ry","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSupport"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isAnimated"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-3d2ry","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"showSupportFromNavigationController:isAnimated:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"showSupportFromNavigationController:isAnimated:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"showSupportFromNavigationController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":" *) "},{"text":"navigationController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isAnimated:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isAnimated"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"navigationController","content":[{"type":"paragraph","inlineContent":[{"text":"The navigation view controller where the support feature will be pushed.","type":"text"}]}]},{"name":"isAnimated","content":[{"inlineContent":[{"type":"text","text":"A flag denoting whether the process is animated."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","op":"replace","value":"DevRev"},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-3d2ry\/title","value":"showSupportFromNavigationController:isAnimated:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-3d2ry\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showSupportFromNavigationController:isAnimated:"}],"op":"replace"}]}]}