{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Presents the support feature modally.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-5ycu9"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(showSupportFromParentViewController:isAnimated:) "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSupport"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"parentViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isAnimated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The parent view controller over which you will show the support feature."}],"type":"paragraph"}],"name":"parentViewController"},{"name":"isAnimated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag denoting whether the process is animated."}]}]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-5ycu9"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-5ycu9"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"showSupportFromParentViewController:isAnimated:"}],"modules":[{"name":"DevRevSDK"}],"title":"showSupport(from:isAnimated:)","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)showSupportFromParentViewController:isAnimated:","role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showSupport","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAnimated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"title":"DevRevInterop","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/showSupport(from:isAnimated:)-5ycu9":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showSupport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAnimated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Presents the support feature modally."}],"navigatorTitle":[{"kind":"identifier","text":"showSupportFromParentViewController:isAnimated:"}],"kind":"symbol","title":"showSupport(from:isAnimated:)","url":"\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-5ycu9","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-5ycu9","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"showSupportFromParentViewController:isAnimated:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showSupportFromParentViewController:isAnimated:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showSupportFromParentViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAnimated:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isAnimated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"parentViewController","content":[{"inlineContent":[{"type":"text","text":"The parent view controller over which you will show the support feature."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A flag denoting whether the process is animated."}],"type":"paragraph"}],"name":"isAnimated"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"DevRev","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]},{"value":"showSupportFromParentViewController:isAnimated:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-5ycu9\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"showSupportFromParentViewController:isAnimated:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-5ycu9\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}