{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"content":[{"inlineContent":[{"text":"Make sure that you have called the ","type":"text"},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)","type":"reference","isActive":true},{"text":" method before.","type":"text"}],"type":"paragraph"}],"style":"important","type":"aside","name":"Important"}]}],"metadata":{"roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"startRecording","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)startRecording","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRecording","kind":"identifier"},{"text":"()","kind":"text"}],"title":"startRecording()","modules":[{"name":"DevRevSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/startrecording()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/startrecording()"]}],"sections":[],"abstract":[{"text":"Starts a user recording session.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startRecording()"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevInterop"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","type":"topic","title":"DevRevInterop","abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/configure(appID:)":{"navigatorTitle":[{"text":"configureWithAppID:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop\/configure(appid:)","title":"configure(appID:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"text":"appID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Configures the SDK with the app ID."}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/startRecording()":{"abstract":[{"type":"text","text":"Starts a user recording session."}],"navigatorTitle":[{"text":"startRecording","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/startrecording()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startRecording()","title":"startRecording()"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","abstract":[],"kind":"symbol","title":"DevRevSDK","type":"topic","url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"startRecording"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startRecording","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"startRecording","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"value":[{"kind":"identifier","text":"DevRev"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/title","value":"configureWithAppID:","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"configureWithAppID:"}]},{"value":"startRecording","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startRecording()\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startRecording()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startRecording","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}