{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopAllMonitoring"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"The method will revoke the consent given by the end-users for monitoring their sessions."}],"type":"paragraph"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"The monitoring flag is ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"opted-in"}]},{"type":"text","text":" by default, meaning it is enabled from start. In case you want to"}]}],"type":"aside","name":"Important"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"This method will only store a monitoring permission flag, it will "},{"type":"strong","inlineContent":[{"text":"not","type":"text"}]},{"type":"text","text":" provide any UI or dialog."},{"type":"text","text":" "},{"type":"text","text":"The responsibility of implementing a UI is yours as a developer integrating the SDK."}],"type":"paragraph"}],"style":"important","name":"Important"},{"style":"note","name":"See Also","content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()"}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/stopallmonitoring()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/stopallmonitoring()"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Sets a flag that stops all session monitoring."}],"metadata":{"role":"symbol","title":"stopAllMonitoring()","modules":[{"name":"DevRevSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"stopAllMonitoring","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopAllMonitoring"},{"text":"()","kind":"text"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)stopAllMonitoring","roleHeading":"Type Method"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"role":"symbol","kind":"symbol","type":"topic","title":"DevRevInterop","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/resumeAllMonitoring()":{"title":"resumeAllMonitoring()","url":"\/documentation\/devrevsdk\/devrevinterop\/resumeallmonitoring()","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resumeAllMonitoring","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Sets a flag that resumes the session monitoring.","type":"text"}],"navigatorTitle":[{"text":"resumeAllMonitoring","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","url":"\/documentation\/devrevsdk","role":"collection","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/stopAllMonitoring()":{"title":"stopAllMonitoring()","url":"\/documentation\/devrevsdk\/devrevinterop\/stopallmonitoring()","type":"topic","abstract":[{"type":"text","text":"Sets a flag that stops all session monitoring."}],"navigatorTitle":[{"text":"stopAllMonitoring","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopAllMonitoring","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"stopAllMonitoring","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"stopAllMonitoring","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"stopAllMonitoring"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"kind":"identifier","text":"DevRev"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeAllMonitoring()\/title","value":"resumeAllMonitoring"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeAllMonitoring()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"resumeAllMonitoring","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopAllMonitoring()\/title","value":"stopAllMonitoring"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopAllMonitoring()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"stopAllMonitoring","kind":"identifier"}],"op":"replace"}]}]}