{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/trackevent(name:properties:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/trackevent(name:properties:)"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackEvent(name:properties:)","interfaceLanguage":"swift"},"metadata":{"title":"trackEvent(name:properties:)","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"symbolKind":"method","modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)trackEventWithName:properties:","navigatorTitle":[{"text":"trackEventWithName:properties:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"abstract":[{"text":"Tracks an event described with a name and optional property payload.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(trackEventWithName:properties:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"] = [:])","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"inlineContent":[{"text":"An event name.","type":"text"}],"type":"paragraph"}]},{"name":"properties","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A property dictionary."}]}]}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","title":"DevRevSDK","url":"\/documentation\/devrevsdk","abstract":[],"type":"topic","kind":"symbol","role":"collection"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/trackEvent(name:properties:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"trackEventWithName:properties:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackEvent(name:properties:)","type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop\/trackevent(name:properties:)","kind":"symbol","role":"symbol","title":"trackEvent(name:properties:)","abstract":[{"type":"text","text":"Tracks an event described with a name and optional property payload."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"role":"symbol","abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","title":"DevRevInterop","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"trackEventWithName:properties:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"trackEventWithName:properties:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"trackEventWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"properties:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"properties","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"name","content":[{"inlineContent":[{"type":"text","text":"An event name."}],"type":"paragraph"}]},{"name":"properties","content":[{"inlineContent":[{"text":"A property dictionary.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1trackEvent(name:properties:)\/title","value":"trackEventWithName:properties:","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1trackEvent(name:properties:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"trackEventWithName:properties:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"kind":"identifier","text":"DevRev"}],"op":"replace"}]}]}