{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkSensitiveViews(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmarkSensitiveViews","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sensitiveViews"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An array of views you want to stop masking.","type":"text"}],"type":"paragraph"}],"name":"sensitiveViews"}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"They will no longer be shown as masked in the portal playbacks, unless they are auto masked.","type":"text"}]}],"kind":"content"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/unmarksensitiveviews(_:)"]},{"paths":["\/documentation\/devrevsdk\/devrevinterop\/unmarksensitiveviews(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"metadata":{"role":"symbol","title":"unmarkSensitiveViews(_:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unmarkSensitiveViews"},{"kind":"text","text":"(["},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Type Method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)unmarkSensitiveViews:","modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"kind":"identifier","text":"unmarkSensitiveViews:"}]},"sections":[],"abstract":[{"text":"Unmark the passed views as being sensitive.","type":"text"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol","title":"DevRevInterop","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/unmarkSensitiveViews(_:)":{"abstract":[{"text":"Unmark the passed views as being sensitive.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/unmarksensitiveviews(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkSensitiveViews(_:)","title":"unmarkSensitiveViews(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmarkSensitiveViews","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"unmarkSensitiveViews:","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"unmarkSensitiveViews:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"unmarkSensitiveViews:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"unmarkSensitiveViews:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<UIView *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"sensitiveViews","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"sensitiveViews","content":[{"inlineContent":[{"type":"text","text":"An array of views you want to stop masking."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"},{"op":"replace","value":"unmarkSensitiveViews:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unmarkSensitiveViews(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unmarkSensitiveViews(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unmarkSensitiveViews:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}