{"metadata":{"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"unmarkAllSensitiveViews"}],"role":"symbol","modules":[{"name":"DevRevSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmarkAllSensitiveViews","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)unmarkAllSensitiveViews","title":"unmarkAllSensitiveViews()"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Stop masking all views previously marked as sensitive.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkAllSensitiveViews()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/unmarkallsensitiveviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/unmarkallsensitiveviews()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(unmarkAllSensitiveViews) "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmarkAllSensitiveViews","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The method will only affect manually masked views."}],"type":"paragraph"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","title":"DevRevInterop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/unmarkAllSensitiveViews()":{"url":"\/documentation\/devrevsdk\/devrevinterop\/unmarkallsensitiveviews()","navigatorTitle":[{"kind":"identifier","text":"unmarkAllSensitiveViews"}],"abstract":[{"type":"text","text":"Stop masking all views previously marked as sensitive."}],"role":"symbol","title":"unmarkAllSensitiveViews()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkAllSensitiveViews()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmarkAllSensitiveViews","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"unmarkAllSensitiveViews","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"unmarkAllSensitiveViews"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"unmarkAllSensitiveViews","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unmarkAllSensitiveViews()\/title","op":"replace","value":"unmarkAllSensitiveViews"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unmarkAllSensitiveViews()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"unmarkAllSensitiveViews","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}