{"abstract":[{"text":"Unregisters the device from receiving push notifications from DevRev.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/unregisterdevice(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/unregisterdevice(_:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"unregisterDeviceWithID:"}],"symbolKind":"method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)unregisterDeviceWithID:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterDevice"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Type Method","modules":[{"name":"DevRevSDK"}],"title":"unregisterDevice(_:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(unregisterDeviceWithID:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"deviceID","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"deviceID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"type":"text","text":"unique"}]},{"type":"text","text":" to your system, or the app vendor"},{"type":"text","text":" "},{"type":"text","text":"identifier i.e. IDFV ("},{"type":"codeVoice","code":"UIDevice.identifierForVendor"},{"type":"text","text":")."}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unregisterDevice(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"type":"topic","role":"collection","title":"DevRevSDK","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/unregisterDevice(_:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterDeviceWithID:"}],"abstract":[{"type":"text","text":"Unregisters the device from receiving push notifications from DevRev."}],"title":"unregisterDevice(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unregisterDevice(_:)","url":"\/documentation\/devrevsdk\/devrevinterop\/unregisterdevice(_:)","kind":"symbol","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"unregisterDeviceWithID:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unregisterDeviceWithID:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"unregisterDeviceWithID:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceID"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A unique device ID. This should be either an identifier "},{"type":"strong","inlineContent":[{"type":"text","text":"unique"}]},{"type":"text","text":" to your system, or the app vendor"},{"type":"text","text":" "},{"type":"text","text":"identifier i.e. IDFV ("},{"type":"codeVoice","code":"UIDevice.identifierForVendor"},{"type":"text","text":")."}],"type":"paragraph"}],"name":"deviceID"}]},"op":"replace"},{"op":"replace","value":"unregisterDeviceWithID:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unregisterDevice(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"unregisterDeviceWithID:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unregisterDevice(_:)\/fragments"},{"op":"replace","value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"op":"replace","value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"op":"replace","value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}