{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/updateUser(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop\/updateuser(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevinterop\/updateuser(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateUser"},{"text":"(","kind":"text"},{"text":"Identity","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"updateUserWithIdentity:","kind":"identifier"}],"modules":[{"name":"DevRevSDK"}],"title":"updateUser(_:)","roleHeading":"Type Method","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(cm)updateUserWithIdentity:"},"abstract":[{"text":"Updates the properties of the current user.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(updateUserWithIdentity:) "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"identity","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","text":"Identity"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An identity object.","type":"text"}]}],"name":"identity"}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"You can use this method to provide additional data about the current user after you have already identified them.","type":"text"}],"type":"paragraph"},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure that you have called the "},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)","type":"reference"},{"type":"text","text":" method before."}]}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"userID"},{"text":" property can ","type":"text"},{"inlineContent":[{"type":"text","text":"not"}],"type":"emphasis"},{"text":" be updated.","type":"text"}]}],"name":"Important","type":"aside"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/configure(appID:)":{"abstract":[{"type":"text","text":"Configures the SDK with the app ID."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/configure(appid:)","navigatorTitle":[{"kind":"identifier","text":"configureWithAppID:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"configure(appID:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid","title":"userID","type":"topic","role":"symbol","abstract":[{"text":"A user identifier.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"userID","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRevInterop","kind":"identifier"}],"title":"DevRevInterop","type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop","role":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/updateUser(_:)":{"navigatorTitle":[{"text":"updateUserWithIdentity:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUser","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","text":"Identity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Updates the properties of the current user.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/updateUser(_:)","role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/updateuser(_:)","title":"updateUser(_:)","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"kind":"symbol","url":"\/documentation\/devrevsdk\/identity","title":"Identity","type":"topic","role":"symbol","abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"type":"text","text":" "},{"text":"The minimum information needed is the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Identity","kind":"identifier"}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"updateUserWithIdentity:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"updateUserWithIdentity:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"updateUserWithIdentity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","text":"Identity"},{"kind":"text","text":" *) "},{"text":"identity","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An identity object."}],"type":"paragraph"}],"name":"identity"}]},"op":"replace"},{"op":"replace","value":"configureWithAppID:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"configureWithAppID:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","op":"replace","value":"userID"},{"op":"replace","value":[{"text":"userID","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments"},{"op":"replace","value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"kind":"identifier","text":"DevRev"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"kind":"identifier","text":"DevRev"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1updateUser(_:)\/title","value":"updateUserWithIdentity:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"updateUserWithIdentity:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1updateUser(_:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","op":"replace","value":"Identity"},{"value":[{"kind":"identifier","text":"Identity"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments"},{"op":"replace","value":[{"text":"Identity","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle"}]}]}