{"abstract":[{"text":"The accent color for the widget (e.g., “#FF5733” or “rgb(255, 87, 51)”).","type":"text"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/accentColor","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"accentColor","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"accentColor","externalID":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme(py)accentColor","modules":[{"name":"DevRevSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/accentcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/accentcolor"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportWidgetTheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"title":"SupportWidgetTheme","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/accentColor":{"kind":"symbol","role":"symbol","title":"accentColor","abstract":[{"type":"text","text":"The accent color for the widget (e.g., “#FF5733” or “rgb(255, 87, 51)”)."}],"type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme\/accentcolor","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/accentColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"accentColor"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"accentColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accentColor"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accentColor"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","value":"SupportWidgetTheme","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","value":[{"text":"SupportWidgetTheme","kind":"identifier"}]},{"value":"accentColor","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1accentColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"accentColor"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1accentColor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}