{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"prefersSystemTheme","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"primaryTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accentColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"spacing"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?)"}],"role":"symbol","roleHeading":"Initializer","title":"init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)","navigatorTitle":[{"text":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:","kind":"identifier"}],"modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme(im)initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:","symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)"},"abstract":[{"text":"Creates a support widget configuration.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/init(preferssystemtheme:primarytextcolor:accentcolor:spacing:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/init(preferssystemtheme:primarytextcolor:accentcolor:spacing:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prefersSystemTheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"primaryTextColor"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"accentColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"spacing"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A flag to use the system preferred theme.","type":"text"}]}],"name":"prefersSystemTheme"},{"content":[{"inlineContent":[{"type":"text","text":"The primary text color for the widget."}],"type":"paragraph"}],"name":"primaryTextColor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The accent color for the widget."}]}],"name":"accentColor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The spacing configuration as a dictionary."}]}],"name":"spacing"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportWidgetTheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"title":"SupportWidgetTheme","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prefersSystemTheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"primaryTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"accentColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"spacing","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Creates a support widget configuration."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:"}],"url":"\/documentation\/devrevsdk\/supportwidgettheme\/init(preferssystemtheme:primarytextcolor:accentcolor:spacing:)","title":"init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)","type":"topic","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPrefersSystemTheme:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"prefersSystemTheme"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryTextColor:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"primaryTextColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accentColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accentColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"spacing:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" *) "},{"text":"spacing","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"A flag to use the system preferred theme.","type":"text"}],"type":"paragraph"}],"name":"prefersSystemTheme"},{"name":"primaryTextColor","content":[{"inlineContent":[{"text":"The primary text color for the widget.","type":"text"}],"type":"paragraph"}]},{"name":"accentColor","content":[{"inlineContent":[{"text":"The accent color for the widget.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The spacing configuration as a dictionary.","type":"text"}]}],"name":"spacing"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","value":"SupportWidgetTheme","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)\/title","value":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}