{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(from:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","modules":[{"name":"DevRevSDK"}],"roleHeading":"Initializer","externalID":"s:9DevRevSDK18SupportWidgetThemeC4fromACs7Decoder_p_tKcfc","title":"init(from:)","symbolKind":"init"},"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"url":"\/documentation\/devrevsdk\/supportwidgettheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupportWidgetTheme","kind":"identifier"}],"type":"topic","title":"SupportWidgetTheme","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/init(from:)":{"title":"init(from:)","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(from:)","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]}},"variantOverrides":[{"patch":[{"value":"SupportWidgetTheme","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}