{"metadata":{"role":"symbol","navigatorTitle":[{"text":"prefersSystemTheme","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme(py)prefersSystemTheme","title":"prefersSystemTheme","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefersSystemTheme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","modules":[{"name":"DevRevSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefersSystemTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/preferssystemtheme"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/preferssystemtheme"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/prefersSystemTheme","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"A flag to use the default theme for the support feature."}],"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"url":"\/documentation\/devrevsdk\/supportwidgettheme","type":"topic","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"kind":"symbol","navigatorTitle":[{"text":"SupportWidgetTheme","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","title":"SupportWidgetTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportWidgetTheme","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/prefersSystemTheme":{"role":"symbol","abstract":[{"type":"text","text":"A flag to use the default theme for the support feature."}],"navigatorTitle":[{"kind":"identifier","text":"prefersSystemTheme"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/prefersSystemTheme","url":"\/documentation\/devrevsdk\/supportwidgettheme\/preferssystemtheme","title":"prefersSystemTheme","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefersSystemTheme","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"prefersSystemTheme"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefersSystemTheme","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"prefersSystemTheme","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","value":"SupportWidgetTheme"},{"op":"replace","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1prefersSystemTheme\/title","value":"prefersSystemTheme"},{"value":[{"text":"prefersSystemTheme","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1prefersSystemTheme\/fragments"}]}]}