{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"]]},"abstract":[{"type":"text","text":"The primary text color for the widget (e.g., “#000000” or “rgb(0, 0, 0)”)."}],"kind":"symbol","metadata":{"modules":[{"name":"DevRevSDK"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"primaryTextColor","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"primaryTextColor","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme(py)primaryTextColor"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/primarytextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/primarytextcolor"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/primaryTextColor","interfaceLanguage":"swift"},"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"url":"\/documentation\/devrevsdk\/supportwidgettheme","navigatorTitle":[{"text":"SupportWidgetTheme","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportWidgetTheme","kind":"identifier"}],"abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","title":"SupportWidgetTheme"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/primaryTextColor":{"navigatorTitle":[{"kind":"identifier","text":"primaryTextColor"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/primaryTextColor","url":"\/documentation\/devrevsdk\/supportwidgettheme\/primarytextcolor","title":"primaryTextColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryTextColor"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"The primary text color for the widget (e.g., “#000000” or “rgb(0, 0, 0)”).","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"primaryTextColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"primaryTextColor"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"primaryTextColor","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","value":"SupportWidgetTheme","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"text":"SupportWidgetTheme","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"op":"replace","value":"primaryTextColor","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1primaryTextColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"primaryTextColor"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1primaryTextColor\/fragments"}]}]}