{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemDefault","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","kind":"typeIdentifier","text":"SupportWidgetTheme"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The default configuration that follows the system theme."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/systemDefault"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemDefault","kind":"identifier"},{"kind":"text","text":": "},{"text":"SupportWidgetTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"}],"role":"symbol","roleHeading":"Type Property","externalID":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme(cpy)systemDefault","modules":[{"name":"DevRevSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"systemDefault","kind":"identifier"}],"title":"systemDefault"},"variants":[{"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/systemdefault"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/supportwidgettheme\/systemdefault"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/systemDefault":{"title":"systemDefault","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The default configuration that follows the system theme."}],"navigatorTitle":[{"text":"systemDefault","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/supportwidgettheme\/systemdefault","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemDefault"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","kind":"typeIdentifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/systemDefault","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"url":"\/documentation\/devrevsdk\/supportwidgettheme","type":"topic","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"kind":"symbol","navigatorTitle":[{"text":"SupportWidgetTheme","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","title":"SupportWidgetTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportWidgetTheme","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"systemDefault","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"systemDefault","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","kind":"typeIdentifier","text":"SupportWidgetTheme"},{"text":" * ","kind":"text"},{"text":"systemDefault","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1systemDefault\/title","op":"replace","value":"systemDefault"},{"value":[{"text":"systemDefault","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1systemDefault\/fragments"},{"value":"SupportWidgetTheme","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"SupportWidgetTheme"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}