{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class"]]},"abstract":[{"type":"text","text":"The user’s email."}],"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/identity\/usertraits-swift.class\/email"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class\/email"},"metadata":{"role":"symbol","externalID":"s:9DevRevSDK8IdentityC10UserTraitsC5emailSSSgvp","roleHeading":"Instance Property","modules":[{"name":"DevRevSDK"}],"title":"email","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"navigatorTitle":[{"text":"userID","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"topic","url":"\/documentation\/devrevsdk\/identity\/userid","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A user identifier.","type":"text"}],"title":"userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class":{"type":"topic","role":"symbol","title":"Identity.UserTraits","url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserTraits","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UserTraits"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","abstract":[{"type":"text","text":"A collection of traits describing the user."}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class/email":{"role":"symbol","url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class\/email","kind":"symbol","title":"email","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class\/email","abstract":[{"type":"text","text":"The user’s email."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk","role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","role":"symbol","abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"text":" ","type":"text"},{"type":"text","text":"The minimum information needed is the "},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference"},{"text":".","type":"text"}],"type":"topic","title":"Identity","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/identity"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","op":"replace","value":"userID"},{"op":"replace","value":[{"text":"userID","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"text":"Identity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","value":[{"text":"Identity","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}