{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/identity\/usertraits-swift.class\/encode(to:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class\/encode(to:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DevRevSDK"}],"title":"encode(to:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7EncoderP","text":"Encoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","externalID":"s:9DevRevSDK8IdentityC10UserTraitsC6encode2toys7Encoder_p_tKF"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.encode(to:)"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"encoder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","abstract":[],"title":"DevRevSDK","kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"userID","type":"topic","url":"\/documentation\/devrevsdk\/identity\/userid","abstract":[{"text":"A user identifier.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"userID"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"type":"text","text":" "},{"text":"The information can be either on the level of organizations or your user.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The minimum information needed is the "},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Identity"}],"url":"\/documentation\/devrevsdk\/identity","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","title":"Identity"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class":{"title":"Identity.UserTraits","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","role":"symbol","url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class","abstract":[{"text":"A collection of traits describing the user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UserTraits","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserTraits","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class/encode(to:)":{"title":"encode(to:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class\/encode(to:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","role":"symbol","url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class\/encode(to:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"userID","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"text":"userID","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"Identity","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title"},{"op":"replace","value":[{"text":"Identity","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Identity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}