{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountTraits-swift.property","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountTraits"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC","text":"AccountTraits","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"accountTraits","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DevRevSDK@objc(cs)Identity(py)accountTraits","title":"accountTraits","modules":[{"name":"DevRevSDK"}]},"abstract":[{"type":"text","text":"A collection of traits describing the account."}],"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/identity\/accounttraits-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/identity\/accounttraits-swift.property"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountTraits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccountTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/AccountTraits-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AccountTraits","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AccountTraits"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","role":"symbol","kind":"symbol","title":"Identity.AccountTraits","url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.class","abstract":[{"text":"A collection of traits describing the account.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid","title":"userID","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"userID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"A user identifier.","type":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","role":"symbol","navigatorTitle":[{"text":"userID","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/accountTraits-swift.property":{"abstract":[{"text":"A collection of traits describing the account.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"accountTraits"}],"role":"symbol","url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.property","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountTraits-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountTraits","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC","text":"AccountTraits","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"accountTraits","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","url":"\/documentation\/devrevsdk","title":"DevRevSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Identity"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"text":" ","type":"text"},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"type":"text","text":" "},{"type":"text","text":"The minimum information needed is the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity","title":"Identity"},"doc://ai.devrev.sdk/documentation/DevRevSDK/AccountTraits":{"kind":"symbol","fragments":[{"text":"AccountTraits","kind":"identifier"}],"title":"AccountTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/AccountTraits","type":"topic","abstract":[{"text":"A collection of traits describing the account.","type":"text"}],"url":"\/documentation\/devrevsdk\/accounttraits","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"accountTraits","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"accountTraits","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"AccountTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/AccountTraits","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)AccountTraits"},{"kind":"text","text":" * "},{"text":"accountTraits","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"userID","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]},{"value":"accountTraits","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1accountTraits-swift.property\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1accountTraits-swift.property\/fragments","value":[{"text":"accountTraits","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity"},{"value":[{"text":"Identity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","value":[{"kind":"identifier","text":"Identity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}