{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/debugDescription","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomDebugStringConvertible.debugDescription"},{"type":"text","text":"."}],"metadata":{"title":"debugDescription","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"externalID":"c:@M@DevRevSDK@objc(cs)Identity(py)debugDescription","role":"symbol","modules":[{"name":"DevRevSDK"}]},"variants":[{"paths":["\/documentation\/devrevsdk\/identity\/debugdescription"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/identity\/debugdescription"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","abstract":[],"title":"DevRevSDK","type":"topic","role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","type":"topic","title":"Identity","url":"\/documentation\/devrevsdk\/identity","navigatorTitle":[{"text":"Identity","kind":"identifier"}],"abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"type":"text","text":" "},{"type":"text","text":"The minimum information needed is the "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/debugDescription":{"url":"\/documentation\/devrevsdk\/identity\/debugdescription","navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"title":"debugDescription","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/debugDescription"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","navigatorTitle":[{"text":"userID","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity\/userid","abstract":[{"text":"A user identifier.","type":"text"}],"type":"topic","title":"userID","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"debugDescription","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"debugDescription","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"kind":"identifier","text":"Identity"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","value":[{"text":"Identity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1debugDescription\/title","value":"debugDescription","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1debugDescription\/fragments","value":[{"text":"debugDescription","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","value":"userID","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"text":"userID","kind":"identifier"}],"op":"replace"}]}]}