{"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)Identity(im)initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:","modules":[{"name":"DevRevSDK"}],"title":"init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"organizationID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"accountID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userTraits"},{"text":": ","kind":"text"},{"text":"UserTraits","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"organizationTraits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OrganizationTraits","preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accountTraits"},{"kind":"text","text":": "},{"text":"AccountTraits","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC"},{"text":"?)","kind":"text"}]},"abstract":[{"type":"text","text":"Creates an identity structure."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"organizationID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"accountID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"userTraits","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC","text":"UserTraits"},{"text":"? = nil, ","kind":"text"},{"text":"organizationTraits","kind":"externalParam"},{"kind":"text","text":": "},{"text":"OrganizationTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"accountTraits"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","kind":"typeIdentifier","text":"AccountTraits","preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A user identifier."}],"type":"paragraph"}],"name":"userID"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An organization identifier."}]}],"name":"organizationID"},{"name":"accountID","content":[{"type":"paragraph","inlineContent":[{"text":"An account identifier.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A collection of traits describing the user.","type":"text"}]}],"name":"userTraits"},{"name":"organizationTraits","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A collection of traits describing the organization."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A collection of traits describing the account."}]}],"name":"accountTraits"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/identity\/init(userid:organizationid:accountid:usertraits:organizationtraits:accounttraits:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/identity\/init(userid:organizationid:accountid:usertraits:organizationtraits:accounttraits:)"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"abstract":[{"text":"A user identifier.","type":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"userID","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","navigatorTitle":[{"text":"userID","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserTraits":{"url":"\/documentation\/devrevsdk\/usertraits","abstract":[{"type":"text","text":"A collection of traits describing the user."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserTraits","role":"symbol","type":"topic","title":"UserTraits","kind":"symbol","fragments":[{"text":"UserTraits","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class":{"title":"Identity.UserTraits","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserTraits"}],"url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class","navigatorTitle":[{"text":"UserTraits","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","abstract":[{"type":"text","text":"A collection of traits describing the user."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/AccountTraits-swift.class":{"url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.class","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","role":"symbol","title":"Identity.AccountTraits","navigatorTitle":[{"text":"AccountTraits","kind":"identifier"}],"abstract":[{"type":"text","text":"A collection of traits describing the account."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountTraits"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class":{"title":"Identity.OrganizationTraits","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class","type":"topic","abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"navigatorTitle":[{"text":"OrganizationTraits","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrganizationTraits"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/AccountTraits":{"kind":"symbol","fragments":[{"kind":"identifier","text":"AccountTraits"}],"abstract":[{"type":"text","text":"A collection of traits describing the account."}],"title":"AccountTraits","url":"\/documentation\/devrevsdk\/accounttraits","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/AccountTraits","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/OrganizationTraits":{"role":"symbol","fragments":[{"text":"OrganizationTraits","kind":"identifier"}],"title":"OrganizationTraits","type":"topic","url":"\/documentation\/devrevsdk\/organizationtraits","kind":"symbol","abstract":[{"text":"A collection of traits describing the organization.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/OrganizationTraits"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","url":"\/documentation\/devrevsdk","role":"collection","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)","kind":"symbol","title":"init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)","abstract":[{"text":"Creates an identity structure.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"organizationID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"accountID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userTraits"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC","text":"UserTraits","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"organizationTraits","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC","kind":"typeIdentifier","text":"OrganizationTraits"},{"kind":"text","text":"?, "},{"text":"accountTraits","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AccountTraits","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:","kind":"identifier"}],"type":"topic","url":"\/documentation\/devrevsdk\/identity\/init(userid:organizationid:accountid:usertraits:organizationtraits:accounttraits:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"url":"\/documentation\/devrevsdk\/identity","abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"text":" ","type":"text"},{"text":"The information can be either on the level of organizations or your user.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The minimum information needed is the "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","role":"symbol","type":"topic","title":"Identity","navigatorTitle":[{"kind":"identifier","text":"Identity"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUserID:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userID"},{"kind":"text","text":" "},{"text":"organizationID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"organizationID"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountID:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accountID","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userTraits:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)UserTraits","text":"UserTraits","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserTraits"},{"kind":"text","text":" *) "},{"text":"userTraits","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"organizationTraits:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)OrganizationTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/OrganizationTraits","text":"OrganizationTraits","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"organizationTraits"},{"text":" ","kind":"text"},{"text":"accountTraits:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AccountTraits","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)AccountTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/AccountTraits"},{"text":" *) ","kind":"text"},{"text":"accountTraits","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"userID","content":[{"inlineContent":[{"type":"text","text":"A user identifier."}],"type":"paragraph"}]},{"name":"organizationID","content":[{"inlineContent":[{"type":"text","text":"An organization identifier."}],"type":"paragraph"}]},{"name":"accountID","content":[{"type":"paragraph","inlineContent":[{"text":"An account identifier.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A collection of traits describing the user.","type":"text"}]}],"name":"userTraits"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A collection of traits describing the organization.","type":"text"}]}],"name":"organizationTraits"},{"name":"accountTraits","content":[{"inlineContent":[{"text":"A collection of traits describing the account.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","value":"userID","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"text":"userID","kind":"identifier"}],"op":"replace"},{"value":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity","op":"replace"},{"value":[{"kind":"identifier","text":"Identity"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Identity"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle"}]}]}