{"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)Identity(py)organizationID","roleHeading":"Instance Property","navigatorTitle":[{"text":"organizationID","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"organizationID","symbolKind":"property","modules":[{"name":"DevRevSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/identity\/organizationid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/identity\/organizationid"]}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationID","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"An organization identifier."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk","role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/organizationID":{"title":"organizationID","type":"topic","role":"symbol","url":"\/documentation\/devrevsdk\/identity\/organizationid","abstract":[{"text":"An organization identifier.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"organizationID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"organizationID","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"navigatorTitle":[{"text":"userID","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"topic","url":"\/documentation\/devrevsdk\/identity\/userid","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A user identifier.","type":"text"}],"title":"userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","role":"symbol","abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"text":" ","type":"text"},{"type":"text","text":"The minimum information needed is the "},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference"},{"text":".","type":"text"}],"type":"topic","title":"Identity","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/identity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"organizationID"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"organizationID","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"organizationID","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationID\/title","value":"organizationID","op":"replace"},{"value":[{"text":"organizationID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationID\/fragments"},{"value":"userID","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"text":"userID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity"},{"value":[{"text":"Identity","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","op":"replace","value":[{"text":"Identity","kind":"identifier"}]}]}]}