{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"variants":[{"paths":["\/documentation\/devrevsdk\/identity\/organizationtraits-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/identity\/organizationtraits-swift.property"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationTraits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","text":"OrganizationTraits","preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationTraits"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"OrganizationTraits","preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC"},{"text":"?","kind":"text"}],"modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"kind":"identifier","text":"organizationTraits"}],"externalID":"c:@M@DevRevSDK@objc(cs)Identity(py)organizationTraits","title":"organizationTraits","roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationTraits-swift.property","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class":{"title":"Identity.OrganizationTraits","kind":"symbol","abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrganizationTraits"}],"navigatorTitle":[{"kind":"identifier","text":"OrganizationTraits"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/OrganizationTraits":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/OrganizationTraits","url":"\/documentation\/devrevsdk\/organizationtraits","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"OrganizationTraits","kind":"identifier"}],"abstract":[{"text":"A collection of traits describing the organization.","type":"text"}],"title":"OrganizationTraits"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"text":" ","type":"text"},{"type":"text","text":"The minimum information needed is the "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","title":"Identity","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Identity"}],"type":"topic","role":"symbol","url":"\/documentation\/devrevsdk\/identity","kind":"symbol","navigatorTitle":[{"text":"Identity","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/organizationTraits-swift.property":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationTraits-swift.property","kind":"symbol","role":"symbol","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.property","abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"type":"topic","title":"organizationTraits","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationTraits"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"OrganizationTraits","preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"organizationTraits"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","abstract":[{"type":"text","text":"A user identifier."}],"type":"topic","url":"\/documentation\/devrevsdk\/identity\/userid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"userID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"userID"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"organizationTraits","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"organizationTraits","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"OrganizationTraits","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)OrganizationTraits","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/OrganizationTraits"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"organizationTraits"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","op":"replace","value":[{"kind":"identifier","text":"Identity"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","value":[{"text":"Identity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationTraits-swift.property\/title","op":"replace","value":"organizationTraits"},{"op":"replace","value":[{"text":"organizationTraits","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationTraits-swift.property\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","value":"userID"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","op":"replace","value":[{"text":"userID","kind":"identifier"}]}]}]}