{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OrganizationTraits"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class"},"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"metadata":{"roleHeading":"Class","title":"Identity.OrganizationTraits","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OrganizationTraits"}],"navigatorTitle":[{"text":"OrganizationTraits","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DevRevSDK"}],"role":"symbol","externalID":"s:9DevRevSDK8IdentityC18OrganizationTraitsC"},"topicSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/init(displayName:domain:organizationDescription:phoneNumbers:tier:customFields:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/init(from:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/customFields","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/displayName","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/domain","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/organizationDescription","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/phoneNumbers","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/tier"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/encode(to:)"],"generated":true,"title":"Instance Methods"}],"abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"references":{"doc://ai.devrev.sdk/Se":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/Se","title":"Swift.Decodable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","url":"\/documentation\/devrevsdk\/identity","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Identity"}],"title":"Identity","abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"type":"text","text":" "},{"text":"The information can be either on the level of organizations or your user.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The minimum information needed is the "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","isActive":true},{"text":".","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/displayName":{"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/displayName","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/displayname","type":"topic","role":"symbol","title":"displayName","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The displayed name of the organization."}]},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","kind":"symbol","title":"Identity.OrganizationTraits","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrganizationTraits"}],"navigatorTitle":[{"text":"OrganizationTraits","kind":"identifier"}],"abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class","type":"topic"},"doc://ai.devrev.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.devrev.sdk\/SQ"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/init(from:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/init(from:)","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/init(from:)","title":"init(from:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/encode(to:)":{"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/encode(to:)","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/encode(to:)","title":"encode(to:)","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","abstract":[],"role":"collection","title":"DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/phoneNumbers":{"kind":"symbol","abstract":[{"type":"text","text":"The phone numbers of the organization."}],"title":"phoneNumbers","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/phoneNumbers","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/phonenumbers","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"phoneNumbers","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/init(displayName:domain:organizationDescription:phoneNumbers:tier:customFields:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"displayName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"domain","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"organizationDescription","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"phoneNumbers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"tier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"title":"init(displayName:domain:organizationDescription:phoneNumbers:tier:customFields:)","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/init(displayname:domain:organizationdescription:phonenumbers:tier:customfields:)","abstract":[{"type":"text","text":"Creates an organization traits structure."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/init(displayName:domain:organizationDescription:phoneNumbers:tier:customFields:)","role":"symbol"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/organizationDescription":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"organizationDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/organizationdescription","kind":"symbol","title":"organizationDescription","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/organizationDescription","type":"topic","abstract":[{"type":"text","text":"The description of the organization."}]},"doc://ai.devrev.sdk/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/ai.devrev.sdk\/SE"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/tier":{"kind":"symbol","abstract":[{"text":"The tier of the organization.","type":"text"}],"title":"tier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/tier","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/tier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","title":"userID","abstract":[{"text":"A user identifier.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid","navigatorTitle":[{"text":"userID","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"userID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/domain":{"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/domain","title":"domain","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"domain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The domain of the organization."}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/domain"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/customFields":{"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/customfields","abstract":[{"type":"text","text":"A dictionary of custom fields."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/customFields","title":"customFields","type":"topic","role":"symbol"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","op":"replace","value":"Identity"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"kind":"identifier","text":"Identity"}]},{"value":[{"kind":"identifier","text":"Identity"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle"},{"op":"replace","value":"userID","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]}]}]}