{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A collection of traits describing the user."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userTraits","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC","text":"UserTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/identity\/usertraits-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/identity\/usertraits-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userTraits-swift.property"},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userTraits","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC","text":"UserTraits","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@DevRevSDK@objc(cs)Identity(py)userTraits","title":"userTraits","navigatorTitle":[{"kind":"identifier","text":"userTraits"}],"modules":[{"name":"DevRevSDK"}]},"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","title":"DevRevSDK","url":"\/documentation\/devrevsdk","abstract":[],"type":"topic","kind":"symbol","role":"collection"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"userID","kind":"identifier"}],"abstract":[{"text":"A user identifier.","type":"text"}],"url":"\/documentation\/devrevsdk\/identity\/userid","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","title":"userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserTraits":{"url":"\/documentation\/devrevsdk\/usertraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserTraits","type":"topic","kind":"symbol","title":"UserTraits","fragments":[{"kind":"identifier","text":"UserTraits"}],"role":"symbol","abstract":[{"text":"A collection of traits describing the user.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"role":"symbol","url":"\/documentation\/devrevsdk\/identity","type":"topic","title":"Identity","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","kind":"symbol","abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"type":"text","text":" "},{"type":"text","text":"The minimum information needed is the "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userTraits-swift.property":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userTraits"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC","kind":"typeIdentifier","text":"UserTraits"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"userTraits"}],"url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.property","abstract":[{"type":"text","text":"A collection of traits describing the user."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userTraits-swift.property","kind":"symbol","type":"topic","title":"userTraits","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class":{"abstract":[{"type":"text","text":"A collection of traits describing the user."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserTraits","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","kind":"symbol","navigatorTitle":[{"text":"UserTraits","kind":"identifier"}],"title":"Identity.UserTraits","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"userTraits"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"userTraits","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserTraits","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)UserTraits","text":"UserTraits"},{"kind":"text","text":" * "},{"kind":"identifier","text":"userTraits"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","value":"userID"},{"value":[{"text":"userID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments"},{"value":"Identity","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"text":"Identity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","value":[{"kind":"identifier","text":"Identity"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userTraits-swift.property\/title","value":"userTraits","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userTraits-swift.property\/fragments","value":[{"kind":"identifier","text":"userTraits"}],"op":"replace"}]}]}