{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bool","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/bool(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue"]]},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bool"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"}],"externalID":"s:9DevRevSDK31ArticleSearchFilterOperandValueC4boolyACSbFZ","title":"bool(_:)","modules":[{"name":"DevRevSDK"}],"roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/bool(_:)"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue/bool(_:)":{"abstract":[],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/bool(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bool"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ArticleSearchFilterOperandValue","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"}],"title":"bool(_:)","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/bool(_:)","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"symbol","abstract":[{"text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"title":"ArticleSearchFilterOperandValue","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ArticleSearchFilterOperandValue","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title"},{"value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}]}]}]}