{"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(jsonobject:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(jsonobject:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/init(jsonObject:)"},"metadata":{"modules":[{"name":"DevRevSDK"}],"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"jsonObject"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithJsonObject:","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue(im)initWithJsonObject:","roleHeading":"Initializer","title":"init(jsonObject:)"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue"]]},"abstract":[{"type":"text","text":"Builds a nested value from JSON-compatible objects ("},{"code":"NSString","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":", "},{"code":"NSArray","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":")."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"jsonObject"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"abstract":[{"type":"text","text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object)."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"navigatorTitle":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"title":"ArticleSearchFilterOperandValue","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue/init(jsonObject:)":{"url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(jsonobject:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Builds a nested value from JSON-compatible objects ("},{"type":"codeVoice","code":"NSString"},{"type":"text","text":", "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":", "},{"code":"NSArray","type":"codeVoice"},{"text":", ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":").","type":"text"}],"kind":"symbol","title":"init(jsonObject:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"jsonObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithJsonObject:"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/init(jsonObject:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithJsonObject:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithJsonObject:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithJsonObject:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"jsonObject","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ArticleSearchFilterOperandValue","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}]},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue~1init(jsonObject:)\/title","value":"initWithJsonObject:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue~1init(jsonObject:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithJsonObject:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}