{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(stringarray:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(stringarray:)"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue"]]},"metadata":{"symbolKind":"init","modules":[{"name":"DevRevSDK"}],"title":"init(stringArray:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"stringArray","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue(im)stringArray:","navigatorTitle":[{"kind":"identifier","text":"stringArray:"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(stringArray:) ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"stringArray","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/init(stringArray:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue/init(stringArray:)":{"navigatorTitle":[{"text":"stringArray:","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(stringarray:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"stringArray","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"abstract":[],"type":"topic","title":"init(stringArray:)","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/init(stringArray:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"navigatorTitle":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","abstract":[{"text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object).","type":"text"}],"title":"ArticleSearchFilterOperandValue","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stringArray:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringArray:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"stringArray:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"stringArray","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"stringArray:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue~1init(stringArray:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue~1init(stringArray:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stringArray:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title","op":"replace","value":"ArticleSearchFilterOperandValue"},{"value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle"}]}]}