{"metadata":{"externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue(im)intArray:","title":"init(intArray:)","role":"symbol","modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"text":"intArray:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"intArray"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"])","kind":"text"}],"symbolKind":"init"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/init(intArray:)"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(intarray:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(intarray:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(intArray:) ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"intArray"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"])","kind":"text"}]}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue/init(intArray:)":{"type":"topic","title":"init(intArray:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"intArray","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/init(intArray:)","kind":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/init(intarray:)","navigatorTitle":[{"text":"intArray:","kind":"identifier"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"abstract":[{"type":"text","text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object)."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"navigatorTitle":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"title":"ArticleSearchFilterOperandValue","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"intArray:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"intArray:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"intArray:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"text":"intArray","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"intArray:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue~1init(intArray:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"intArray:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue~1init(intArray:)\/fragments"},{"value":"ArticleSearchFilterOperandValue","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}