{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/object(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/object(_:)"]}],"metadata":{"externalID":"s:9DevRevSDK31ArticleSearchFilterOperandValueC6objectyACSDySSACGFZ","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"object","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"}],"title":"object(_:)","symbolKind":"method","role":"symbol","modules":[{"name":"DevRevSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"},{"kind":"text","text":"]) -> "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"typeIdentifier","text":"ArticleSearchFilterOperandValue","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue/object(_:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"},{"text":"]) -> ","kind":"text"},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/object(_:)","title":"object(_:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/object(_:)","abstract":[],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"symbol","abstract":[{"text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"title":"ArticleSearchFilterOperandValue","type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ArticleSearchFilterOperandValue","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}]}]}]}