{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"text":"ArticleSearchFilterOperandValue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/string(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/string(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"string(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","externalID":"s:9DevRevSDK31ArticleSearchFilterOperandValueC6stringyACSSFZ","modules":[{"name":"DevRevSDK"}]},"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue/string(_:)":{"type":"topic","title":"string(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue\/string(_:)","role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue\/string(_:)","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"kind":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue","abstract":[{"type":"text","text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object)."}],"role":"symbol","navigatorTitle":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"title":"ArticleSearchFilterOperandValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title","value":"ArticleSearchFilterOperandValue","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle","value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}]}]}]}