{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk"]},{"paths":["\/documentation\/devrevsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"DevRevSDK","symbolKind":"module","modules":[{"name":"DevRevSDK"}],"roleHeading":"Framework","title":"DevRevSDK","role":"collection"},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"]},{"anchor":"Protocols","generated":true,"title":"Protocols","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate"]},{"generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/State"],"title":"Enumerations","anchor":"Enumerations"}],"hierarchy":{"paths":[[]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/State":{"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/State","navigatorTitle":[{"kind":"identifier","text":"State"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"State"}],"role":"symbol","abstract":[{"type":"text","text":"State of the SDK."}],"url":"\/documentation\/devrevsdk\/state","title":"State","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"title":"DevRevInterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"url":"\/documentation\/devrevsdk\/devrevinterop","role":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-35snb":{"title":"DevRev","type":"topic","url":"\/documentation\/devrevsdk\/devrev-35snb","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRev"}],"abstract":[{"type":"text","text":"An entry point to the DevRev SDK."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-35snb","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DevRev","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate":{"url":"\/documentation\/devrevsdk\/devrevdelegate","kind":"symbol","type":"topic","role":"symbol","title":"DevRevDelegate","navigatorTitle":[{"text":"DevRevDelegate","kind":"identifier"}],"abstract":[{"text":"A delegate protocol that notifies the host app of DevRev SDK’s session events.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevDelegate"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/OrganizationTraits":{"fragments":[{"kind":"identifier","text":"OrganizationTraits"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/organizationtraits","abstract":[{"text":"A collection of traits describing the organization.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/OrganizationTraits","title":"OrganizationTraits","type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"role":"symbol","abstract":[{"text":"A user identifier.","type":"text"}],"navigatorTitle":[{"text":"userID","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity\/userid","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","title":"userID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserTraits":{"fragments":[{"kind":"identifier","text":"UserTraits"}],"url":"\/documentation\/devrevsdk\/usertraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserTraits","kind":"symbol","abstract":[{"type":"text","text":"A collection of traits describing the user."}],"role":"symbol","title":"UserTraits","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"url":"\/documentation\/devrevsdk\/identity","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"text":" ","type":"text"},{"text":"The information can be either on the level of organizations or your user.","type":"text"},{"type":"text","text":" "},{"text":"The minimum information needed is the ","type":"text"},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"Identity","kind":"identifier"}],"kind":"symbol","title":"Identity","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Identity"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevSDKVersionNumber":{"fragments":[{"text":"DevRevSDKVersionNumber","kind":"identifier"}],"abstract":[{"text":"Project version number for DevRevSDK.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevsdkversionnumber","title":"DevRevSDKVersionNumber","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevSDKVersionNumber"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevSDKVersionString":{"role":"symbol","fragments":[{"kind":"identifier","text":"DevRevSDKVersionString"}],"title":"DevRevSDKVersionString","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevSDKVersionString","url":"\/documentation\/devrevsdk\/devrevsdkversionstring","kind":"symbol","abstract":[{"text":"Project version string for DevRevSDK.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/AccountTraits":{"fragments":[{"text":"AccountTraits","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A collection of traits describing the account."}],"url":"\/documentation\/devrevsdk\/accounttraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/AccountTraits","kind":"symbol","type":"topic","title":"AccountTraits"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","type":"topic","abstract":[],"title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","role":"collection","url":"\/documentation\/devrevsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Classes","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/AccountTraits","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/OrganizationTraits","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserTraits"],"title":"Classes","generated":true},{"title":"Protocols","generated":true,"anchor":"Protocols","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate"]},{"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevSDKVersionNumber","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevSDKVersionString"],"generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}]},{"value":[{"text":"DevRev","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle"},{"value":"DevRevDelegate","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/fragments","value":[{"text":"DevRevDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/navigatorTitle","op":"replace","value":[{"text":"DevRevDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","op":"replace","value":"userID"},{"op":"replace","value":[{"text":"userID","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments"},{"op":"replace","value":"Identity","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"text":"Identity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","value":[{"text":"Identity","kind":"identifier"}],"op":"replace"}]}]}