{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-47gi"},"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-47gi"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-47gi"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"DevRevSDK"}],"symbolKind":"init","title":"init(op:operands:)","roleHeading":"Initializer","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter(im)initWithOp:operands:","navigatorTitle":[{"text":"initWithOp:operands:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"operands","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ArticleSearchFilterOperand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand"},{"kind":"text","text":"])"}]},"abstract":[{"type":"text","text":"Creates an article search filter."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"operands","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ArticleSearchFilterOperand","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"op","content":[{"inlineContent":[{"text":"The filter operator string as sent in JSON (","type":"text"},{"type":"codeVoice","code":"op"},{"type":"text","text":" field). Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator"},{"type":"text","text":" in Swift for known operators."}],"type":"paragraph"}]},{"name":"operands","content":[{"inlineContent":[{"text":"The filter operands.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","kind":"symbol","type":"topic","title":"ArticleSearchFilter","url":"\/documentation\/devrevsdk\/articlesearchfilter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ArticleSearchFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"A single filter expression applied to article search."}],"navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk","title":"DevRevSDK","role":"collection","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","title":"ArticleSearchFilterOperand","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleSearchFilterOperand","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperator":{"url":"\/documentation\/devrevsdk\/filteroperator","title":"FilterOperator","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FilterOperator","kind":"identifier"}],"navigatorTitle":[{"text":"FilterOperator","kind":"identifier"}],"abstract":[{"type":"text","text":"Operators for article search filter expressions (DQL-style). JSON "},{"code":"op","type":"codeVoice"},{"type":"text","text":" values use snake_case (e.g. "},{"type":"codeVoice","code":"all_of"},{"type":"text","text":")."}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/init(op:operands:)-47gi":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-47gi","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"op"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operands"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","text":"ArticleSearchFilterOperand","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOp:operands:"}],"kind":"symbol","title":"init(op:operands:)","abstract":[{"type":"text","text":"Creates an article search filter."}],"role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-47gi"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithOp:operands:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOp:operands:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOp:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"op","kind":"internalParam"},{"kind":"text","text":" "},{"text":"operands:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<ArticleSearchFilterOperand *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"operands","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"op","content":[{"inlineContent":[{"text":"The filter operator string as sent in JSON (","type":"text"},{"code":"op","type":"codeVoice"},{"text":" field). Use ","type":"text"},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","isActive":true},{"text":" in Swift for known operators.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The filter operands.","type":"text"}]}],"name":"operands"}]}},{"value":"ArticleSearchFilter","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"text":"ArticleSearchFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","op":"replace","value":[{"text":"ArticleSearchFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","op":"replace","value":"ArticleSearchFilterOperand"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle","value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1init(op:operands:)-47gi\/title","op":"replace","value":"initWithOp:operands:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1init(op:operands:)-47gi\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithOp:operands:","kind":"identifier"}]}]}]}