{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-90hjw"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-90hjw"]}],"metadata":{"role":"symbol","title":"init(op:operands:)","modules":[{"name":"DevRevSDK"}],"externalID":"s:9DevRevSDK19ArticleSearchFilterC2op8operandsAcA0F8OperatorO_SayAA0deF7OperandCGtcfc","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FilterOperator","preciseIdentifier":"s:9DevRevSDK14FilterOperatorO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operands"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","text":"ArticleSearchFilterOperand","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"]]},"sections":[],"abstract":[{"text":"Convenience initializer using a typed operator (encodes to the same JSON ","type":"text"},{"type":"codeVoice","code":"op"},{"text":" string).","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"op","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FilterOperator","preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operands"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","text":"ArticleSearchFilterOperand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperator":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilterOperator"}],"navigatorTitle":[{"kind":"identifier","text":"FilterOperator"}],"type":"topic","url":"\/documentation\/devrevsdk\/filteroperator","abstract":[{"type":"text","text":"Operators for article search filter expressions (DQL-style). JSON "},{"code":"op","type":"codeVoice"},{"type":"text","text":" values use snake_case (e.g. "},{"type":"codeVoice","code":"all_of"},{"text":").","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","role":"symbol","title":"FilterOperator","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","type":"topic","title":"ArticleSearchFilterOperand","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","navigatorTitle":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilterOperand","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"abstract":[{"text":"A single filter expression applied to article search.","type":"text"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","type":"topic","title":"ArticleSearchFilter","url":"\/documentation\/devrevsdk\/articlesearchfilter","navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilter"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/init(op:operands:)-90hjw":{"url":"\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-90hjw","title":"init(op:operands:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-90hjw","type":"topic","kind":"symbol","abstract":[{"text":"Convenience initializer using a typed operator (encodes to the same JSON ","type":"text"},{"type":"codeVoice","code":"op"},{"type":"text","text":" string)."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"op","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FilterOperator","preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operands"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","text":"ArticleSearchFilterOperand"},{"kind":"text","text":"])"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","op":"replace","value":"ArticleSearchFilterOperand"},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title","op":"replace","value":"ArticleSearchFilter"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"text":"ArticleSearchFilter","kind":"identifier"}]},{"value":[{"text":"ArticleSearchFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}