{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"op"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DevRevSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"op","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"op","kind":"identifier"}],"title":"op","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter(py)op"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/op"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/op"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/op","interfaceLanguage":"swift"},"abstract":[{"text":"The filter operator string as sent in JSON (","type":"text"},{"code":"op","type":"codeVoice"},{"text":" field). Use ","type":"text"},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","type":"reference"},{"type":"text","text":" in Swift for known operators."}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk","title":"DevRevSDK","role":"collection","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","kind":"symbol","type":"topic","title":"ArticleSearchFilter","url":"\/documentation\/devrevsdk\/articlesearchfilter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ArticleSearchFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"A single filter expression applied to article search."}],"navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/op":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/op","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"op"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"op"}],"kind":"symbol","title":"op","abstract":[{"text":"The filter operator string as sent in JSON (","type":"text"},{"code":"op","type":"codeVoice"},{"type":"text","text":" field). Use "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","isActive":true},{"type":"text","text":" in Swift for known operators."}],"role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilter\/op"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperator":{"url":"\/documentation\/devrevsdk\/filteroperator","title":"FilterOperator","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FilterOperator","kind":"identifier"}],"navigatorTitle":[{"text":"FilterOperator","kind":"identifier"}],"abstract":[{"type":"text","text":"Operators for article search filter expressions (DQL-style). JSON "},{"code":"op","type":"codeVoice"},{"type":"text","text":" values use snake_case (e.g. "},{"type":"codeVoice","code":"all_of"},{"type":"text","text":")."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"op"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"op","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"op"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"ArticleSearchFilter","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","op":"replace","value":[{"text":"ArticleSearchFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1op\/title","value":"op","op":"replace"},{"op":"replace","value":[{"text":"op","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1op\/fragments"}]}]}