{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The filter operands."}],"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/operands"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilter\/operands"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operands"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","kind":"typeIdentifier","text":"ArticleSearchFilterOperand","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/operands","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"operands","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter(py)operands","roleHeading":"Instance Property","modules":[{"name":"DevRevSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"operands"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","text":"ArticleSearchFilterOperand","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"operands"}]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"url":"\/documentation\/devrevsdk\/articlesearchfilter","kind":"symbol","abstract":[{"text":"A single filter expression applied to article search.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilter","kind":"identifier"}],"title":"ArticleSearchFilter","navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/operands":{"navigatorTitle":[{"text":"operands","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"operands","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","kind":"typeIdentifier","text":"ArticleSearchFilterOperand"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/operands","url":"\/documentation\/devrevsdk\/articlesearchfilter\/operands","kind":"symbol","title":"operands","abstract":[{"text":"The filter operands.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","kind":"symbol","title":"ArticleSearchFilterOperand","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"operands"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"operands"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<ArticleSearchFilterOperand *>"},{"text":" * ","kind":"text"},{"text":"operands","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title","op":"replace","value":"ArticleSearchFilter"},{"value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments"},{"value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1operands\/title","value":"operands"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1operands\/fragments","op":"replace","value":[{"text":"operands","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","value":"ArticleSearchFilterOperand","op":"replace"},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace"}]}]}