{"abstract":[{"type":"text","text":"The description of the organization."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/organizationdescription"]}],"kind":"symbol","metadata":{"externalID":"s:9DevRevSDK8IdentityC18OrganizationTraitsC23organizationDescriptionSSSgvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"organizationDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"DevRevSDK"}],"role":"symbol","title":"organizationDescription"},"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/organizationDescription","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"organizationDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class/organizationDescription":{"type":"topic","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class\/organizationDescription","abstract":[{"text":"The description of the organization.","type":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class\/organizationdescription","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"title":"organizationDescription"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","url":"\/documentation\/devrevsdk\/identity","navigatorTitle":[{"text":"Identity","kind":"identifier"}],"abstract":[{"text":"A JSON-represented structure that describes your customer’s identity information.","type":"text"},{"type":"text","text":" "},{"text":"The information can be either on the level of organizations or your user.","type":"text"},{"type":"text","text":" "},{"text":"The minimum information needed is the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"Identity","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Identity"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"kind":"symbol","role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class":{"abstract":[{"text":"A collection of traits describing the organization.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OrganizationTraits"}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class","type":"topic","navigatorTitle":[{"text":"OrganizationTraits","kind":"identifier"}],"title":"Identity.OrganizationTraits"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"navigatorTitle":[{"kind":"identifier","text":"userID"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","type":"topic","abstract":[{"type":"text","text":"A user identifier."}],"title":"userID","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Identity","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"kind":"identifier","text":"Identity"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle","op":"replace","value":[{"text":"Identity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","op":"replace","value":"userID"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]}]}]}