{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"widgetSearch","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"},{"text":"? = nil, ","kind":"text"},{"text":"searchBarSearch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"widgetSearch","content":[{"inlineContent":[{"type":"text","text":"Filter for PLuG Widget search."}],"type":"paragraph"}]},{"name":"searchBarSearch","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Filter for CMDK search."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters"]]},"abstract":[{"text":"Creates an article search filters object.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilters\/init(widgetsearch:searchbarsearch:)"]},{"paths":["\/documentation\/devrevsdk\/articlesearchfilters\/init(widgetsearch:searchbarsearch:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters(im)initWithWidgetSearch:searchBarSearch:","role":"symbol","symbolKind":"init","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"widgetSearch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"kind":"text","text":"?, "},{"text":"searchBarSearch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithWidgetSearch:searchBarSearch:","kind":"identifier"}],"title":"init(widgetSearch:searchBarSearch:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(widgetSearch:searchBarSearch:)"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"title":"DevRevSDK","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","abstract":[{"type":"text","text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search)."}],"url":"\/documentation\/devrevsdk\/articlesearchfilters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilters"}],"title":"ArticleSearchFilters","kind":"symbol","navigatorTitle":[{"text":"ArticleSearchFilters","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/init(widgetSearch:searchBarSearch:)":{"title":"init(widgetSearch:searchBarSearch:)","url":"\/documentation\/devrevsdk\/articlesearchfilters\/init(widgetsearch:searchbarsearch:)","abstract":[{"type":"text","text":"Creates an article search filters object."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(widgetSearch:searchBarSearch:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"widgetSearch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"searchBarSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter"},{"kind":"text","text":"?)"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithWidgetSearch:searchBarSearch:","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"kind":"symbol","title":"ArticleSearchFilter","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","url":"\/documentation\/devrevsdk\/articlesearchfilter","role":"symbol","abstract":[{"text":"A single filter expression applied to article search.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilter"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilter"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithWidgetSearch:searchBarSearch:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidgetSearch:searchBarSearch:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithWidgetSearch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","text":"ArticleSearchFilter"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"widgetSearch"},{"text":" ","kind":"text"},{"text":"searchBarSearch:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"searchBarSearch","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Filter for PLuG Widget search."}],"type":"paragraph"}],"name":"widgetSearch"},{"name":"searchBarSearch","content":[{"inlineContent":[{"text":"Filter for CMDK search.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/title","value":"ArticleSearchFilters"},{"value":[{"kind":"identifier","text":"ArticleSearchFilters"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ArticleSearchFilters"}]},{"value":"initWithWidgetSearch:searchBarSearch:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1init(widgetSearch:searchBarSearch:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithWidgetSearch:searchBarSearch:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1init(widgetSearch:searchBarSearch:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title","op":"replace","value":"ArticleSearchFilter"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","value":[{"text":"ArticleSearchFilter","kind":"identifier"}]}]}]}