{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters"]]},"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilters\/searchbarsearch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilters\/searchbarsearch"]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"searchBarSearch","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters(py)searchBarSearch","modules":[{"name":"DevRevSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarSearch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"searchBarSearch"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Filter for CMDK search."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/searchBarSearch"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters":{"navigatorTitle":[{"text":"ArticleSearchFilters","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search)."}],"url":"\/documentation\/devrevsdk\/articlesearchfilters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilters"}],"type":"topic","title":"ArticleSearchFilters","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/searchBarSearch":{"abstract":[{"text":"Filter for CMDK search.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/searchBarSearch","type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilters\/searchbarsearch","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchBarSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"searchBarSearch"}],"title":"searchBarSearch","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A single filter expression applied to article search.","type":"text"}],"url":"\/documentation\/devrevsdk\/articlesearchfilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilter"}],"type":"topic","title":"ArticleSearchFilter","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"searchBarSearch","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"searchBarSearch"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"ArticleSearchFilter","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"kind":"text","text":" * "},{"text":"searchBarSearch","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"ArticleSearchFilters","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilters"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/navigatorTitle","value":[{"text":"ArticleSearchFilters","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"searchBarSearch","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1searchBarSearch\/title"},{"value":[{"text":"searchBarSearch","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1searchBarSearch\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title","value":"ArticleSearchFilter"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","op":"replace","value":[{"text":"ArticleSearchFilter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}