{"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilters\/widgetsearch"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilters\/widgetsearch"]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"widgetSearch","kind":"identifier"}],"title":"widgetSearch","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"widgetSearch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"kind":"text","text":"?"}],"modules":[{"name":"DevRevSDK"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters(py)widgetSearch"},"kind":"symbol","abstract":[{"text":"Filter for PLuG Widget search.","type":"text"}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/widgetSearch","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"widgetSearch"},{"kind":"text","text":": "},{"text":"ArticleSearchFilter","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/widgetSearch":{"type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilters\/widgetsearch","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"widgetSearch"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/widgetSearch","abstract":[{"text":"Filter for PLuG Widget search.","type":"text"}],"title":"widgetSearch","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"widgetSearch","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter"},{"kind":"text","text":"?"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","title":"ArticleSearchFilters","navigatorTitle":[{"text":"ArticleSearchFilters","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilters","abstract":[{"text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilters"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"abstract":[{"text":"A single filter expression applied to article search.","type":"text"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","type":"topic","title":"ArticleSearchFilter","url":"\/documentation\/devrevsdk\/articlesearchfilter","navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilter"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"widgetSearch","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"widgetSearch"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter"},{"text":" * ","kind":"text"},{"text":"widgetSearch","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"widgetSearch","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1widgetSearch\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1widgetSearch\/fragments","op":"replace","value":[{"text":"widgetSearch","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/title","value":"ArticleSearchFilters","op":"replace"},{"value":[{"text":"ArticleSearchFilters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/fragments"},{"value":[{"text":"ArticleSearchFilters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/navigatorTitle"},{"value":"ArticleSearchFilter","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","value":[{"kind":"identifier","text":"ArticleSearchFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}