{"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate\/devRevSessionDidStart()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/devrevsdk\/devrevdelegate\/devrevsessiondidstart()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/devrevdelegate\/devrevsessiondidstart()"]}],"metadata":{"navigatorTitle":[{"text":"devRevSessionDidStart","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(pl)DevRevDelegate(im)devRevSessionDidStart","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"devRevSessionDidStart","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"DevRevSDK"}],"title":"devRevSessionDidStart()"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate"]]},"abstract":[{"text":"Called when the DevRev SDK has successfully initialized and is ready to be used.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"devRevSessionDidStart","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"This method is an approppriate point to fetch the current session URL.","type":"text"}]}],"style":"note"}],"kind":"content"}],"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","url":"\/documentation\/devrevsdk","type":"topic","role":"collection"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate/devRevSessionDidStart()":{"url":"\/documentation\/devrevsdk\/devrevdelegate\/devrevsessiondidstart()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate\/devRevSessionDidStart()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"devRevSessionDidStart","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"devRevSessionDidStart"}],"title":"devRevSessionDidStart()","abstract":[{"text":"Called when the DevRev SDK has successfully initialized and is ready to be used.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate":{"url":"\/documentation\/devrevsdk\/devrevdelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevRevDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DevRevDelegate"}],"title":"DevRevDelegate","abstract":[{"text":"A delegate protocol that notifies the host app of DevRev SDK’s session events.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"devRevSessionDidStart"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"devRevSessionDidStart","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"devRevSessionDidStart","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate~1devRevSessionDidStart()\/title","value":"devRevSessionDidStart"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate~1devRevSessionDidStart()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"devRevSessionDidStart","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/title","value":"DevRevDelegate"},{"value":[{"text":"DevRevDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/fragments"},{"value":[{"text":"DevRevDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}