{"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"DevRevSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@DevRevSDK@objc(cs)DevRev(im)init","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-7x2h1\/init","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/devrevsdk\/devrev-7x2h1\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","url":"\/documentation\/devrevsdk","role":"collection"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-7x2h1/init":{"title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrev-7x2h1\/init","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-7x2h1\/init","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","type":"topic","title":"DevRevInterop","navigatorTitle":[{"kind":"identifier","text":"DevRevInterop"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DevRevInterop"}],"abstract":[{"text":"An interoperability object used as an entry point to the DevRev SDK.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DevRev","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title"},{"value":[{"kind":"identifier","text":"DevRev"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments"},{"value":[{"text":"DevRev","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","op":"replace"}]}]}