{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/snapshotmask\/location\/init(location:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A region to be masked."}],"type":"paragraph"}],"name":"location"}]}],"kind":"symbol","abstract":[{"text":"Creates a location configuration for a specific mask type.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location"]]},"metadata":{"externalID":"s:9DevRevSDK12SnapshotMaskC8LocationC8locationAESo6CGRectV_tcfc","symbolKind":"init","role":"symbol","modules":[{"name":"DevRevSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(location:)"},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location\/init(location:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/Location":{"title":"SnapshotMask.Location","kind":"symbol","abstract":[{"type":"text","text":"A class that describes the regions with its mask type."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location","url":"\/documentation\/devrevsdk\/snapshotmask\/location","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Location"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Location","kind":"identifier"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","abstract":[],"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask":{"url":"\/documentation\/devrevsdk\/snapshotmask","title":"SnapshotMask","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A class that describes the regions of a snapshot to be masked for privacy purposes."}],"navigatorTitle":[{"text":"SnapshotMask","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SnapshotMask"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/Location/init(location:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Creates a location configuration for a specific mask type.","type":"text"}],"title":"init(location:)","url":"\/documentation\/devrevsdk\/snapshotmask\/location\/init(location:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location\/init(location:)"}},"variantOverrides":[{"patch":[{"value":"SnapshotMask","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/title"},{"value":[{"text":"SnapshotMask","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/navigatorTitle","value":[{"kind":"identifier","text":"SnapshotMask"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}