{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-9myv6","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetype:)-9myv6"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"init(field:op:value:valueType:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"field","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"op","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FilterOperator","preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier","text":"ArticleSearchFilterOperandValue"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"valueType"},{"text":": ","kind":"text"},{"text":"FilterOperandValueType","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO"},{"text":")","kind":"text"}],"symbolKind":"init","externalID":"s:9DevRevSDK26ArticleSearchFilterOperandC5field2op5value0J4TypeACSS_AA0F8OperatorOAA0defG5ValueCAA0fgmK0Otcfc","modules":[{"name":"DevRevSDK"}],"roleHeading":"Initializer","role":"symbol"},"abstract":[{"text":"Convenience initializer using a typed operator.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"field","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","text":"FilterOperator","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ArticleSearchFilterOperandValue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"valueType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperandValueType","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","kind":"typeIdentifier","text":"FilterOperandValueType"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"field","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The field to filter on (e.g. "},{"code":"\"article.tags.tag_id\"","type":"codeVoice"},{"type":"text","text":")."}]}]},{"name":"op","content":[{"inlineContent":[{"type":"text","text":"The operator string for this operand ("},{"type":"codeVoice","code":"op"},{"type":"text","text":" in JSON)."}],"type":"paragraph"}]},{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value to compare against."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value type for the operand."}]}],"name":"valueType"}],"kind":"parameters"}],"kind":"symbol","sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","title":"DevRevSDK","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperator":{"abstract":[{"type":"text","text":"Operators for article search filter expressions (DQL-style). JSON "},{"code":"op","type":"codeVoice"},{"text":" values use snake_case (e.g. ","type":"text"},{"type":"codeVoice","code":"all_of"},{"type":"text","text":")."}],"navigatorTitle":[{"kind":"identifier","text":"FilterOperator"}],"url":"\/documentation\/devrevsdk\/filteroperator","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","title":"FilterOperator","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FilterOperator","kind":"identifier"}],"type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(field:op:value:valueType:)-9myv6":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-9myv6","title":"init(field:op:value:valueType:)","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetype:)-9myv6","abstract":[{"type":"text","text":"Convenience initializer using a typed operator."}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"field","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","text":"FilterOperator"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueType"},{"kind":"text","text":": "},{"text":"FilterOperandValueType","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"symbol","abstract":[{"text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"title":"ArticleSearchFilterOperandValue","type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","title":"ArticleSearchFilterOperand","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"abstract":[{"text":"A single operand in a filter expression.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperandValueType":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperandValueType","abstract":[{"text":"How the operand ","type":"text"},{"code":"FilterOperand","type":"codeVoice"},{"text":" ","type":"text"},{"code":"value","type":"codeVoice"},{"text":" is interpreted (","type":"text"},{"code":"valueType","type":"codeVoice"},{"type":"text","text":" in JSON)."}],"role":"symbol","navigatorTitle":[{"text":"FilterOperandValueType","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/filteroperandvaluetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilterOperandValueType","kind":"identifier"}],"type":"topic","title":"FilterOperandValueType","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title","value":"ArticleSearchFilterOperandValue"},{"op":"replace","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","value":"ArticleSearchFilterOperand","op":"replace"},{"value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle","value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}]}]}]}