{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"field"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"op"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"},{"text":", ","kind":"text"},{"text":"valueType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FilterOperandValueType","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperandValueType","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The field to filter on (e.g. "},{"type":"codeVoice","code":"\"article.tags.tag_id\""},{"text":").","type":"text"}],"type":"paragraph"}],"name":"field"},{"name":"op","content":[{"type":"paragraph","inlineContent":[{"text":"The operator string for this operand (","type":"text"},{"code":"op","type":"codeVoice"},{"text":" in JSON).","type":"text"}]}]},{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value to compare against."}]}]},{"name":"valueType","content":[{"type":"paragraph","inlineContent":[{"text":"The value type for the operand.","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"DevRevSDK"}],"externalID":"s:9DevRevSDK26ArticleSearchFilterOperandC5field2op5value0J4TypeACSS_SSAA0defG5ValueCAA0fglK0Otcfc","symbolKind":"init","title":"init(field:op:value:valueType:)","role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"field","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"op","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilterOperandValue","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"valueType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","text":"FilterOperandValueType"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Creates a filter operand."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-osxc"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetype:)-osxc"]}],"sections":[],"kind":"symbol","references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(field:op:value:valueType:)-osxc":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"field","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"op","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"},{"text":", ","kind":"text"},{"text":"valueType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FilterOperandValueType","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO"},{"text":")","kind":"text"}],"title":"init(field:op:value:valueType:)","kind":"symbol","abstract":[{"text":"Creates a filter operand.","type":"text"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-osxc","type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetype:)-osxc"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"title":"ArticleSearchFilterOperandValue","abstract":[{"text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object).","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperandValueType":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FilterOperandValueType"}],"url":"\/documentation\/devrevsdk\/filteroperandvaluetype","abstract":[{"type":"text","text":"How the operand "},{"type":"codeVoice","code":"FilterOperand"},{"text":" ","type":"text"},{"code":"value","type":"codeVoice"},{"type":"text","text":" is interpreted ("},{"type":"codeVoice","code":"valueType"},{"text":" in JSON).","type":"text"}],"title":"FilterOperandValueType","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperandValueType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FilterOperandValueType","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk","title":"DevRevSDK","role":"collection","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","title":"ArticleSearchFilterOperand","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleSearchFilterOperand","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"ArticleSearchFilterOperandValue","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle","op":"replace","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}]},{"op":"replace","value":"ArticleSearchFilterOperand","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments","op":"replace","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}