{"abstract":[{"type":"text","text":"Objective-C–friendly initializer when "},{"type":"codeVoice","code":"valueType"},{"type":"text","text":" is only available as a string ("},{"code":"\"json\"","type":"codeVoice"},{"type":"text","text":" or "},{"code":"\"part\"","type":"codeVoice"},{"type":"text","text":")."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"field","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueTypeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The field to filter on (e.g. "},{"code":"\"article.tags.tag_id\"","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}],"name":"field"},{"name":"op","content":[{"inlineContent":[{"text":"The operator string for this operand (","type":"text"},{"type":"codeVoice","code":"op"},{"text":" in JSON).","type":"text"}],"type":"paragraph"}]},{"name":"value","content":[{"inlineContent":[{"text":"The value to compare against.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value type for the operand as a string ("},{"code":"\"json\"","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"\"part\""},{"text":").","type":"text"}]}],"name":"valueTypeString"}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetypestring:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetypestring:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithField:op:value:valueTypeString:"}],"modules":[{"name":"DevRevSDK"}],"role":"symbol","symbolKind":"init","title":"init(field:op:value:valueTypeString:)","roleHeading":"Initializer","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand(im)initWithField:op:value:valueTypeString:","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"field","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"op","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier","text":"ArticleSearchFilterOperandValue"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"valueTypeString"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueTypeString:)","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(field:op:value:valueTypeString:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithField:op:value:valueTypeString:"}],"abstract":[{"type":"text","text":"Objective-C–friendly initializer when "},{"code":"valueType","type":"codeVoice"},{"type":"text","text":" is only available as a string ("},{"type":"codeVoice","code":"\"json\""},{"text":" or ","type":"text"},{"code":"\"part\"","type":"codeVoice"},{"text":").","type":"text"}],"role":"symbol","title":"init(field:op:value:valueTypeString:)","kind":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetypestring:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"field"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"op","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"},{"text":", ","kind":"text"},{"text":"valueTypeString","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueTypeString:)","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperandValue":{"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}],"kind":"symbol","type":"topic","abstract":[{"text":"A value in a filter operand. Supports types that serialize to JSON (string, number, bool, array, object).","type":"text"}],"title":"ArticleSearchFilterOperandValue","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","url":"\/documentation\/devrevsdk\/articlesearchfilteroperandvalue"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","type":"topic","title":"ArticleSearchFilterOperand","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","navigatorTitle":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilterOperand","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithField:op:value:valueTypeString:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithField:op:value:valueTypeString:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithField:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"field","kind":"internalParam"},{"kind":"text","text":" "},{"text":"op:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"op","kind":"internalParam"},{"kind":"text","text":" "},{"text":"value:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":" ","kind":"text"},{"kind":"identifier","text":"valueTypeString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"valueTypeString","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The field to filter on (e.g. "},{"type":"codeVoice","code":"\"article.tags.tag_id\""},{"text":").","type":"text"}]}],"name":"field"},{"name":"op","content":[{"type":"paragraph","inlineContent":[{"text":"The operator string for this operand (","type":"text"},{"code":"op","type":"codeVoice"},{"text":" in JSON).","type":"text"}]}]},{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value to compare against."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The value type for the operand as a string (","type":"text"},{"type":"codeVoice","code":"\"json\""},{"type":"text","text":" or "},{"type":"codeVoice","code":"\"part\""},{"text":").","type":"text"}]}],"name":"valueTypeString"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1init(field:op:value:valueTypeString:)\/title","value":"initWithField:op:value:valueTypeString:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1init(field:op:value:valueTypeString:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithField:op:value:valueTypeString:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/title","op":"replace","value":"ArticleSearchFilterOperandValue"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/fragments","value":[{"kind":"identifier","text":"ArticleSearchFilterOperandValue"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperandValue\/navigatorTitle","value":[{"text":"ArticleSearchFilterOperandValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","op":"replace","value":"ArticleSearchFilterOperand"},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments"},{"value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle"}]}]}