{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"op","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"op","role":"symbol","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand(py)op","roleHeading":"Instance Property","modules":[{"name":"DevRevSDK"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"op"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"op"}]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/op","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The operator string for this operand (","type":"text"},{"type":"codeVoice","code":"op"},{"type":"text","text":" in JSON)."}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"]]},"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/op"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/op"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/op":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/op","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/op","type":"topic","navigatorTitle":[{"kind":"identifier","text":"op"}],"kind":"symbol","abstract":[{"type":"text","text":"The operator string for this operand ("},{"code":"op","type":"codeVoice"},{"type":"text","text":" in JSON)."}],"title":"op","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"op","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","kind":"symbol","title":"ArticleSearchFilterOperand","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"op","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"op","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"op","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"op","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1op\/title"},{"value":[{"text":"op","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1op\/fragments"},{"value":"ArticleSearchFilterOperand","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}