{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/valueType"},"abstract":[{"type":"text","text":"How "},{"isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value","type":"reference"},{"text":" is encoded for the API (JSON ","type":"text"},{"code":"valueType","type":"codeVoice"},{"type":"text","text":": "},{"type":"codeVoice","code":"\"json\""},{"text":" or ","type":"text"},{"code":"\"part\"","type":"codeVoice"},{"type":"text","text":")."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand\/valuetype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueType"},{"text":": ","kind":"text"},{"text":"FilterOperandValueType","kind":"typeIdentifier","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperandValueType","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO"}]}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"s:9DevRevSDK26ArticleSearchFilterOperandC9valueTypeAA0fg5ValueI0Ovp","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","text":"FilterOperandValueType","kind":"typeIdentifier"}],"title":"valueType","modules":[{"name":"DevRevSDK"}]},"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/valueType":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/valueType","abstract":[{"type":"text","text":"How "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value","isActive":true,"type":"reference"},{"type":"text","text":" is encoded for the API (JSON "},{"type":"codeVoice","code":"valueType"},{"type":"text","text":": "},{"code":"\"json\"","type":"codeVoice"},{"type":"text","text":" or "},{"code":"\"part\"","type":"codeVoice"},{"type":"text","text":")."}],"title":"valueType","role":"symbol","type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/valuetype","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueType"},{"text":": ","kind":"text"},{"text":"FilterOperandValueType","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","kind":"typeIdentifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"url":"\/documentation\/devrevsdk","kind":"symbol","title":"DevRevSDK","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","kind":"symbol","title":"ArticleSearchFilterOperand","role":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperandValueType":{"title":"FilterOperandValueType","navigatorTitle":[{"kind":"identifier","text":"FilterOperandValueType"}],"url":"\/documentation\/devrevsdk\/filteroperandvaluetype","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperandValueType","abstract":[{"type":"text","text":"How the operand "},{"type":"codeVoice","code":"FilterOperand"},{"text":" ","type":"text"},{"type":"codeVoice","code":"value"},{"type":"text","text":" is interpreted ("},{"code":"valueType","type":"codeVoice"},{"type":"text","text":" in JSON)."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FilterOperandValueType"}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/value":{"abstract":[{"type":"text","text":"The value to compare against."}],"type":"topic","title":"value","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value","role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"text":"ArticleSearchFilterOperandValue","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"value","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title","value":"ArticleSearchFilterOperand"},{"value":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments"},{"op":"replace","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1value\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1value\/fragments","value":[{"text":"value","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}