{"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(from:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(widgetSearch:searchBarSearch:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/searchBarSearch","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/widgetSearch"]}],"metadata":{"role":"symbol","title":"ArticleSearchFilters","modules":[{"name":"DevRevSDK"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilters"}],"symbolKind":"class","externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters","navigatorTitle":[{"text":"ArticleSearchFilters","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search)."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilters"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Set via ","type":"text"},{"code":"FeatureConfiguration.supportWidgetArticleSearchFilters","type":"codeVoice"},{"text":"; filters are applied automatically when the support widget is ready.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The filter applies to both PLuG Widget search and CMDK (keyboard shortcut) search."}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilters"]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","interfaceLanguage":"swift"},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/init(widgetSearch:searchBarSearch:)":{"url":"\/documentation\/devrevsdk\/articlesearchfilters\/init(widgetsearch:searchbarsearch:)","abstract":[{"type":"text","text":"Creates an article search filters object."}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(widgetSearch:searchBarSearch:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"widgetSearch"},{"kind":"text","text":": "},{"text":"ArticleSearchFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"text":"?, ","kind":"text"},{"text":"searchBarSearch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"text":"?)","kind":"text"}],"title":"init(widgetSearch:searchBarSearch:)","role":"symbol","navigatorTitle":[{"text":"initWithWidgetSearch:searchBarSearch:","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SQ","title":"Swift.Equatable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters":{"navigatorTitle":[{"text":"ArticleSearchFilters","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Filters that control which articles are returned by PLuG search (widget search and CMDK search)."}],"url":"\/documentation\/devrevsdk\/articlesearchfilters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilters"}],"type":"topic","title":"ArticleSearchFilters","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters","role":"symbol"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"},"doc://ai.devrev.sdk/SE":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SE","title":"Swift.Encodable"},"doc://ai.devrev.sdk/Se":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/Se","title":"Swift.Decodable"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","title":"NSObject"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/searchBarSearch":{"abstract":[{"text":"Filter for CMDK search.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/searchBarSearch","type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilters\/searchbarsearch","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchBarSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","text":"ArticleSearchFilter"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"searchBarSearch"}],"title":"searchBarSearch","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/widgetSearch":{"title":"widgetSearch","role":"symbol","navigatorTitle":[{"text":"widgetSearch","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/widgetSearch","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"widgetSearch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ArticleSearchFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Filter for PLuG Widget search."}],"type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilters\/widgetsearch"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilters/init(from:)":{"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(from:)","url":"\/documentation\/devrevsdk\/articlesearchfilters\/init(from:)","type":"topic","title":"init(from:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ArticleSearchFilters","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ArticleSearchFilters","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ArticleSearchFilters"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/searchBarSearch","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/widgetSearch"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilters\/init(widgetSearch:searchBarSearch:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilters"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1init(widgetSearch:searchBarSearch:)\/title","value":"initWithWidgetSearch:searchBarSearch:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1init(widgetSearch:searchBarSearch:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithWidgetSearch:searchBarSearch:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/title","op":"replace","value":"ArticleSearchFilters"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/fragments","value":[{"text":"ArticleSearchFilters","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ArticleSearchFilters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters\/navigatorTitle"},{"value":"searchBarSearch","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1searchBarSearch\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1searchBarSearch\/fragments","value":[{"kind":"identifier","text":"searchBarSearch"}],"op":"replace"},{"value":"widgetSearch","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1widgetSearch\/title"},{"value":[{"kind":"identifier","text":"widgetSearch"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilters~1widgetSearch\/fragments"}]}]}