{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilter","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(from:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-47gi","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-90hjw"],"anchor":"Initializers"},{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/op","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/operands"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"modules":[{"name":"DevRevSDK"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilter"}],"externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilter","title":"ArticleSearchFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilter"}],"roleHeading":"Class","role":"symbol"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/devrevsdk\/articlesearchfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilter"]}],"abstract":[{"type":"text","text":"A single filter expression applied to article search."}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/init(from:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(from:)","abstract":[],"title":"init(from:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilter\/init(from:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol","type":"topic","url":"\/documentation\/devrevsdk","title":"DevRevSDK","role":"collection","abstract":[]},"doc://ai.devrev.sdk/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/ai.devrev.sdk\/SE","type":"unresolvable"},"doc://ai.devrev.sdk/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/ai.devrev.sdk\/Se","type":"unresolvable"},"doc://ai.devrev.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/ai.devrev.sdk\/SQ","type":"unresolvable"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/operands":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/operands","abstract":[{"text":"The filter operands.","type":"text"}],"title":"operands","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operands"},{"kind":"text","text":": ["},{"text":"ArticleSearchFilterOperand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"operands","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/articlesearchfilter\/operands"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.devrev.sdk\/SH"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/init(op:operands:)-47gi":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-47gi","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"op"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operands"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","text":"ArticleSearchFilterOperand","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOp:operands:"}],"kind":"symbol","title":"init(op:operands:)","abstract":[{"type":"text","text":"Creates an article search filter."}],"role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-47gi"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/init(op:operands:)-90hjw":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-90hjw","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"op"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","text":"FilterOperator","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operands"},{"text":": [","kind":"text"},{"text":"ArticleSearchFilterOperand","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"kind":"symbol","title":"init(op:operands:)","abstract":[{"type":"text","text":"Convenience initializer using a typed operator (encodes to the same JSON "},{"code":"op","type":"codeVoice"},{"text":" string).","type":"text"}],"role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilter\/init(op:operands:)-90hjw"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FilterOperator":{"url":"\/documentation\/devrevsdk\/filteroperator","title":"FilterOperator","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FilterOperator","kind":"identifier"}],"navigatorTitle":[{"text":"FilterOperator","kind":"identifier"}],"abstract":[{"type":"text","text":"Operators for article search filter expressions (DQL-style). JSON "},{"code":"op","type":"codeVoice"},{"type":"text","text":" values use snake_case (e.g. "},{"type":"codeVoice","code":"all_of"},{"type":"text","text":")."}],"kind":"symbol"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter","kind":"symbol","type":"topic","title":"ArticleSearchFilter","url":"\/documentation\/devrevsdk\/articlesearchfilter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ArticleSearchFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"A single filter expression applied to article search."}],"navigatorTitle":[{"text":"ArticleSearchFilter","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilter/op":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/op","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"op"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"op"}],"kind":"symbol","title":"op","abstract":[{"text":"The filter operator string as sent in JSON (","type":"text"},{"code":"op","type":"codeVoice"},{"type":"text","text":" field). Use "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FilterOperator","isActive":true},{"type":"text","text":" in Swift for known operators."}],"role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilter\/op"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"ArticleSearchFilter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"ArticleSearchFilter","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ArticleSearchFilter"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/op","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/operands"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilter\/init(op:operands:)-47gi"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ArticleSearchFilter","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"value":"operands","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1operands\/title","op":"replace"},{"value":[{"kind":"identifier","text":"operands"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1operands\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1init(op:operands:)-47gi\/title","op":"replace","value":"initWithOp:operands:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1init(op:operands:)-47gi\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithOp:operands:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/title","value":"ArticleSearchFilter"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/fragments","value":[{"text":"ArticleSearchFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ArticleSearchFilter"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1op\/title","value":"op","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilter~1op\/fragments","value":[{"kind":"identifier","text":"op"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}