{"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-9myv6","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-osxc","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueTypeString:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(from:)"],"generated":true,"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/field","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/op","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/valueType"],"anchor":"Instance-Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand"},"metadata":{"title":"ArticleSearchFilterOperand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"externalID":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperand","roleHeading":"Class","modules":[{"name":"DevRevSDK"}],"symbolKind":"class","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/articlesearchfilteroperand"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(field:op:value:valueType:)-osxc":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-osxc","role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetype:)-osxc","title":"init(field:op:value:valueType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"field"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"op","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"valueType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FilterOperandValueType","preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a filter operand."}],"type":"topic","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/field":{"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/field","title":"field","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/field","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"field","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","abstract":[{"type":"text","text":"The field to filter on (e.g. "},{"code":"\"article.tags.tag_id\"","type":"codeVoice"},{"type":"text","text":")."}],"kind":"symbol","navigatorTitle":[{"text":"field","kind":"identifier"}]},"doc://ai.devrev.sdk/SE":{"identifier":"doc:\/\/ai.devrev.sdk\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://ai.devrev.sdk/s7CVarArgP":{"identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://ai.devrev.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SQ","title":"Swift.Equatable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/value":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value","kind":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/value","title":"value","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"text":"ArticleSearchFilterOperandValue","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The value to compare against."}],"navigatorTitle":[{"text":"value","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand":{"abstract":[{"type":"text","text":"A single operand in a filter expression."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperand"}],"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand","navigatorTitle":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand","title":"ArticleSearchFilterOperand"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(field:op:value:valueType:)-9myv6":{"type":"topic","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetype:)-9myv6","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueType:)-9myv6","role":"symbol","abstract":[{"type":"text","text":"Convenience initializer using a typed operator."}],"kind":"symbol","title":"init(field:op:value:valueType:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"field"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"op","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FilterOperator","preciseIdentifier":"s:9DevRevSDK14FilterOperatorO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue"},{"text":", ","kind":"text"},{"text":"valueType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","text":"FilterOperandValueType","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(field:op:value:valueTypeString:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueTypeString:)","role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(field:op:value:valuetypestring:)","title":"init(field:op:value:valueTypeString:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"field"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"op","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilterOperandValue","text":"ArticleSearchFilterOperandValue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"valueTypeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithField:op:value:valueTypeString:","kind":"identifier"}],"abstract":[{"type":"text","text":"Objective-C–friendly initializer when "},{"code":"valueType","type":"codeVoice"},{"text":" is only available as a string (","type":"text"},{"code":"\"json\"","type":"codeVoice"},{"type":"text","text":" or "},{"code":"\"part\"","type":"codeVoice"},{"type":"text","text":")."}],"type":"topic","kind":"symbol"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/valueType":{"url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/valuetype","title":"valueType","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/valueType","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK22FilterOperandValueTypeO","text":"FilterOperandValueType","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"How "},{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value","isActive":true,"type":"reference"},{"type":"text","text":" is encoded for the API (JSON "},{"code":"valueType","type":"codeVoice"},{"text":": ","type":"text"},{"code":"\"json\"","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"\"part\""},{"type":"text","text":")."}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/init(from:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(from:)","role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/init(from:)","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"},"doc://ai.devrev.sdk/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/Se"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH"},"doc://ai.devrev.sdk/documentation/DevRevSDK/ArticleSearchFilterOperand/op":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/op","role":"symbol","url":"\/documentation\/devrevsdk\/articlesearchfilteroperand\/op","title":"op","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"op","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"op","kind":"identifier"}],"abstract":[{"type":"text","text":"The operator string for this operand ("},{"code":"op","type":"codeVoice"},{"text":" in JSON).","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ArticleSearchFilterOperand","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/field","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/op","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/value"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/ArticleSearchFilterOperand\/init(field:op:value:valueTypeString:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleSearchFilterOperand"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1field\/title","value":"field","op":"replace"},{"value":[{"kind":"identifier","text":"field"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1field\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1value\/title","value":"value","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"replace","value":"ArticleSearchFilterOperand","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/fragments","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"ArticleSearchFilterOperand","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1init(field:op:value:valueTypeString:)\/title","value":"initWithField:op:value:valueTypeString:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithField:op:value:valueTypeString:"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1init(field:op:value:valueTypeString:)\/fragments"},{"value":"op","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1op\/title","op":"replace"},{"value":[{"text":"op","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1ArticleSearchFilterOperand~1op\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}