{"abstract":[{"type":"text","text":"A delegate protocol that notifies the host app of DevRev SDK’s session events."}],"kind":"symbol","metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRevDelegate","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(pl)DevRevDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","title":"DevRevDelegate","navigatorTitle":[{"kind":"identifier","text":"DevRevDelegate"}],"modules":[{"name":"DevRevSDK"}]},"topicSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate\/devRevSessionDidStart()"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DevRevDelegate) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRevDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/devrevdelegate"]},{"paths":["\/documentation\/devrevsdk\/devrevdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","interfaceLanguage":"swift"},"sections":[],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate/devRevSessionDidStart()":{"title":"devRevSessionDidStart()","role":"symbol","type":"topic","navigatorTitle":[{"text":"devRevSessionDidStart","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrevdelegate\/devrevsessiondidstart()","abstract":[{"type":"text","text":"Called when the DevRev SDK has successfully initialized and is ready to be used."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate\/devRevSessionDidStart()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"devRevSessionDidStart"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevDelegate":{"abstract":[{"type":"text","text":"A delegate protocol that notifies the host app of DevRev SDK’s session events."}],"title":"DevRevDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DevRevDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DevRevDelegate"}],"url":"\/documentation\/devrevsdk\/devrevdelegate","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate","type":"topic"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DevRevDelegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DevRevDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DevRevDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevDelegate\/devRevSessionDidStart()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DevRevDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate~1devRevSessionDidStart()\/title","value":"devRevSessionDidStart"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"devRevSessionDidStart"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate~1devRevSessionDidStart()\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/title","op":"replace","value":"DevRevDelegate"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevDelegate\/fragments","value":[{"text":"DevRevDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}