{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/areOnDemandSessionsEnabled","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/inAppLinkHandler","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isConfigured","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isMonitoringEnabled","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isRecording","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isUserIdentified","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/prefersSystemTheme","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/shouldDismissModalsOnOpenLink"],"anchor":"Type-Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/addSessionProperties(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/createSupportConversation(isAnimated:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/endTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyAnonymousUser(userID:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyUnverifiedUser(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyVerifiedUser(_:sessionToken:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/logout(deviceID:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/markSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processAllOnDemandSessions()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-5r4j4","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-7ncbs","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-3acfg","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-9lp2p","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/sessionURL(for:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/setDelegate(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-3d2ry","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-5ycu9","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(isAnimated:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackEvent(name:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackScreenName(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unregisterDevice(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/updateUser(_:)"],"anchor":"Type-Methods","generated":true}],"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DevRev) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"The class exposes the functions to Objective-C, and its main purpose is to be used in app framework bridges."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Certain features of the SDK might require prior user identification before being called, make sure you have triggered"},{"type":"text","text":" "},{"type":"text","text":"the appropriate identification method before calling the features."}],"type":"paragraph"}]}],"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/devrevinterop"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/devrevinterop"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}],"symbolKind":"class","title":"DevRevInterop","modules":[{"name":"DevRevSDK"}],"role":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)DevRev","roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/createSupportConversation(isAnimated:)":{"url":"\/documentation\/devrevsdk\/devrevinterop\/createsupportconversation(isanimated:)","role":"symbol","title":"createSupportConversation(isAnimated:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/createSupportConversation(isAnimated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createSupportConversation:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSupportConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isAnimated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new support conversation over the top most view controller."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/resumeRecording()":{"type":"topic","role":"symbol","kind":"symbol","title":"resumeRecording()","navigatorTitle":[{"kind":"identifier","text":"resumeRecording"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeRecording()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resumes a paused recording session."}],"url":"\/documentation\/devrevsdk\/devrevinterop\/resumerecording()"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://ai.devrev.sdk/SQ":{"identifier":"doc:\/\/ai.devrev.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop":{"abstract":[{"type":"text","text":"An interoperability object used as an entry point to the DevRev SDK."}],"title":"DevRevInterop","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop","url":"\/documentation\/devrevsdk\/devrevinterop","type":"topic","role":"symbol","navigatorTitle":[{"text":"DevRevInterop","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRevInterop","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/trackEvent(name:properties:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackEventWithName:properties:"}],"title":"trackEvent(name:properties:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackEvent(name:properties:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"text":"Tracks an event described with a name and optional property payload.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/trackevent(name:properties:)","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/sessionURL(for:)":{"url":"\/documentation\/devrevsdk\/devrevinterop\/sessionurl(for:)","type":"topic","abstract":[{"type":"text","text":"Creates a shortened URL string for the user recording session."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sessionURLForPlatform:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/sessionURL(for:)","title":"sessionURL(for:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/areOnDemandSessionsEnabled":{"title":"areOnDemandSessionsEnabled","type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop\/areondemandsessionsenabled","kind":"symbol","abstract":[{"type":"text","text":"A flag denoting whether the on-demand sessions are enabled."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/areOnDemandSessionsEnabled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"areOnDemandSessionsEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/markSensitiveViews(_:)":{"abstract":[{"type":"text","text":"Mark the passed views as sensitive."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markSensitiveViews","kind":"identifier"},{"text":"([","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/markSensitiveViews(_:)","url":"\/documentation\/devrevsdk\/devrevinterop\/marksensitiveviews(_:)","title":"markSensitiveViews(_:)","navigatorTitle":[{"text":"markSensitiveViews:","kind":"identifier"}]},"doc://ai.devrev.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/endTimer(_:properties:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/endTimer(_:properties:)","role":"symbol","navigatorTitle":[{"text":"endTimerWithName:properties:","kind":"identifier"}],"abstract":[{"text":"Ends a previously started timer.","type":"text"}],"title":"endTimer(_:properties:)","url":"\/documentation\/devrevsdk\/devrevinterop\/endtimer(_:properties:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/prefersSystemTheme":{"url":"\/documentation\/devrevsdk\/devrevinterop\/preferssystemtheme","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/prefersSystemTheme","abstract":[{"text":"A flag to use the default theme for the support feature.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersSystemTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"prefersSystemTheme","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/pauseRecording()":{"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/pauserecording()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseRecording"},{"kind":"text","text":"()"}],"title":"pauseRecording()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Pauses the ongoing user recording session."}],"navigatorTitle":[{"kind":"identifier","text":"pauseRecording"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseRecording()"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/unregisterDevice(_:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterDeviceWithID:"}],"abstract":[{"type":"text","text":"Unregisters the device from receiving push notifications from DevRev."}],"title":"unregisterDevice(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unregisterDevice(_:)","url":"\/documentation\/devrevsdk\/devrevinterop\/unregisterdevice(_:)","kind":"symbol","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/setDelegate(_:)":{"role":"symbol","title":"setDelegate(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/setDelegate(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DevRevDelegate","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the DevRev delegate."}],"url":"\/documentation\/devrevsdk\/devrevinterop\/setdelegate(_:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/isMonitoringEnabled":{"url":"\/documentation\/devrevsdk\/devrevinterop\/ismonitoringenabled","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isMonitoringEnabled","title":"isMonitoringEnabled","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMonitoringEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"A flag denoting whether session monitoring is enabled."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/stopAllMonitoring()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAllMonitoring","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()","url":"\/documentation\/devrevsdk\/devrevinterop\/stopallmonitoring()","type":"topic","title":"stopAllMonitoring()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"stopAllMonitoring","kind":"identifier"}],"abstract":[{"text":"Sets a flag that stops all session monitoring.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/configure(appID:)":{"abstract":[{"text":"Configures the SDK with the app ID.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"configure(appID:)","navigatorTitle":[{"kind":"identifier","text":"configureWithAppID:"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/configure(appid:)","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/showSupport(isAnimated:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSupport"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isAnimated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Presents the support feature modally over the top most view controller."}],"url":"\/documentation\/devrevsdk\/devrevinterop\/showsupport(isanimated:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showSupport:"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(isAnimated:)","title":"showSupport(isAnimated:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRev-7x2h1/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/devrev-7x2h1\/init","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-7x2h1\/init","title":"init"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/identifyVerifiedUser(_:sessionToken:)":{"title":"identifyVerifiedUser(_:sessionToken:)","type":"topic","navigatorTitle":[{"text":"identifyVerifiedUser:sesionToken:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyVerifiedUser(_:sessionToken:)","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/identifyverifieduser(_:sessiontoken:)","abstract":[{"text":"Identifies a verified user after the SDK has been configured.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifyVerifiedUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/registerDeviceToken(_:deviceID:)-9lp2p":{"title":"registerDeviceToken(_:deviceID:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerDeviceToken:forDeviceID:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"deviceID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Registers the processed device token string for receiving push notifications from DevRev."}],"url":"\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-9lp2p","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-9lp2p","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/processPushNotification(_:)-7ncbs":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-7ncbs","type":"topic","kind":"symbol","abstract":[{"text":"Processes the push notification JSON payload and performs the necessary actions.","type":"text"}],"role":"symbol","title":"processPushNotification(_:)","url":"\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)-7ncbs","navigatorTitle":[{"text":"processPushNotification:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processPushNotification","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"abstract":[],"type":"topic","role":"collection","title":"DevRevSDK","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/inAppLinkHandler":{"url":"\/documentation\/devrevsdk\/devrevinterop\/inapplinkhandler","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/inAppLinkHandler","type":"topic","navigatorTitle":[{"text":"inAppLinkHandler","kind":"identifier"}],"abstract":[{"text":"An optional in-app link handler, which can be used to intercept and handle in-app links.","type":"text"}],"title":"inAppLinkHandler","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inAppLinkHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/isRecording":{"role":"symbol","title":"isRecording","type":"topic","abstract":[{"text":"A flag denoting whether the session is being recorded.","type":"text"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/isrecording","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isRecording","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRecording","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/identifyUnverifiedUser(_:)":{"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/identifyunverifieduser(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyUnverifiedUser(_:)","type":"topic","abstract":[{"text":"Identifies an unverified user after the SDK has been configured.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifyUnverifiedUser:"}],"title":"identifyUnverifiedUser(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifyUnverifiedUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Identity","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity"},{"kind":"text","text":")"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/identifyAnonymousUser(userID:)":{"abstract":[{"text":"Identifies an anonymous user after the SDK has been configured.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"identifyAnonymousUser:"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/identifyanonymoususer(userid:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifyAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyAnonymousUser(userID:)","kind":"symbol","title":"identifyAnonymousUser(userID:)","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/isConfigured":{"url":"\/documentation\/devrevsdk\/devrevinterop\/isconfigured","abstract":[{"text":"A flag denoting whether the SDK has been configured.","type":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isConfigured","title":"isConfigured","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isConfigured","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/logout(deviceID:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"logout(deviceID:)","role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/logout(deviceid:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/logout(deviceID:)","navigatorTitle":[{"text":"logoutWithDeviceID:","kind":"identifier"}],"abstract":[{"type":"text","text":"Logs out the current identified user and resets the session."},{"type":"text","text":" "},{"type":"text","text":"The process will also unregister the user’s device from receiving push notifications, and stop any ongoing"},{"type":"text","text":" "},{"type":"text","text":"session recording."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/updateUser(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/updateUser(_:)","abstract":[{"text":"Updates the properties of the current user.","type":"text"}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/updateuser(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUser","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)Identity","text":"Identity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"updateUserWithIdentity:","kind":"identifier"}],"title":"updateUser(_:)","type":"topic","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/startRecording()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Starts a user recording session."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startRecording()","navigatorTitle":[{"kind":"identifier","text":"startRecording"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/startrecording()","role":"symbol","title":"startRecording()"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/unmarkSensitiveViews(_:)":{"role":"symbol","title":"unmarkSensitiveViews(_:)","url":"\/documentation\/devrevsdk\/devrevinterop\/unmarksensitiveviews(_:)","kind":"symbol","navigatorTitle":[{"text":"unmarkSensitiveViews:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmarkSensitiveViews","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkSensitiveViews(_:)","abstract":[{"type":"text","text":"Unmark the passed views as being sensitive."}]},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/addSessionProperties(_:)":{"title":"addSessionProperties(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addSessionProperties"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"url":"\/documentation\/devrevsdk\/devrevinterop\/addsessionproperties(_:)","abstract":[{"type":"text","text":"Adds properties to the session. The properties will be sent along any analytic events."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/addSessionProperties(_:)","role":"symbol","navigatorTitle":[{"text":"addSessionProperties:","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/resumeAllMonitoring()":{"navigatorTitle":[{"kind":"identifier","text":"resumeAllMonitoring"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeAllMonitoring"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Sets a flag that resumes the session monitoring."}],"type":"topic","title":"resumeAllMonitoring()","url":"\/documentation\/devrevsdk\/devrevinterop\/resumeallmonitoring()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/processAllOnDemandSessions()":{"title":"processAllOnDemandSessions()","url":"\/documentation\/devrevsdk\/devrevinterop\/processallondemandsessions()","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processAllOnDemandSessions()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processAllOnDemandSessions","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"processAllOnDemandSessions","kind":"identifier"}],"abstract":[{"text":"Stops the ongoing user recording and sends all on-demand sessions along with the current recording.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/processPushNotification(_:)-5r4j4":{"title":"processPushNotification(_:)","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/processpushnotification(_:)-5r4j4","type":"topic","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-5r4j4","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processPushNotification"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Sendable","preciseIdentifier":"s:s8SendableP"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Processes the push notification and performs the necessary actions."}]},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/isUserIdentified":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/isUserIdentified","abstract":[{"text":"A flag denoting whether the user has been has been provided to the SDK.","type":"text"}],"title":"isUserIdentified","url":"\/documentation\/devrevsdk\/devrevinterop\/isuseridentified","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserIdentified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/startTimer(_:properties:)":{"type":"topic","title":"startTimer(_:properties:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/starttimer(_:properties:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startTimer(_:properties:)","abstract":[{"type":"text","text":"Starts a timer at any point in the app in order to measure time metrics for events such as load or response time."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startTimerWithName:properties:"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/showSupport(from:isAnimated:)-5ycu9":{"type":"topic","title":"showSupport(from:isAnimated:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showSupport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAnimated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-5ycu9","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-5ycu9","abstract":[{"type":"text","text":"Presents the support feature modally."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showSupportFromParentViewController:isAnimated:"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/stopRecording()":{"type":"topic","title":"stopRecording()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopRecording","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/stoprecording()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopRecording()","abstract":[{"type":"text","text":"Stops an ongoing user recording sessions and uploads the session to the portal."}],"role":"symbol","navigatorTitle":[{"text":"stopRecording","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/trackScreenName(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackScreenName","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Manually tracks a screen name for identification."}],"url":"\/documentation\/devrevsdk\/devrevinterop\/trackscreenname(_:)","kind":"symbol","title":"trackScreenName(_:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackScreenName(_:)","navigatorTitle":[{"text":"trackScreenWithName:","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/shouldDismissModalsOnOpenLink":{"navigatorTitle":[{"kind":"identifier","text":"shouldDismissModalsOnOpenLink"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/shouldDismissModalsOnOpenLink","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldDismissModalsOnOpenLink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"shouldDismissModalsOnOpenLink","abstract":[{"type":"text","text":"A flag controlling whether modals are dismissed when opening a link."}],"role":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/shoulddismissmodalsonopenlink"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/registerDeviceToken(_:deviceID:)-3acfg":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"deviceID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"registerDeviceToken(_:deviceID:)","abstract":[{"type":"text","text":"Registers the device token as provided by Apple for receiving push notifications from DevRev."}],"role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/devrevinterop\/registerdevicetoken(_:deviceid:)-3acfg","navigatorTitle":[{"kind":"identifier","text":"registerRawDeviceToken:forDeviceID:"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-3acfg"},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/clearSessionProperties()":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSessionProperties"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","title":"clearSessionProperties()","url":"\/documentation\/devrevsdk\/devrevinterop\/clearsessionproperties()","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","navigatorTitle":[{"kind":"identifier","text":"clearSessionProperties"}],"abstract":[{"type":"text","text":"Clears the session properties."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/DevRevInterop/showSupport(from:isAnimated:)-3d2ry":{"title":"showSupport(from:isAnimated:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSupport"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAnimated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"showSupportFromNavigationController:isAnimated:","kind":"identifier"}],"type":"topic","url":"\/documentation\/devrevsdk\/devrevinterop\/showsupport(from:isanimated:)-3d2ry","abstract":[{"type":"text","text":"Pushes the support feature to your navigation stack."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-3d2ry","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DevRev"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DevRev","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRev-7x2h1\/init"],"anchor":"Instance-Methods"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/inAppLinkHandler","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/shouldDismissModalsOnOpenLink"],"anchor":"Type-Properties"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/addSessionProperties(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/clearSessionProperties()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/configure(appID:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/createSupportConversation(isAnimated:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/endTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyAnonymousUser(userID:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyUnverifiedUser(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/identifyVerifiedUser(_:sessionToken:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/logout(deviceID:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/markSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/pauseRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processAllOnDemandSessions()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/processPushNotification(_:)-7ncbs","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-3acfg","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/registerDeviceToken(_:deviceID:)-9lp2p","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeAllMonitoring()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/resumeRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/sessionURL(for:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/setDelegate(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-3d2ry","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(from:isAnimated:)-5ycu9","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/showSupport(isAnimated:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/startTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopAllMonitoring()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/stopRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackEvent(name:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/trackScreenName(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unmarkSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/unregisterDevice(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/DevRevInterop\/updateUser(_:)"],"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevRev","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1createSupportConversation(isAnimated:)\/title","value":"createSupportConversation:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1createSupportConversation(isAnimated:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createSupportConversation:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeRecording()\/title","value":"resumeRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeRecording()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"resumeRecording","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/title","value":"DevRev"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/fragments","value":[{"text":"DevRev","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop\/navigatorTitle","value":[{"text":"DevRev","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1trackEvent(name:properties:)\/title","value":"trackEventWithName:properties:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1trackEvent(name:properties:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"trackEventWithName:properties:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1sessionURL(for:)\/title","value":"sessionURLForPlatform:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1sessionURL(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sessionURLForPlatform:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1markSensitiveViews(_:)\/title","value":"markSensitiveViews:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1markSensitiveViews(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"markSensitiveViews:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1endTimer(_:properties:)\/title","value":"endTimerWithName:properties:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1endTimer(_:properties:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"endTimerWithName:properties:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1pauseRecording()\/title","value":"pauseRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1pauseRecording()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pauseRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unregisterDevice(_:)\/title","value":"unregisterDeviceWithID:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unregisterDevice(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unregisterDeviceWithID:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1setDelegate(_:)\/title","value":"setDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1setDelegate(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopAllMonitoring()\/title","value":"stopAllMonitoring"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopAllMonitoring()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stopAllMonitoring","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/title","value":"configureWithAppID:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1configure(appID:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"configureWithAppID:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(isAnimated:)\/title","value":"showSupport:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(isAnimated:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showSupport:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyVerifiedUser(_:sessionToken:)\/title","value":"identifyVerifiedUser:sesionToken:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyVerifiedUser(_:sessionToken:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"identifyVerifiedUser:sesionToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-9lp2p\/title","value":"registerDeviceToken:forDeviceID:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-9lp2p\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"registerDeviceToken:forDeviceID:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processPushNotification(_:)-7ncbs\/title","value":"processPushNotification:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processPushNotification(_:)-7ncbs\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processPushNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1inAppLinkHandler\/title","value":"inAppLinkHandler"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1inAppLinkHandler\/fragments","value":[{"text":"inAppLinkHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyUnverifiedUser(_:)\/title","value":"identifyUnverifiedUser:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyUnverifiedUser(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"identifyUnverifiedUser:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyAnonymousUser(userID:)\/title","value":"identifyAnonymousUser:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1identifyAnonymousUser(userID:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"identifyAnonymousUser:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1logout(deviceID:)\/title","value":"logoutWithDeviceID:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1logout(deviceID:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logoutWithDeviceID:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1updateUser(_:)\/title","value":"updateUserWithIdentity:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1updateUser(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateUserWithIdentity:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startRecording()\/title","value":"startRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startRecording()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unmarkSensitiveViews(_:)\/title","value":"unmarkSensitiveViews:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1unmarkSensitiveViews(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unmarkSensitiveViews:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1addSessionProperties(_:)\/title","value":"addSessionProperties:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1addSessionProperties(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addSessionProperties:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeAllMonitoring()\/title","value":"resumeAllMonitoring"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1resumeAllMonitoring()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"resumeAllMonitoring"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processAllOnDemandSessions()\/title","value":"processAllOnDemandSessions"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1processAllOnDemandSessions()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"processAllOnDemandSessions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startTimer(_:properties:)\/title","value":"startTimerWithName:properties:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1startTimer(_:properties:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startTimerWithName:properties:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-5ycu9\/title","value":"showSupportFromParentViewController:isAnimated:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-5ycu9\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showSupportFromParentViewController:isAnimated:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopRecording()\/title","value":"stopRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1stopRecording()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stopRecording","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1trackScreenName(_:)\/title","value":"trackScreenWithName:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1trackScreenName(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"trackScreenWithName:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1shouldDismissModalsOnOpenLink\/title","value":"shouldDismissModalsOnOpenLink"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1shouldDismissModalsOnOpenLink\/fragments","value":[{"text":"shouldDismissModalsOnOpenLink","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-3acfg\/title","value":"registerRawDeviceToken:forDeviceID:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1registerDeviceToken(_:deviceID:)-3acfg\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerRawDeviceToken:forDeviceID:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1clearSessionProperties()\/title","value":"clearSessionProperties"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1clearSessionProperties()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearSessionProperties","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-3d2ry\/title","value":"showSupportFromNavigationController:isAnimated:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1DevRevInterop~1showSupport(from:isAnimated:)-3d2ry\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showSupportFromNavigationController:isAnimated:","kind":"identifier"}]}]}]}