{"metadata":{"modules":[{"name":"DevRevSDK"}],"navigatorTitle":[{"text":"FeatureConfiguration","kind":"identifier"}],"externalID":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureConfiguration"}],"roleHeading":"Class","symbolKind":"class","title":"FeatureConfiguration","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(from:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(witCustomSupportWidgetTheme:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(withShouldEnableFrameCapture:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/alwaysUseRemoteConfig","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/autoStartRecording","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableFrameCapture","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableSupportChatStreaming","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetArticleSearchFilters","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetTheme"]},{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/default"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"sections":[],"variants":[{"paths":["\/documentation\/devrevsdk\/featureconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/devrevsdk\/featureconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A feature configuration class used to customize SDK behavior."}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/enableFrameCapture":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableFrameCapture","title":"enableFrameCapture","url":"\/documentation\/devrevsdk\/featureconfiguration\/enableframecapture","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableFrameCapture"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Enables or disables frame capture for session replay.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableFrameCapture"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration":{"url":"\/documentation\/devrevsdk\/featureconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FeatureConfiguration","kind":"identifier"}],"abstract":[{"text":"A feature configuration class used to customize SDK behavior.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration","role":"symbol","kind":"symbol","title":"FeatureConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureConfiguration"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(withShouldEnableFrameCapture:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithShouldEnableFrameCapture:"}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(withshouldenableframecapture:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShouldEnableFrameCapture"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a configuration that toggles frame capture while preserving the current runtime settings."}],"title":"init(withShouldEnableFrameCapture:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(withShouldEnableFrameCapture:)","type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(from:)":{"abstract":[],"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(from:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(from:)","type":"topic","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/supportWidgetArticleSearchFilters":{"title":"supportWidgetArticleSearchFilters","url":"\/documentation\/devrevsdk\/featureconfiguration\/supportwidgetarticlesearchfilters","abstract":[{"type":"text","text":"Optional filters for PLuG article search (widget and CMDK). Applied when the support widget is ready. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for no filter."}],"role":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetArticleSearchFilters","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"supportWidgetArticleSearchFilters","kind":"identifier"},{"kind":"text","text":": "},{"text":"ArticleSearchFilters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"supportWidgetArticleSearchFilters"}],"kind":"symbol"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject"},"doc://ai.devrev.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/ai.devrev.sdk\/SQ","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/alwaysUseRemoteConfig":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/alwaysUseRemoteConfig","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysUseRemoteConfig"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"alwaysUseRemoteConfig","kind":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration\/alwaysuseremoteconfig","abstract":[{"text":"A flag indicating that always use remote config at initialization.","type":"text"}],"navigatorTitle":[{"text":"alwaysUseRemoteConfig","kind":"identifier"}]},"doc://ai.devrev.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/ai.devrev.sdk\/SH","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/enableSupportChatStreaming":{"navigatorTitle":[{"text":"enableSupportChatStreaming","kind":"identifier"}],"title":"enableSupportChatStreaming","abstract":[{"type":"text","text":"Enables real-time AI agent response streaming in PLuG conversations."}],"type":"topic","url":"\/documentation\/devrevsdk\/featureconfiguration\/enablesupportchatstreaming","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableSupportChatStreaming","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableSupportChatStreaming","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(witCustomSupportWidgetTheme:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithWitCustomSupportWidgetTheme:"}],"url":"\/documentation\/devrevsdk\/featureconfiguration\/init(witcustomsupportwidgettheme:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"witCustomSupportWidgetTheme","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Creates configuration that allows you use set only custom support widget themes.","type":"text"}],"title":"init(witCustomSupportWidgetTheme:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(witCustomSupportWidgetTheme:)","type":"topic","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/default":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DevRevSDK@objc(cs)FeatureConfiguration","text":"FeatureConfiguration","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/default","type":"topic","abstract":[{"text":"The default configuration with enabled frame capture and auto start recording.","type":"text"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/featureconfiguration\/default","title":"default"},"doc://ai.devrev.sdk/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/ai.devrev.sdk\/SE","type":"unresolvable"},"doc://ai.devrev.sdk/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/ai.devrev.sdk\/Se","type":"unresolvable"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://ai.devrev.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)":{"title":"init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","url":"\/documentation\/devrevsdk\/featureconfiguration\/init(enableframecapture:autostartrecording:alwaysuseremoteconfig:supportwidgettheme:enablesupportchatstreaming:supportwidgetarticlesearchfilters:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enableFrameCapture"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoStartRecording"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alwaysUseRemoteConfig"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportWidgetTheme"},{"text":": ","kind":"text"},{"text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"enableSupportChatStreaming"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportWidgetArticleSearchFilters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ArticleSearchFilters","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)ArticleSearchFilters"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Creates an SDK configuration.","type":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/autoStartRecording":{"kind":"symbol","navigatorTitle":[{"text":"autoStartRecording","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/autoStartRecording","abstract":[{"text":"Automatically starts session recording after SDK configuration.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoStartRecording","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"autoStartRecording","url":"\/documentation\/devrevsdk\/featureconfiguration\/autostartrecording","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/supportWidgetTheme":{"abstract":[{"type":"text","text":"The theme for the widget (system “light” or “dark” or custom)."}],"navigatorTitle":[{"text":"supportWidgetTheme","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportWidgetTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","text":"SupportWidgetTheme"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetTheme","url":"\/documentation\/devrevsdk\/featureconfiguration\/supportwidgettheme","type":"topic","title":"supportWidgetTheme","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/FeatureConfiguration/default_":{"url":"\/documentation\/devrevsdk\/featureconfiguration\/default_","kind":"symbol","abstract":[{"type":"text","text":"The default configuration with enabled frame capture and auto start recording."}],"fragments":[{"text":"default_","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/default_","type":"topic","title":"default_"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"FeatureConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"FeatureConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"FeatureConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/alwaysUseRemoteConfig","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/autoStartRecording","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableFrameCapture","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/enableSupportChatStreaming","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetArticleSearchFilters","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/supportWidgetTheme"]},{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(witCustomSupportWidgetTheme:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/init(withShouldEnableFrameCapture:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/FeatureConfiguration\/default_"],"title":"Type Properties","anchor":"Type-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureConfiguration"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableFrameCapture\/title","value":"enableFrameCapture"},{"value":[{"text":"enableFrameCapture","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableFrameCapture\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/title","value":"FeatureConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/fragments","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FeatureConfiguration"}]},{"op":"replace","value":"initWithShouldEnableFrameCapture:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(withShouldEnableFrameCapture:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(withShouldEnableFrameCapture:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithShouldEnableFrameCapture:","kind":"identifier"}]},{"value":"supportWidgetArticleSearchFilters","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetArticleSearchFilters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"supportWidgetArticleSearchFilters"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetArticleSearchFilters\/fragments"},{"op":"replace","value":"alwaysUseRemoteConfig","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1alwaysUseRemoteConfig\/title"},{"value":[{"kind":"identifier","text":"alwaysUseRemoteConfig"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1alwaysUseRemoteConfig\/fragments"},{"value":"enableSupportChatStreaming","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableSupportChatStreaming\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1enableSupportChatStreaming\/fragments","op":"replace","value":[{"text":"enableSupportChatStreaming","kind":"identifier"}]},{"value":"initWithWitCustomSupportWidgetTheme:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(witCustomSupportWidgetTheme:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(witCustomSupportWidgetTheme:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithWitCustomSupportWidgetTheme:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)\/title","value":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1init(enableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithEnableFrameCapture:autoStartRecording:alwaysUseRemoteConfig:supportWidgetTheme:enableSupportChatStreaming:supportWidgetArticleSearchFilters:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1autoStartRecording\/title","op":"replace","value":"autoStartRecording"},{"value":[{"text":"autoStartRecording","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1autoStartRecording\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetTheme\/title","op":"replace","value":"supportWidgetTheme"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1FeatureConfiguration~1supportWidgetTheme\/fragments","value":[{"kind":"identifier","text":"supportWidgetTheme"}]}]}]}