{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"text":" ","type":"text"},{"type":"text","text":"The minimum information needed is the "},{"type":"reference","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","isActive":true},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/devrevsdk\/identity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/identity"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity"},"topicSections":[{"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class"],"generated":true},{"generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(from:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountID","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountTraits-swift.property","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/debugDescription","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationID","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationTraits-swift.property","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userTraits-swift.property"],"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Identity","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"content":[{"inlineContent":[{"text":"Some features cannot be used prior to having the user identified.","type":"text"}],"type":"paragraph"}],"name":"Important","style":"important","type":"aside"}]}],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"Identity","navigatorTitle":[{"kind":"identifier","text":"Identity"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)Identity"},"sections":[],"kind":"symbol","references":{"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/AccountTraits-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"AccountTraits"}],"abstract":[{"type":"text","text":"A collection of traits describing the account."}],"role":"symbol","title":"Identity.AccountTraits","kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountTraits"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/AccountTraits-swift.class","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/organizationID":{"abstract":[{"type":"text","text":"An organization identifier."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"organizationID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"organizationID","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity\/organizationid","type":"topic","title":"organizationID","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationID"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/accountID":{"role":"symbol","kind":"symbol","type":"topic","title":"accountID","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountID","navigatorTitle":[{"text":"accountID","kind":"identifier"}],"abstract":[{"text":"An account identifier.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accountID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/devrevsdk\/identity\/accountid"},"doc://ai.devrev.sdk/Se":{"identifier":"doc:\/\/ai.devrev.sdk\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity":{"role":"symbol","url":"\/documentation\/devrevsdk\/identity","navigatorTitle":[{"text":"Identity","kind":"identifier"}],"title":"Identity","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"}],"abstract":[{"type":"text","text":"A JSON-represented structure that describes your customer’s identity information."},{"type":"text","text":" "},{"type":"text","text":"The information can be either on the level of organizations or your user."},{"type":"text","text":" "},{"text":"The minimum information needed is the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID"},{"text":".","type":"text"}],"kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/SE":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SE","title":"Swift.Encodable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userID":{"role":"symbol","url":"\/documentation\/devrevsdk\/identity\/userid","navigatorTitle":[{"kind":"identifier","text":"userID"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","title":"userID","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"userID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"A user identifier."}],"kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/debugDescription":{"title":"debugDescription","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/debugDescription","abstract":[],"url":"\/documentation\/devrevsdk\/identity\/debugdescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/UserTraits-swift.class":{"role":"symbol","url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.class","navigatorTitle":[{"kind":"identifier","text":"UserTraits"}],"title":"Identity.UserTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/UserTraits-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserTraits"}],"abstract":[{"type":"text","text":"A collection of traits describing the user."}],"kind":"symbol","type":"topic"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/organizationTraits-swift.property":{"role":"symbol","kind":"symbol","type":"topic","title":"organizationTraits","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationTraits-swift.property","navigatorTitle":[{"text":"organizationTraits","kind":"identifier"}],"abstract":[{"text":"A collection of traits describing the organization.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"organizationTraits"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC","kind":"typeIdentifier","text":"OrganizationTraits"},{"text":"?","kind":"text"}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.property"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)":{"title":"init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)","navigatorTitle":[{"kind":"identifier","text":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)","abstract":[{"text":"Creates an identity structure.","type":"text"}],"url":"\/documentation\/devrevsdk\/identity\/init(userid:organizationid:accountid:usertraits:organizationtraits:accounttraits:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"organizationID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accountID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"userTraits"},{"text":": ","kind":"text"},{"text":"UserTraits","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC"},{"kind":"text","text":"?, "},{"text":"organizationTraits","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC18OrganizationTraitsC","text":"OrganizationTraits"},{"text":"?, ","kind":"text"},{"text":"accountTraits","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC","text":"AccountTraits"},{"text":"?)","kind":"text"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/init(from:)":{"role":"symbol","kind":"symbol","type":"topic","title":"init(from:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/devrevsdk\/identity\/init(from:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","title":"DevRevSDK","abstract":[],"url":"\/documentation\/devrevsdk","kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/accountTraits-swift.property":{"title":"accountTraits","navigatorTitle":[{"kind":"identifier","text":"accountTraits"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountTraits-swift.property","abstract":[{"text":"A collection of traits describing the account.","type":"text"}],"url":"\/documentation\/devrevsdk\/identity\/accounttraits-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accountTraits","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK8IdentityC13AccountTraitsC","text":"AccountTraits"},{"text":"?","kind":"text"}]},"doc://ai.devrev.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.devrev.sdk\/SQ"},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/userTraits-swift.property":{"abstract":[{"type":"text","text":"A collection of traits describing the user."}],"type":"topic","title":"userTraits","navigatorTitle":[{"text":"userTraits","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/devrevsdk\/identity\/usertraits-swift.property","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userTraits-swift.property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userTraits"},{"text":": ","kind":"text"},{"text":"UserTraits","preciseIdentifier":"s:9DevRevSDK8IdentityC10UserTraitsC","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/Identity/OrganizationTraits-swift.class":{"navigatorTitle":[{"text":"OrganizationTraits","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/OrganizationTraits-swift.class","title":"Identity.OrganizationTraits","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OrganizationTraits","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/identity\/organizationtraits-swift.class","abstract":[{"type":"text","text":"A collection of traits describing the organization."}],"type":"topic","role":"symbol","kind":"symbol"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"Identity","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"Identity","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"Identity"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountID","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/accountTraits-swift.property","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/debugDescription","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationID","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/organizationTraits-swift.property","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userID","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/userTraits-swift.property"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/Identity\/init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identity","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationID\/title","op":"replace","value":"organizationID"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationID\/fragments","value":[{"text":"organizationID","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1accountID\/title","value":"accountID"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1accountID\/fragments","op":"replace","value":[{"text":"accountID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/title","value":"Identity","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/fragments","value":[{"kind":"identifier","text":"Identity"}],"op":"replace"},{"value":[{"text":"Identity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/title","value":"userID"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1debugDescription\/title","op":"replace","value":"debugDescription"},{"value":[{"text":"debugDescription","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1debugDescription\/fragments"},{"op":"replace","value":"organizationTraits","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationTraits-swift.property\/title"},{"value":[{"kind":"identifier","text":"organizationTraits"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1organizationTraits-swift.property\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)\/title","value":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUserID:organizationID:accountID:userTraits:organizationTraits:accountTraits:"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1init(userID:organizationID:accountID:userTraits:organizationTraits:accountTraits:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1accountTraits-swift.property\/title","value":"accountTraits"},{"value":[{"kind":"identifier","text":"accountTraits"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1accountTraits-swift.property\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userTraits-swift.property\/title","value":"userTraits"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1Identity~1userTraits-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"userTraits"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}