{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"metadata":{"role":"symbol","title":"SnapshotMask","symbolKind":"class","externalID":"c:@M@DevRevSDK@objc(cs)SnapshotMask","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SnapshotMask"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SnapshotMask"}],"modules":[{"name":"DevRevSDK"}]},"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/init(locations:shouldSkip:)"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask"},"abstract":[{"type":"text","text":"A class that describes the regions of a snapshot to be masked for privacy purposes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SnapshotMask"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this class to specify which areas of a UI snapshot should be obscured, such as sensitive information or private content."},{"type":"text","text":" "},{"text":"The mask is defined by a collection of rectangles, each representing a region to be masked.","type":"text"},{"text":" ","type":"text"},{"text":"You can also indicate whether the snapshot should be skipped entirely.","type":"text"}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Masking regions help protect user privacy by preventing sensitive areas from being captured in snapshots.","type":"text"}]}],"style":"important","name":"Important"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"DevRev.MaskLocationProviding"}]}],"type":"aside","style":"note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/devrevsdk\/snapshotmask"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/snapshotmask"]}],"references":{"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://ai.devrev.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SQ","title":"Swift.Equatable"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"title":"DevRevSDK","role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask":{"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask","type":"topic","abstract":[{"type":"text","text":"A class that describes the regions of a snapshot to be masked for privacy purposes."}],"url":"\/documentation\/devrevsdk\/snapshotmask","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SnapshotMask","kind":"identifier"}],"title":"SnapshotMask","role":"symbol","navigatorTitle":[{"text":"SnapshotMask","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/Location":{"type":"topic","abstract":[{"text":"A class that describes the regions with its mask type.","type":"text"}],"url":"\/documentation\/devrevsdk\/snapshotmask\/location","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Location","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/Location","navigatorTitle":[{"text":"Location","kind":"identifier"}],"title":"SnapshotMask.Location"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SnapshotMask/init(locations:shouldSkip:)":{"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SnapshotMask\/init(locations:shouldSkip:)","type":"topic","abstract":[{"type":"text","text":"Creates a snapshot mask configuration for external mask type."}],"url":"\/documentation\/devrevsdk\/snapshotmask\/init(locations:shouldskip:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"locations","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Location","kind":"typeIdentifier","preciseIdentifier":"s:9DevRevSDK12SnapshotMaskC8LocationC"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"shouldSkip"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(locations:shouldSkip:)","role":"symbol"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","title":"NSObject"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SnapshotMask","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"SnapshotMask","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SnapshotMask","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SnapshotMask","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SnapshotMask","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/fragments","value":[{"kind":"identifier","text":"SnapshotMask"}],"op":"replace"},{"value":[{"text":"SnapshotMask","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SnapshotMask\/navigatorTitle"}]}]}