{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/devrevsdk\/supportwidgettheme"]},{"paths":["\/documentation\/devrevsdk\/supportwidgettheme"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportWidgetTheme"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/Se","doc:\/\/ai.devrev.sdk\/SE","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","role":"symbol","navigatorTitle":[{"text":"SupportWidgetTheme","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportWidgetTheme","kind":"identifier"}],"roleHeading":"Class","title":"SupportWidgetTheme"},"topicSections":[{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(from:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/accentColor","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/prefersSystemTheme","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/primaryTextColor","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/spacing"]},{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/systemDefault"],"anchor":"Type-Properties","title":"Type Properties","generated":true}],"references":{"doc://ai.devrev.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SQ"},"doc://ai.devrev.sdk/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SE"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/spacing":{"url":"\/documentation\/devrevsdk\/supportwidgettheme\/spacing","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"abstract":[{"text":"The spacing configuration as a dictionary with “bottom” and “side” keys (e.g., [“bottom”: “20px”, “side”: “15px”]).","type":"text"}],"title":"spacing","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/spacing","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"spacing"}]},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject","title":"NSObject"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/accentColor":{"url":"\/documentation\/devrevsdk\/supportwidgettheme\/accentcolor","title":"accentColor","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The accent color for the widget (e.g., “#FF5733” or “rgb(255, 87, 51)”)."}],"navigatorTitle":[{"text":"accentColor","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/accentColor"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/init(from:)":{"url":"\/documentation\/devrevsdk\/supportwidgettheme\/init(from:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(from:)","kind":"symbol","title":"init(from:)","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)":{"type":"topic","title":"init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prefersSystemTheme"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"primaryTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"accentColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"spacing","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"url":"\/documentation\/devrevsdk\/supportwidgettheme\/init(preferssystemtheme:primarytextcolor:accentcolor:spacing:)","abstract":[{"type":"text","text":"Creates a support widget configuration."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)","navigatorTitle":[{"text":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme":{"type":"topic","url":"\/documentation\/devrevsdk\/supportwidgettheme","title":"SupportWidgetTheme","kind":"symbol","abstract":[{"type":"text","text":"A theme class used to customize the support widget appearance."}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme","navigatorTitle":[{"kind":"identifier","text":"SupportWidgetTheme"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SupportWidgetTheme"}]},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://ai.devrev.sdk/Se":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/Se","title":"Swift.Decodable"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","type":"topic","abstract":[],"title":"DevRevSDK","kind":"symbol","role":"collection","url":"\/documentation\/devrevsdk"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/systemDefault":{"title":"systemDefault","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The default configuration that follows the system theme."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"systemDefault"},{"kind":"text","text":": "},{"text":"SupportWidgetTheme","preciseIdentifier":"c:@M@DevRevSDK@objc(cs)SupportWidgetTheme","kind":"typeIdentifier"}],"url":"\/documentation\/devrevsdk\/supportwidgettheme\/systemdefault","navigatorTitle":[{"text":"systemDefault","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/systemDefault"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/SH","title":"Swift.Hashable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/prefersSystemTheme":{"title":"prefersSystemTheme","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A flag to use the default theme for the support feature."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersSystemTheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/devrevsdk\/supportwidgettheme\/preferssystemtheme","navigatorTitle":[{"kind":"identifier","text":"prefersSystemTheme"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/prefersSystemTheme"},"doc://ai.devrev.sdk/documentation/DevRevSDK/SupportWidgetTheme/primaryTextColor":{"type":"topic","navigatorTitle":[{"text":"primaryTextColor","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/primaryTextColor","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"primaryTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The primary text color for the widget (e.g., “#000000” or “rgb(0, 0, 0)”)."}],"title":"primaryTextColor","role":"symbol","url":"\/documentation\/devrevsdk\/supportwidgettheme\/primarytextcolor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SupportWidgetTheme"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SupportWidgetTheme","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/accentColor","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/prefersSystemTheme","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/primaryTextColor","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/spacing"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)"],"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/SupportWidgetTheme\/systemDefault"],"anchor":"Type-Properties","title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SupportWidgetTheme"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"spacing","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1spacing\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1spacing\/fragments","op":"replace","value":[{"text":"spacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1accentColor\/title","value":"accentColor","op":"replace"},{"value":[{"text":"accentColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1accentColor\/fragments"},{"value":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1init(prefersSystemTheme:primaryTextColor:accentColor:spacing:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPrefersSystemTheme:primaryTextColor:accentColor:spacing:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/title","value":"SupportWidgetTheme","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/fragments","op":"replace","value":[{"kind":"identifier","text":"SupportWidgetTheme"}]},{"value":[{"kind":"identifier","text":"SupportWidgetTheme"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1systemDefault\/title","op":"replace","value":"systemDefault"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1systemDefault\/fragments","value":[{"kind":"identifier","text":"systemDefault"}],"op":"replace"},{"value":"prefersSystemTheme","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1prefersSystemTheme\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1prefersSystemTheme\/fragments","value":[{"text":"prefersSystemTheme","kind":"identifier"}],"op":"replace"},{"value":"primaryTextColor","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1primaryTextColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"primaryTextColor"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1SupportWidgetTheme~1primaryTextColor\/fragments"}]}]}