{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(UserExperior) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}]}]}],"variants":[{"paths":["\/documentation\/devrevsdk\/userexperior"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/devrevsdk\/userexperior"]}],"kind":"symbol","identifier":{"url":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","interfaceLanguage":"swift"},"abstract":[{"text":"Primary class to integrate UserExperior in your app","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/ai.devrev.sdk\/objc(pl)NSObject","doc:\/\/ai.devrev.sdk\/s7CVarArgP","doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","doc:\/\/ai.devrev.sdk\/SQ","doc:\/\/ai.devrev.sdk\/SH"],"kind":"relationships"}],"metadata":{"modules":[{"name":"DevRevSDK"}],"externalID":"c:@M@DevRevSDK@objc(cs)UserExperior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}],"symbolKind":"class","title":"UserExperior"},"hierarchy":{"paths":[["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getConsentStatus","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getOptOutStatus","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/isRecording"]},{"title":"Type Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/activateThirdPartyAnalyticsMonitor()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/addSessionProperties(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/consentOptIn()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/consentOptOut()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/endTimer(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/endTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/exposeSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getSessionUrl(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logEvent(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logEvent(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logMessage(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logMessage(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/markSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/pauseRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/resumeRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setDelegate(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setUserIdentifier(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:_:_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startScreen(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startTimer(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkAllSensitives()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/updateRevUserData(revOrgId:revUserId:isAnonymous:)"]}],"references":{"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/init":{"abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/init","url":"\/documentation\/devrevsdk\/userexperior\/init","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/resumeRecording()":{"abstract":[{"text":"Resumes the paused  recording.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/resumeRecording()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resumeRecording","kind":"identifier"},{"text":"()","kind":"text"}],"title":"resumeRecording()","navigatorTitle":[{"kind":"identifier","text":"resumeRecording"}],"type":"topic","kind":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/resumerecording()","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/updateRevUserData(revOrgId:revUserId:isAnonymous:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/updateRevUserData(revOrgId:revUserId:isAnonymous:)","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateRevUserData","kind":"identifier"},{"kind":"text","text":"("},{"text":"revOrgId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"revUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAnonymous"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"url":"\/documentation\/devrevsdk\/userexperior\/updaterevuserdata(revorgid:revuserid:isanonymous:)","type":"topic","kind":"symbol","title":"updateRevUserData(revOrgId:revUserId:isAnonymous:)","navigatorTitle":[{"kind":"identifier","text":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/stopRecording()":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopRecording()","role":"symbol","type":"topic","title":"stopRecording()","abstract":[{"text":"Stop ongoing user recording and send the session to the portal.","type":"text"}],"url":"\/documentation\/devrevsdk\/userexperior\/stoprecording()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"stopRecording","kind":"identifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/setUserIdentifier(_:)":{"abstract":[{"text":"UserExperior SDK by default takes the device id as a user identifier.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserIdentifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setUserIdentifier:","kind":"identifier"}],"title":"setUserIdentifier(_:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setUserIdentifier(_:)","url":"\/documentation\/devrevsdk\/userexperior\/setuseridentifier(_:)","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/activateThirdPartyAnalyticsMonitor()":{"abstract":[{"text":"Activates the third party analytics monitoring system","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/activateThirdPartyAnalyticsMonitor()","url":"\/documentation\/devrevsdk\/userexperior\/activatethirdpartyanalyticsmonitor()","title":"activateThirdPartyAnalyticsMonitor()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"activateThirdPartyAnalyticsMonitor","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/addSessionProperties(_:)":{"abstract":[{"text":"Log user properties","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addSessionProperties","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"addSessionProperties:"}],"title":"addSessionProperties(_:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/addSessionProperties(_:)","url":"\/documentation\/devrevsdk\/userexperior\/addsessionproperties(_:)","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/endTimer(_:)":{"deprecated":true,"abstract":[{"type":"text","text":"UserExperior SDK allows you to track the load\/ response time of the components in your app using a method called startTimer and endTimer."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTimer"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"endTimerWithName:"}],"title":"endTimer(_:)","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/endTimer(_:)","url":"\/documentation\/devrevsdk\/userexperior\/endtimer(_:)","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/getOptOutStatus":{"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getOptOutStatus","kind":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/getoptoutstatus","title":"getOptOutStatus","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getOptOutStatus"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getOptOutStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/exposeSensitiveViews(_:)":{"abstract":[{"type":"text","text":"Disable auto masking for selected auto masked views"}],"navigatorTitle":[{"kind":"identifier","text":"exposeSensitiveViewsWithViewsToExpose:"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/exposeSensitiveViews(_:)","url":"\/documentation\/devrevsdk\/userexperior\/exposesensitiveviews(_:)","type":"topic","title":"exposeSensitiveViews(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposeSensitiveViews"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/getSessionUrl(_:)":{"url":"\/documentation\/devrevsdk\/userexperior\/getsessionurl(_:)","type":"topic","abstract":[{"type":"text","text":"Get  User session URL for third party integrations"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getSessionUrlWithPlatformName:"}],"title":"getSessionUrl(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getSessionUrl(_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSessionUrl"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/pauseRecording()":{"kind":"symbol","abstract":[{"type":"text","text":"Pauses the ongoing user recording."}],"url":"\/documentation\/devrevsdk\/userexperior\/pauserecording()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pauseRecording"}],"role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/pauseRecording()","title":"pauseRecording()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseRecording"},{"kind":"text","text":"()"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/unmarkSensitiveViews(_:)":{"navigatorTitle":[{"kind":"identifier","text":"unmarkSensitiveViewsWithViewToUnBlock:"}],"url":"\/documentation\/devrevsdk\/userexperior\/unmarksensitiveviews(_:)","kind":"symbol","title":"unmarkSensitiveViews(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmarkSensitiveViews","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkSensitiveViews(_:)","abstract":[{"type":"text","text":"Stop masking given views."}],"role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/stopTimer(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:)","url":"\/documentation\/devrevsdk\/userexperior\/stoptimer(_:)","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"stopTimer(_:)","navigatorTitle":[{"text":"stopTimerWithName:","kind":"identifier"}],"abstract":[],"deprecated":true,"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/startTimer(_:)":{"navigatorTitle":[{"text":"startTimerWithName:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/starttimer(_:)","abstract":[{"text":"UserExperior SDK allows you to track the load\/ response time of the components in your app using a method called startTimer and endTimer.","type":"text"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startTimer(_:)","title":"startTimer(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startTimer"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"deprecated":true,"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/endTimer(_:properties:)":{"abstract":[{"type":"text","text":"UserExperior SDK allows you to track the load\/ response time of the components in your app using a method called startTimer and stopTimer."}],"navigatorTitle":[{"kind":"identifier","text":"endTimerWithName:properties:"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/endTimer(_:properties:)","url":"\/documentation\/devrevsdk\/userexperior\/endtimer(_:properties:)","type":"topic","title":"endTimer(_:properties:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"endTimer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"kind":"symbol"},"doc://ai.devrev.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"},"doc://ai.devrev.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.devrev.sdk\/SH"},"doc://ai.devrev.sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ai.devrev.sdk\/s7CVarArgP"},"doc://ai.devrev.sdk/documentation/DevRevSDK":{"role":"collection","url":"\/documentation\/devrevsdk","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK","abstract":[],"type":"topic","kind":"symbol","title":"DevRevSDK"},"doc://ai.devrev.sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ai.devrev.sdk\/objc(pl)NSObject"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/startRecording(_:)":{"abstract":[{"type":"text","text":"Start user recording."}],"navigatorTitle":[{"text":"startRecordingWithVersionKey:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:)","url":"\/documentation\/devrevsdk\/userexperior\/startrecording(_:)","type":"topic","title":"startRecording(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/markSensitiveViews(_:)":{"abstract":[{"text":"Mask given views. They will show as masked in portal playbacks.","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/markSensitiveViews(_:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"markSensitiveViews","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/marksensitiveviews(_:)","title":"markSensitiveViews(_:)"},"doc://ai.devrev.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/ai.devrev.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/consentOptIn()":{"title":"consentOptIn()","role":"symbol","kind":"symbol","abstract":[{"text":"User Opted-in for user recording permission","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentOptIn"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/consentOptIn()","navigatorTitle":[{"text":"consentOptIn","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/userexperior\/consentoptin()"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior","abstract":[{"type":"text","text":"Primary class to integrate UserExperior in your app"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserExperior"}],"url":"\/documentation\/devrevsdk\/userexperior","type":"topic","kind":"symbol","title":"UserExperior","navigatorTitle":[{"kind":"identifier","text":"UserExperior"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/logMessage(_:)":{"abstract":[{"text":"UserExperior SDK lets you log user messages based on the scenario.","type":"text"}],"title":"logMessage(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logMessage(_:)","kind":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/logmessage(_:)","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logMessage","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"logMessageWithName:","kind":"identifier"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/startTimer(_:properties:)":{"navigatorTitle":[{"text":"startTimerWithName:properties:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startTimer(_:properties:)","kind":"symbol","title":"startTimer(_:properties:)","url":"\/documentation\/devrevsdk\/userexperior\/starttimer(_:properties:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"UserExperior SDK allows you to track the load\/ response time of the components in your app using a method called startTimer and endTimer."}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/startRecording(_:_:_:)":{"abstract":[{"text":"Start user recording with framework and sdk version (In case of Hybrid platform ONLY)","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:_:_:)","role":"symbol","title":"startRecording(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"startRecordingWithVersionKey:fw:sv:"}],"url":"\/documentation\/devrevsdk\/userexperior\/startrecording(_:_:_:)","type":"topic"},"doc://ai.devrev.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/ai.devrev.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/isRecording":{"abstract":[{"type":"text","text":"Get the currect recording status of SDK."}],"title":"isRecording","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRecording","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isRecording","kind":"identifier"}],"url":"\/documentation\/devrevsdk\/userexperior\/isrecording","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/isRecording","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/logEvent(_:properties:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"properties"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"type":"topic","navigatorTitle":[{"text":"logEventWithName:properties:","kind":"identifier"}],"title":"logEvent(_:properties:)","kind":"symbol","url":"\/documentation\/devrevsdk\/userexperior\/logevent(_:properties:)","abstract":[{"text":"Log a custom Event with along its Properties","type":"text"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logEvent(_:properties:)"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/startScreen(_:)":{"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startScreen(_:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startScreen"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startScreenWithName:"}],"role":"symbol","abstract":[{"text":"UserExperior SDK automatically detects ViewController and defines them as screens.","type":"text"}],"title":"startScreen(_:)","url":"\/documentation\/devrevsdk\/userexperior\/startscreen(_:)","type":"topic"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/logEvent(_:)":{"role":"symbol","navigatorTitle":[{"text":"logEventWithName:","kind":"identifier"}],"abstract":[{"text":"UserExperior SDK lets you log user events based on the scenario. An event is the indication of Progress in the user’s session.","type":"text"}],"url":"\/documentation\/devrevsdk\/userexperior\/logevent(_:)","type":"topic","title":"logEvent(_:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logEvent(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logEvent","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/logMessage(_:properties:)":{"navigatorTitle":[{"kind":"identifier","text":"logMessageWithName:properties:"}],"deprecated":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logMessage","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"properties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"kind":"symbol","title":"logMessage(_:properties:)","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logMessage(_:properties:)","url":"\/documentation\/devrevsdk\/userexperior\/logmessage(_:properties:)","abstract":[{"type":"text","text":"Log a custom Message with along its Properties"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/unmarkAllSensitives()":{"navigatorTitle":[{"text":"unmarkAllSensitives","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkAllSensitives()","kind":"symbol","title":"unmarkAllSensitives()","url":"\/documentation\/devrevsdk\/userexperior\/unmarkallsensitives()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmarkAllSensitives","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Stop masking all previously masked views. Effects only manually masked views"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/stopTimer(_:properties:)":{"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:properties:)","kind":"symbol","abstract":[],"url":"\/documentation\/devrevsdk\/userexperior\/stoptimer(_:properties:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopTimer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"properties"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"title":"stopTimer(_:properties:)","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"stopTimerWithName:properties:"}]},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/setDelegate(_:)":{"kind":"symbol","title":"setDelegate(_:)","abstract":[{"type":"text","text":"Set User Experior Delegate"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DevRevDelegate","preciseIdentifier":"c:@M@DevRevSDK@objc(pl)DevRevDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/devrevsdk\/userexperior\/setdelegate(_:)","type":"topic","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setDelegate(_:)","role":"symbol"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/getConsentStatus":{"url":"\/documentation\/devrevsdk\/userexperior\/getconsentstatus","abstract":[{"type":"text","text":"Get a consent request status"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConsentStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"getConsentStatus"}],"title":"getConsentStatus","role":"symbol","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getConsentStatus","type":"topic"},"doc://ai.devrev.sdk/SQ":{"identifier":"doc:\/\/ai.devrev.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://ai.devrev.sdk/documentation/DevRevSDK/UserExperior/consentOptOut()":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"consentOptOut","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","title":"consentOptOut()","navigatorTitle":[{"kind":"identifier","text":"consentOptOut"}],"type":"topic","identifier":"doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/consentOptOut()","url":"\/documentation\/devrevsdk\/userexperior\/consentoptout()","abstract":[{"type":"text","text":"User Opted-out for user recording permission"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"UserExperior","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"UserExperior"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"UserExperior"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/init"]},{"identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getConsentStatus","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getOptOutStatus","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/isRecording"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/activateThirdPartyAnalyticsMonitor()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/addSessionProperties(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/consentOptIn()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/consentOptOut()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/endTimer(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/endTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/exposeSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/getSessionUrl(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logEvent(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logEvent(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logMessage(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/logMessage(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/markSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/pauseRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/resumeRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setDelegate(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/setUserIdentifier(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startRecording(_:_:_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startScreen(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startTimer(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/startTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopRecording()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/stopTimer(_:properties:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkAllSensitives()","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/unmarkSensitiveViews(_:)","doc:\/\/ai.devrev.sdk\/documentation\/DevRevSDK\/UserExperior\/updateRevUserData(revOrgId:revUserId:isAnonymous:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/ai.devrev.sdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"UserExperior","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1resumeRecording()\/title","op":"replace","value":"resumeRecording"},{"value":[{"text":"+ ","kind":"text"},{"text":"resumeRecording","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1resumeRecording()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1updateRevUserData(revOrgId:revUserId:isAnonymous:)\/title","value":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1updateRevUserData(revOrgId:revUserId:isAnonymous:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"updateRevUserDataWithRevOrgId:revUserId:isAnonymous:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopRecording()\/title","value":"stopRecording"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stopRecording"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopRecording()\/fragments"},{"value":"setUserIdentifier:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1setUserIdentifier(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1setUserIdentifier(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setUserIdentifier:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1activateThirdPartyAnalyticsMonitor()\/title","value":"activateThirdPartyAnalyticsMonitor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1activateThirdPartyAnalyticsMonitor()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"activateThirdPartyAnalyticsMonitor"}]},{"op":"replace","value":"addSessionProperties:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1addSessionProperties(_:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1addSessionProperties(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"addSessionProperties:"}],"op":"replace"},{"op":"replace","value":"endTimerWithName:","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1endTimer(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"endTimerWithName:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1endTimer(_:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1getOptOutStatus\/title","op":"replace","value":"getOptOutStatus"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1getOptOutStatus\/fragments","op":"replace","value":[{"text":"getOptOutStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1exposeSensitiveViews(_:)\/title","value":"exposeSensitiveViewsWithViewsToExpose:","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1exposeSensitiveViews(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"exposeSensitiveViewsWithViewsToExpose:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1getSessionUrl(_:)\/title","value":"getSessionUrlWithPlatformName:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"getSessionUrlWithPlatformName:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1getSessionUrl(_:)\/fragments","op":"replace"},{"op":"replace","value":"pauseRecording","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1pauseRecording()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"pauseRecording","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1pauseRecording()\/fragments"},{"value":"unmarkSensitiveViewsWithViewToUnBlock:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkSensitiveViews(_:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkSensitiveViews(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unmarkSensitiveViewsWithViewToUnBlock:","kind":"identifier"}],"op":"replace"},{"value":"stopTimerWithName:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopTimer(_:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopTimer(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"stopTimerWithName:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startTimer(_:)\/title","value":"startTimerWithName:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startTimerWithName:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startTimer(_:)\/fragments"},{"value":"endTimerWithName:properties:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1endTimer(_:properties:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"endTimerWithName:properties:"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1endTimer(_:properties:)\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startRecording(_:)\/title","op":"replace","value":"startRecordingWithVersionKey:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startRecording(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"startRecordingWithVersionKey:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1markSensitiveViews(_:)\/title","value":"markSensitiveViewsWithViewToSecure:"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1markSensitiveViews(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"markSensitiveViewsWithViewToSecure:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1consentOptIn()\/title","op":"replace","value":"consentOptIn"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"consentOptIn"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1consentOptIn()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/title","op":"replace","value":"UserExperior"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior\/fragments","value":[{"text":"UserExperior","kind":"identifier"}]},{"value":"logMessageWithName:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logMessage(_:)\/title"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logMessage(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"logMessageWithName:"}],"op":"replace"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startTimer(_:properties:)\/title","op":"replace","value":"startTimerWithName:properties:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startTimer(_:properties:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startTimerWithName:properties:"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startRecording(_:_:_:)\/title","value":"startRecordingWithVersionKey:fw:sv:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startRecordingWithVersionKey:fw:sv:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startRecording(_:_:_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1isRecording\/title","value":"isRecording"},{"value":[{"text":"isRecording","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1isRecording\/fragments"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logEvent(_:properties:)\/title","op":"replace","value":"logEventWithName:properties:"},{"value":[{"text":"+ ","kind":"text"},{"text":"logEventWithName:properties:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logEvent(_:properties:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startScreen(_:)\/title","value":"startScreenWithName:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1startScreen(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startScreenWithName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logEvent(_:)\/title","value":"logEventWithName:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logEventWithName:"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logEvent(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logMessage(_:properties:)\/title","value":"logMessageWithName:properties:"},{"value":[{"kind":"text","text":"+ "},{"text":"logMessageWithName:properties:","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1logMessage(_:properties:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkAllSensitives()\/title","value":"unmarkAllSensitives"},{"value":[{"kind":"text","text":"+ "},{"text":"unmarkAllSensitives","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1unmarkAllSensitives()\/fragments"},{"value":"stopTimerWithName:properties:","op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopTimer(_:properties:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopTimerWithName:properties:"}],"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1stopTimer(_:properties:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1setDelegate(_:)\/title","value":"setDelegate:"},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1setDelegate(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"getConsentStatus","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1getConsentStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1getConsentStatus\/fragments","value":[{"text":"getConsentStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1consentOptOut()\/title","op":"replace","value":"consentOptOut"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"consentOptOut","kind":"identifier"}],"path":"\/references\/doc:~1~1ai.devrev.sdk~1documentation~1DevRevSDK~1UserExperior~1consentOptOut()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}